---
title: "main_body_size"
author: "Emanuele Giacomuzzo"
date: "2022-08-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Aim

### Data manipulation

#### Import

```{r}
culture_info = read.csv(here("data", "PatchSizePilot_culture_info.csv"), header = TRUE)
load(here("data", "morphology", "t0.RData"));t0 = morph_mvt
load(here("data", "morphology", "t1.RData"));t1 = morph_mvt
load(here("data", "morphology", "t2.RData"));t2 = morph_mvt
load(here("data", "morphology", "t3.RData"));t3 = morph_mvt
load(here("data", "morphology", "t4.RData"));t4 = morph_mvt
load(here("data", "morphology", "t5.RData"));t5 = morph_mvt
load(here("data", "morphology", "t6.RData"));t6 = morph_mvt
load(here("data", "morphology", "t7.RData"));t7 = morph_mvt
rm(morph_mvt)
```

#### Tidy

```{r}

### --- Tidy t0 - t7 data-sets --- ###

#Column: time
t0$time = NA
t1$time = NA

#Column: replicate_video
t0$replicate_video[t0$file == "sample_00001"] = 1
t0$replicate_video[t0$file == "sample_00002"] = 2
t0$replicate_video[t0$file == "sample_00003"] = 3
t0$replicate_video[t0$file == "sample_00004"] = 4
t0$replicate_video[t0$file == "sample_00005"] = 5
t0$replicate_video[t0$file == "sample_00006"] = 6
t0$replicate_video[t0$file == "sample_00007"] = 7
t0$replicate_video[t0$file == "sample_00008"] = 8
t0$replicate_video[t0$file == "sample_00009"] = 9
t0$replicate_video[t0$file == "sample_00010"] = 10
t0$replicate_video[t0$file == "sample_00011"] = 11
t0$replicate_video[t0$file == "sample_00012"] = 12
t1$replicate_video = 1 #In t1 I took only 1 video/culture
t2$replicate_video = 1 #In t2 I took only 1 video/culture
t3$replicate_video = 1 #In t3 I took only 1 video/culture
t4$replicate_video = 1 #In t4 I took only 1 video/culture
t5$replicate_video = 1 #In t5 I took only 1 video/culture
t6 = t6 %>% rename(replicate_video = replicate)
t7 = t7 %>% rename(replicate_video = replicate)


### --- Create ds dataset --- ###

long_t0 = t0 %>% slice(rep(1:n(), max(culture_info$culture_ID)))
ID_vector = NULL
ID_vector_elongating = NULL
for (ID in 1:max(culture_info$culture_ID)){
  ID_vector = rep(ID, times = nrow(t0))
  ID_vector_elongating = c(ID_vector_elongating, ID_vector)
}
long_t0$culture_ID = ID_vector_elongating
t0 = merge(culture_info,long_t0, by="culture_ID"); rm(long_t0)
t1 = merge(culture_info,t1,by="culture_ID")
t2 = merge(culture_info,t2,by="culture_ID")
t3 = merge(culture_info,t3,by="culture_ID")
t4 = merge(culture_info,t4,by="culture_ID")
t5 = merge(culture_info,t5,by="culture_ID")
t6 = merge(culture_info,t6,by="culture_ID")
t7 = merge(culture_info,t7,by="culture_ID")
ds = rbind(t0, t1, t2, t3, t4, t5, t6, t7); rm(t0, t1, t2, t3, t4, t5, t6, t7)

### --- Tidy ds data-set --- ###

#Column: day
ds$day = ds$time_point;
ds$day[ds$day=="t0"] = "0"
ds$day[ds$day=="t1"] = "4"
ds$day[ds$day=="t2"] = "8"
ds$day[ds$day=="t3"] = "12"
ds$day[ds$day=="t4"] = "16"
ds$day[ds$day=="t5"] = "20"
ds$day[ds$day=="t6"] = "24"
ds$day[ds$day=="t7"] = "28"
ds$day = as.numeric(ds$day)

#Column: time point
ds$time_point[ds$time_point=="t0"] = 0
ds$time_point[ds$time_point=="t1"] = 1
ds$time_point[ds$time_point=="t2"] = 2
ds$time_point[ds$time_point=="t3"] = 3
ds$time_point[ds$time_point=="t4"] = 4
ds$time_point[ds$time_point=="t5"] = 5
ds$time_point[ds$time_point=="t6"] = 6
ds$time_point[ds$time_point=="t7"] = 7
ds$time_point = as.character(ds$time_point)

#Column: eco_metaeco_type
ds$eco_metaeco_type = factor(ds$eco_metaeco_type, 
                             levels=c('S', 'S (S_S)', 'S (S_L)', 'M', 'M (M_M)', 'L', 'L (L_L)', 'L (S_L)'))

#Select useful columns
ds = ds %>% 
  select(culture_ID, 
         patch_size, 
         disturbance, 
         metaecosystem_type, 
         mean_area, 
         replicate_video, 
         day, 
         metaecosystem, 
         system_nr, 
         eco_metaeco_type)

#Reorder columns
ds = ds[, c("culture_ID", 
            "system_nr", 
            "disturbance", 
            "day",
            "patch_size", 
            "metaecosystem", 
            "metaecosystem_type", 
            "eco_metaeco_type", 
            "replicate_video",
            "mean_area")]
```

#### Create size classes data-set

As in @Jacquet2020 I will create 12 size classes.

```{r}

#### --- PARAMETERS & INITIALISATION --- ###

nr_of_size_classes = 12
largest_size = max(ds$mean_area)
size_class_width = largest_size/nr_of_size_classes
size_class = NULL

### --- CREATE DATASET --- ###

size_class_boundaries = seq(0, largest_size, by = size_class_width)

for (class in 1:nr_of_size_classes){
  
  bin_lower_limit = size_class_boundaries[class]
  bin_upper_limit = size_class_boundaries[class+1]
  size_input = (size_class_boundaries[class] + size_class_boundaries[class + 1])/2
  
  size_class[[class]] = ds%>%
    filter(bin_lower_limit <= mean_area) %>%
    filter(mean_area <= bin_upper_limit) %>%
    group_by(culture_ID, 
             system_nr, 
             disturbance, 
             day, 
             patch_size, 
             metaecosystem, 
             metaecosystem_type, 
             eco_metaeco_type, 
             replicate_video) %>% #Group by video
    summarise(mean_abundance_across_videos = n()) %>%
    group_by(culture_ID, 
             system_nr, 
             disturbance, 
             day, 
             patch_size, 
             metaecosystem, 
             metaecosystem_type, 
             eco_metaeco_type) %>% #Group by ID
    summarise(abundance = mean(mean_abundance_across_videos)) %>%
    mutate(log_abundance = log(abundance)) %>%
    mutate(size_class = class) %>%
    mutate(size = size_input) %>%
    mutate(log_size = log(size))
  
}

ds_classes = rbind(size_class[[1]], size_class[[2]], size_class[[3]], size_class[[4]],
                  size_class[[5]], size_class[[6]], size_class[[7]], size_class[[8]],
                  size_class[[9]], size_class[[10]], size_class[[11]], size_class[[12]],)
```

### Plot

#### Comparison of the three small patches

The code for plotting the size class distribution across small patches doesn't work for some reason. It displays all plots as if they were the same.

```{r echo = FALSE, eval = FALSE}
for (time_point in 0:7) {
   
  print(ds_classes %>%
     filter(time_point == time_point) %>%
     filter(disturbance == "low") %>%
     filter(patch_size == "S") %>%
     ggplot(aes(x = log_size,
                y = log_abundance,
                group = interaction(log_size, eco_metaeco_type),
                fill = eco_metaeco_type)) +
     geom_boxplot() +
     labs(title = paste0("Disturbance = Low, Day = ", time_point*4), 
          x = "log body size (µm2)", 
          y = "log mean abundance + 1 (indiv/µl)",
          fill='') +
     scale_y_continuous(limits = c(0,5))+
     scale_x_continuous(limits = c(7,10.5)) +
     scale_fill_discrete(labels = c("small isolated",
                                    "small connected to small",
                                    "small connected to large")) +
     theme_bw() +
     theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))
}

for (time_point in 0:7) {
   
  print(ds_classes %>%
     filter(time_point == time_point) %>%
     filter(disturbance == "high") %>%
     filter(patch_size == "S") %>%
     ggplot(aes(x = log_size,
                y = log_abundance,
                group = interaction(log_size, eco_metaeco_type),
                fill = eco_metaeco_type)) +
     geom_boxplot() +
     labs(title = paste0("Disturbance = High, Day = ", time_point*4), 
          x = "log body size (µm2)", 
          y = "log mean abundance + 1 (indiv/µl)",
          fill='') +
     scale_y_continuous(limits = c(0,5))+
     scale_x_continuous(limits = c(7,10.5)) +
     scale_fill_discrete(labels = c("small isolated",
                                    "small connected to small",
                                    "small connected to large")) +
     theme_bw() +
     theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))
}
```

#### Comparison of different time points

```{r, echo = FALSE, fig.align = "center"}

for (disturbance in c("low", "high")) {

  print(paste("Disturbance =", disturbance))
  
print(ds_classes %>%
  filter(eco_metaeco_type == "S") %>%
  filter(disturbance == disturbance) %>%
  ggplot(aes(x = log_size,
             y = log_abundance,
             group = interaction(log_size, day),
             color = day)) +
  labs(title = "small isolated") +
  geom_point(stat = "summary", fun = "mean") +
  geom_line(stat = "summary", fun = "mean", aes(group = day)) +
  scale_fill_gradient(low="blue", high="yellow") + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))

print(ds_classes %>%
  filter(eco_metaeco_type == "S (S_S)") %>%
  filter(disturbance == disturbance) %>%
  ggplot(aes(x = log_size,
             y = log_abundance,
             group = interaction(log_size, day),
             color = day)) +
  labs(title = "small connected to small") +
  geom_point(stat = "summary", fun = "mean") +
  geom_line(stat = "summary", fun = "mean", aes(group = day)) +
  scale_fill_gradient(low="blue", high="yellow") + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))

print(ds_classes %>%
  filter(eco_metaeco_type == "S (S_L)") %>%
  filter(disturbance == "low") %>%
  ggplot(aes(x = log_size,
             y = log_abundance,
             group = interaction(log_size, day),
             color = day)) +
  labs(title = "small connected to large") +
  geom_point(stat = "summary", fun = "mean") +
  geom_line(stat = "summary", fun = "mean", aes(group = day)) +
  scale_fill_gradient(low="blue", high="yellow") + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))

print(ds_classes %>%
  filter(eco_metaeco_type == "M") %>%
  filter(disturbance == disturbance) %>%
  ggplot(aes(x = log_size,
             y = log_abundance,
             group = interaction(log_size, day),
             color = day)) +
  labs(title = "medium isolated") +
  geom_point(stat = "summary", fun = "mean") +
  geom_line(stat = "summary", fun = "mean", aes(group = day)) +
  scale_fill_gradient(low="blue", high="yellow") + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))

print(ds_classes %>%
  filter(eco_metaeco_type == "M (M_M)") %>%
  filter(disturbance == disturbance) %>%
  ggplot(aes(x = log_size,
             y = log_abundance,
             group = interaction(log_size, day),
             color = day)) +
  labs(title = "medium connected to medium") +
  geom_point(stat = "summary", fun = "mean") +
  geom_line(stat = "summary", fun = "mean", aes(group = day)) +
  scale_fill_gradient(low="blue", high="yellow") + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))

print(ds_classes %>%
  filter(eco_metaeco_type == "L") %>%
  filter(disturbance == disturbance) %>%
  ggplot(aes(x = log_size,
             y = log_abundance,
             group = interaction(log_size, day),
             color = day)) +
  labs(title = "large isolated") +
  geom_point(stat = "summary", fun = "mean") +
  geom_line(stat = "summary", fun = "mean", aes(group = day)) +
  scale_fill_gradient(low="blue", high="yellow") + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))

print(ds_classes %>%
  filter(eco_metaeco_type == "L (L_L)") %>%
  filter(disturbance == disturbance) %>%
  ggplot(aes(x = log_size,
             y = log_abundance,
             group = interaction(log_size, day),
             color = day)) +
  labs(title = "large connected to large") +
  geom_point(stat = "summary", fun = "mean") +
  geom_line(stat = "summary", fun = "mean", aes(group = day)) +
  scale_fill_gradient(low="blue", high="yellow") + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))

print(ds_classes %>%
  filter(eco_metaeco_type == "L (S_L)") %>%
  filter(disturbance == disturbance) %>%
  ggplot(aes(x = log_size,
             y = log_abundance,
             group = interaction(log_size, day),
             color = day)) +
  labs(title = "large connected to small") +
  geom_point(stat = "summary", fun = "mean") +
  geom_line(stat = "summary", fun = "mean", aes(group = day)) +
  scale_fill_gradient(low="blue", high="yellow") + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = c(.95, .95),
          legend.justification = c("right", "top"),
          legend.box.just = "right",
          legend.margin = margin(6, 6, 6, 6)))

}
```

```{r echo = FALSE}
# ################### --- SINGLE SIZE CLASS OVER TIME --- #######################################
# 
# ds_classes %>%
#   filter(size_class == min(ds_classes$size_class)) %>%
#   filter(metaecosystem == "no") %>%
#   ggplot(aes(x = day,
#              y = log_abundance,
#              group = interaction(day,eco_metaeco_type),
#              fill = eco_metaeco_type,
#              color = eco_metaeco_type)) +
#   geom_boxplot()
# 
# ds_classes %>%
#   filter(size_class == min(ds_classes$size_class)) %>%
#   filter(metaecosystem == "no") %>%
#   ggplot(aes(x = day,
#              y = log_abundance,
#              group = interaction(day,eco_metaeco_type),
#              fill = eco_metaeco_type,
#              color = eco_metaeco_type)) +
#   geom_point(stat = "summary", fun = "mean") +
#   geom_line(stat = "summary", fun = "mean", aes(group = eco_metaeco_type)) 
# 
# ds_classes %>%
#   filter(size_class == min(ds_classes$size_class)) %>%
#   filter(patch_size == "S") %>%
#   ggplot(aes(x = day,
#              y = log_abundance,
#              group = interaction(day,eco_metaeco_type),
#              fill = eco_metaeco_type,
#              color = eco_metaeco_type)) +
#   geom_boxplot()
# 
# ds_classes %>%
#   filter(size_class == min(ds_classes$size_class)) %>%
#   filter(patch_size == "S") %>%
#   ggplot(aes(x = day,
#              y = log_abundance,
#              group = interaction(day,eco_metaeco_type),
#              fill = eco_metaeco_type,
#              color = eco_metaeco_type)) +
#   geom_point(stat = "summary", fun = "mean") +
#   geom_line(stat = "summary", fun = "mean", aes(group = eco_metaeco_type)) 
```
