---
title: "small_patches"
author: "Emanuele Giacomuzzo"
date: "2022-10-17"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Small patches {.tabset .tabset-pills}

*Research question: *

#### Plots {.tabset .tabset-pills}

##### Low disturbance

```{r}
patch_size_input = "S"
disturbance_input = "low"

for (species_input in 1:n_protist_species){
  
 print(ds_biomass_abund %>%
  pivot_longer(Ble:Tet, names_to = "species", values_to = "population_abundance") %>%
  filter(disturbance == disturbance_input) %>%
  filter(patch_size == patch_size_input) %>%
  filter(species == protist_species[species_input]) %>%
  ggplot(aes(x = day,
             y = population_abundance,
             group = interaction(day, eco_metaeco_type),
             fill = eco_metaeco_type)) + 
  geom_boxplot() +
  labs(title = paste0(protist_species[species_input], " (Disturbance = ", disturbance_input, ")"),
               x = "Day",
               y = "Population abundance (indiv/μl I think)",
               fill = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_fill_manual(values = c("#A2A2A2", "#008B31", "#DC0000"),
                    labels = c("Small isolated",
                               "Small connected to large",
                               "Small connected to small"))  +
  geom_vline(xintercept = first_perturbation_day,
             linetype = "dotdash",
             color = "grey",
             size = 0.7) +
  labs(caption = "Vertical grey line: first perturbation")) 
  
}
```

##### High disturbance

```{r}
patch_size_input = "S"
disturbance_input = "high"

for (species_input in 1:n_protist_species){
  
 print(ds_biomass_abund %>%
  pivot_longer(Ble:Tet, names_to = "species", values_to = "population_abundance") %>%
  filter(disturbance == disturbance_input) %>%
  filter(patch_size == patch_size_input) %>%
  filter(species == protist_species[species_input]) %>%
  ggplot(aes(x = day,
             y = population_abundance,
             group = interaction(day, eco_metaeco_type),
             fill = eco_metaeco_type)) + 
  geom_boxplot() +
  labs(title = paste0(protist_species[species_input], " (Disturbance = ", disturbance_input, ")"),
               x = "Day",
               y = "Population abundance (indiv/μl I think)",
               fill = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_fill_manual(values = c("#A2A2A2", "#008B31", "#DC0000"),
                    labels = c("Small isolated",
                               "Small connected to large",
                               "Small connected to small"))  +
  geom_vline(xintercept = first_perturbation_day,
             linetype = "dotdash",
             color = "grey",
             size = 0.7) +
  labs(caption = "Vertical grey line: first perturbation")) 
  
}
```