---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

```{r}

# --- PREPARE DATA FOR PLOTTING --- #

# Define what you want to plot

metaecosystem_type_selected = c("Medium-Medium",
                                "Small-Large")

# Filter dataset

data_for_plotting = ds_metaecosystems %>%
  filter(metaecosystem_type %in% metaecosystem_type_selected,
         disturbance == disturbance_selected)
```


```{r}

# Write function to plot a response variable. Afterwards you can use this function to plot alpha, beta, gamma diversity, and biomass.

plot.single.plot = function(response_variable_selected){
  
  data_for_plotting %>%
    filter(metaecosystem_type %in% metaecosystem_type_selected,
           !is.na(!!sym(response_variable_selected))) %>%
    summarySE(measurevar = response_variable_selected,
              groupvars = c("day", "ecosystem_size_symmetry", "connection")) %>%
    ggplot(aes(x = day,
               y = get(response_variable_selected),
               group = interaction(day, ecosystem_size_symmetry, connection),
               color = ecosystem_size_symmetry,
               linetype = connection)) +
    geom_point(stat = "summary",
               fun = "mean",
               position = position_dodge(dodging),
               size = treatment_points_size) +
    geom_line(stat = "summary",
              fun = "mean",
              aes(group = interaction(ecosystem_size_symmetry, connection)),
              position = position_dodge(dodging),
              linewidth = treatment_lines_linewidth) +
    geom_errorbar(aes(ymax = get(response_variable_selected) + ci,
                      ymin = get(response_variable_selected) - ci),
                  width = width_errorbar,
                  position = position_dodge(dodging)) +
    labs(x = axis_names$axis_name[axis_names$variable == "day"],
         y = axis_names$axis_name[axis_names$variable == response_variable_selected],
         color = "") +
    scale_color_manual(values = treatment_colours_paper) +
    scale_linetype_manual(values = treatment_linetype_paper) +
    geom_vline(xintercept = resource_flow_days,
               linetype = resource_flow_line_type,
               color = resource_flow_line_colour,
               linewidth = resource_flow_line_width) +
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          legend.position = legend_position,
          legend.key.width = unit(legend_width_cm, "cm")) +
    guides(color = guide_legend(title = NULL,
                                nrow = 2),
           linetype = guide_legend(title = NULL,
                                   nrow = 2)) +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left),
                             "cm")) +
    geom_rect(xmin = grey_background_xmin, 
              xmax = grey_background_xmax,
              ymin = grey_background_ymin, 
              ymax = grey_background_ymax, 
              fill = grey_background_fill, 
              alpha = grey_background_alpha,
              color = grey_background_color)
}
```

```{r fig.height = figures_height_rmd_output}

# Combine plots of alpha, beta, gamma biodiversity and biomass.

p_combined = ggarrange(plot.single.plot("mean_shannon") +
                         rremove("xlab") +
                         theme(axis.text.x = element_blank(),
                               axis.ticks.x = element_blank()) +
                         font("legend.text", size = paper_labels_size) +
                         font("ylab", size = paper_labels_size),
                       plot.single.plot("bray_curtis") +
                         rremove("xlab") +
                         theme(axis.text.x = element_blank(),
                               axis.ticks.x = element_blank()) +
                         font("legend.text", 
                              size = paper_labels_size) +
                         font("ylab", 
                              size = paper_labels_size),
                       plot.single.plot("metaecosystem_richness") +
                         rremove("xlab") +
                         theme(axis.text.x = element_blank(),
                               axis.ticks.x = element_blank()) +
                         font("legend.text", 
                              size = paper_labels_size) +
                         font("ylab", 
                              size = paper_labels_size),
                       plot.single.plot("total_metaecosystem_bioarea_mm2") +
                         font("legend.text", 
                              size = paper_labels_size) +
                         font("xlab", 
                              size = paper_labels_size) +
                         font("ylab", 
                              size = paper_labels_size) +
                         scale_x_continuous(breaks = unique(data_for_plotting$day)),
                       heights = c(0.8, 0.8, 0.8, 1),
                       nrow = 4,
                       common.legend = TRUE,
                       align = "v",
                       labels = c("(a)", "(b)", "(c)", "(d)"),
                       label.x = 0.1,
                       label.y = 0.8) %>%
  print()
```

```{r echo = FALSE, results=FALSE}

# Save combined plots

png(file = here("3_results", 
                "figures", 
                disturbance_selected, 
                "paper", 
                "metaecosystem_diversity_n_function.png"),
    width = paper_width,
    height = paper_height,
    units = paper_units,
    res = paper_res)

p_combined

dev.off()
```