---
title: "Biomass analysis (PatchSizePilot)"
author: "Emanuele Giacomuzzo"
date: '2022-07-07'
output: html_document
editor_options: 
  chunk_output_type: console
---

## Regional Biomass {.tabset .tabset-dropdown}

```{r child = here("r_files", "biomass_regional", "sections", "metaeco_all.Rmd")}
source(here("r_files", "biomass_regional", "extracted_sections", "metaeco_all.R"))
```

```{r child = here("r_files", "biomass_regional", "sections", "MM_SL_plots.Rmd")}
source(here("r_files", "biomass_regional", "extracted_sections", "MM_SL_plots.R"))
```

```{r child = here("r_files", "biomass_regional", "sections", "MM_SL_time_series.Rmd")}
source(here("r_files", "biomass_regional", "extracted_sections", "MM_SL_time_series.R"))
```

```{r MM_SL_time_fitted, child = here("r_files", "biomass_regional", "sections", "MM_SL_single_points.Rmd"), echo = TRUE, eval = TRUE}
source(here("r_files", "biomass_regional", "extracted_sections", "MM_SL_single_points.R"))
```

```{r child = here("r_files", "biomass_regional", "sections", "SL_SL_from_isolated.Rmd"), eval = FALSE}
source(here("r_files", "biomass_regional", "extracted_sections", "SL_SL_from_isolated.R"))
```

```{r child = here("r_files", "biomass_regional", "sections", "metaeco_equally_sized_patches.Rmd")}
source(here("r_files", "biomass_regional", "extracted_sections", "metaeco_equally_sized_patches.R"))
```