---
title: "large_patches"
author: "Emanuele Giacomuzzo"
date: "2022-08-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

##### plots

```{r}

### --- SINGLE PATCHES --- ###

ds_biomass %>%
  filter(disturbance == "low") %>%
  filter(patch_size == "L") %>%
  ggplot(aes(x = day,
             y = bioarea_per_volume,
             group = system_nr,
             fill = system_nr,
             color = system_nr,
             linetype = eco_metaeco_type)) +
  geom_line(stat = "summary", fun = "mean") + 
  labs(x = "Day",
       y = "Local bioarea (something/μl)",
       title = "Disturbance = low",
       linetype = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_linetype_discrete(labels = c("large isolated",
                                     "large connected to large",
                                     "large connected to small")) +
  geom_vline(xintercept = first_perturbation_day, 
             linetype="dotdash", 
             color = "grey", 
             size=0.7) +
  labs(caption = "Vertical grey line: first perturbation")

ds_biomass %>%
  filter(disturbance == "high") %>%
  filter(patch_size == "L") %>%
  ggplot(aes(x = day,
             y = bioarea_per_volume,
             group = system_nr,
             fill = system_nr,
             color = system_nr,
             linetype = eco_metaeco_type)) +
  geom_line(stat = "summary", fun = "mean") + 
  labs(x = "Day",
       y = "Local bioarea (something/μl)",
       title = "Disturbance = high",
       linetype = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_linetype_discrete(labels = c("large isolated",
                                     "large connected to large",
                                     "large connected to small")) +
  geom_vline(xintercept = first_perturbation_day, 
             linetype="dotdash", 
             color = "grey", 
             size=0.7) +
  labs(caption = "Vertical grey line: first perturbation")

### --- BOXPLOTS --- ###

ds_biomass %>%
  filter(disturbance == "low") %>%
  filter(patch_size == "L") %>%
  ggplot(aes(x = day,
             y = bioarea_per_volume,
             group = interaction(day,eco_metaeco_type),
             fill = eco_metaeco_type)) +
  geom_boxplot() +
  labs(x = "Day",
       y = "Local bioarea (something/μl)",
       title = "Disturbance = low",
       fill = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_fill_discrete(labels = c("large isolated", 
                                 "large connected to large",
                                 "large connected to small")) +
  geom_vline(xintercept = first_perturbation_day, 
             linetype="dotdash", 
             color = "grey", 
             size=0.7) +
  labs(caption = "Vertical grey line: first perturbation")

local_large_high_plot = ds_biomass %>%
  filter(disturbance == "high") %>%
  filter(patch_size == "L") %>%
  ggplot(aes(x = day,
             y = bioarea_per_volume,
             group = interaction(day,eco_metaeco_type),
             fill = eco_metaeco_type)) +
  geom_boxplot() +
  labs(x = "Day",
       y = "Local bioarea (something/μl)",
       title = "Disturbance = high",
       fill = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_fill_discrete(labels = c("large isolated", 
                                 "large connected to large",
                                 "large connected to small")) +
  geom_vline(xintercept = first_perturbation_day + 0.7, 
             linetype="dotdash", 
             color = "grey", 
             size=0.7) +
  labs(caption = "Vertical grey line: first perturbation")
local_large_high_plot
```

##### isolated vs connected to large

*Does M have an effect?*

```{r}
full_model = lmer(bioarea_per_volume ~
                    metaecosystem_type * disturbance  +
                    (1 | system_nr) +
                    (1 | day),
                  data = ds_biomass %>%
                    filter (eco_metaeco_type == "L" |
                            eco_metaeco_type == "L (L_L)") %>%
                    filter(time_point >= 2),
                  REML = FALSE)

no_metaeco_type_model = lmer(bioarea_per_volume ~
                               disturbance +
                               (1 | system_nr) +
                               (1 | day),
                             data = ds_biomass %>%
                               filter (eco_metaeco_type == "L" |
                                       eco_metaeco_type == "L (L_L)") %>%
                               filter(time_point >= 2),
                             REML = FALSE)

anova(full_model, no_metaeco_type_model)
```

Yes.

##### isolated vs connected to small

*Does M have an effect?*

```{r}
full_model = lmer(bioarea_per_volume ~
                    metaecosystem_type * disturbance  +
                    (1 | system_nr) +
                    (1 | day),
                  data = ds_biomass %>%
                    filter (eco_metaeco_type == "L" |
                            eco_metaeco_type == "L (S_L)") %>%
                    filter(time_point >= 2),
                  REML = FALSE)

no_metaeco_type_model = lmer(bioarea_per_volume ~
                               disturbance +
                               (1 | system_nr) +
                               (1 | day),
                             data = ds_biomass %>%
                               filter (eco_metaeco_type == "L" |
                                       eco_metaeco_type == "L (S_L)") %>%
                               filter(time_point >= 2),
                             REML = FALSE)

anova(full_model, no_metaeco_type_model)
```

Yes.

##### connected to large vs connected to small

*Does M have an effect?*

```{r}
full_model = lmer(bioarea_per_volume ~
                    metaecosystem_type * disturbance  +
                    (1 | system_nr) +
                    (1 | day),
                  data = ds_biomass %>%
                    filter (eco_metaeco_type == "L (L_L)" |
                            eco_metaeco_type == "L (S_L)") %>%
                    filter(time_point >= 2),
                  REML = FALSE)

no_metaeco_type_model = lmer(bioarea_per_volume ~
                               disturbance +
                               (1 | system_nr) +
                               (1 | day),
                             data = ds_biomass %>%
                               filter (eco_metaeco_type == "L (L_L)" |
                                       eco_metaeco_type == "L (S_L)") %>%
                               filter(time_point >= 2),
                             REML = FALSE)

anova(full_model, no_metaeco_type_model)
```

Yes.
