---
title: "patches_all"
author: "Emanuele Giacomuzzo"
date: "2022-08-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
ds_biomass %>%
  group_by(culture_ID, disturbance, day, eco_metaeco_type) %>%
  summarise(bioarea_per_volume = mean(bioarea_per_volume)) %>% #Average across videos
  filter(disturbance == "low") %>%
  ggplot(aes(x = day,
             y = bioarea_per_volume,
             group = interaction(day, eco_metaeco_type),
             fill = eco_metaeco_type)) +
  geom_boxplot() +
  labs(title = "Disturbance = low",
       x = "Day",
       y = "Local bioarea (µm²/µl)",
       fill = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_fill_discrete(labels = c("large isolated",
                                 "large connected to large",
                                 "large connected to small",
                                 "medium isolated",
                                 "medium connected to medium",
                                 "small isolated",
                                 "small connected to large",
                                 "small connected to small")) +
  geom_vline(xintercept = first_perturbation_day + 0.6,
             linetype="dotdash",
             color = "grey",
             size=0.7) +
  labs(caption = "Vertical grey line: first perturbation")

ds_biomass %>%
  group_by(culture_ID, disturbance, day, eco_metaeco_type) %>%
  summarise(bioarea_per_volume = mean(bioarea_per_volume)) %>% #Average across videos
  filter(disturbance == "high") %>%
  ggplot(aes(x = day,
             y = bioarea_per_volume,
             group = interaction(day, eco_metaeco_type),
             fill = eco_metaeco_type)) +
  geom_boxplot() +
  labs(title = "Disturbance = high",
       x = "Day",
       y = "Local bioarea (µm²/µl)",
       fill = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_fill_discrete(labels = c("large isolated",
                                 "large connected to large",
                                 "large connected to small",
                                 "medium isolated",
                                 "medium connected to medium",
                                 "small isolated",
                                 "small connected to large",
                                 "small connected to small")) +
  geom_vline(xintercept = first_perturbation_day + 0.6,
             linetype="dotdash",
             color = "grey",
             size=0.7) +
  labs(caption = "Vertical grey line: first perturbation")
```

The following one is with the total biomass of the patches. It's useful to check if everything is fine with our analysis.
s
```{r}
ds_biomass_total = ds_biomass %>%
  filter(!culture_ID %in% ecosystems_to_take_off) %>%
  group_by(culture_ID, 
           system_nr, 
           disturbance, 
           time_point,
           day, 
           patch_size,
           patch_size_volume,
           eco_metaeco_type) %>%
  summarise(bioarea_per_volume_video_averaged = mean(bioarea_per_volume)) %>%
  mutate(total_patch_bioarea = bioarea_per_volume_video_averaged * patch_size_volume)

ds_biomass_total %>%
  filter(disturbance == "low") %>%
  ggplot(aes(x = day,
             y = total_patch_bioarea,
             group = interaction(day, eco_metaeco_type),
             fill = eco_metaeco_type)) +
  geom_boxplot() +
  labs(title = "Disturbance = low",
       x = "Day",
       y = "Total patch bioarea (µm²)",
       fill = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_fill_discrete(labels = c("large isolated",
                                 "large connected to large",
                                 "large connected to small",
                                 "medium isolated",
                                 "medium connected to medium",
                                 "small isolated",
                                 "small connected to large",
                                 "small connected to small")) +
  geom_vline(xintercept = first_perturbation_day + 0.6,
             linetype="dotdash",
             color = "grey",
             size=0.7) +
  labs(caption = "Vertical grey line: first perturbation")

ds_biomass_total %>%
  filter(disturbance == "high") %>%
  ggplot(aes(x = day,
             y = total_patch_bioarea,
             group = interaction(day, eco_metaeco_type),
             fill = eco_metaeco_type)) +
  geom_boxplot() +
  labs(title = "Disturbance = high",
       x = "Day",
       y = "Total patch bioarea (µm²)",
       fill = "") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)) +
  scale_fill_discrete(labels = c("large isolated",
                                 "large connected to large",
                                 "large connected to small",
                                 "medium isolated",
                                 "medium connected to medium",
                                 "small isolated",
                                 "small connected to large",
                                 "small connected to small")) +
  geom_vline(xintercept = first_perturbation_day + 0.6,
             linetype="dotdash",
             color = "grey",
             size=0.7) +
  labs(caption = "Vertical grey line: first perturbation")
```

