---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

### Filter according to disturbance

Here I'm filtering ecosystems to have only the ones with disturbance `r disturbance_global_selected`.

```{r}
ds_ecosystems_both_disturbances = ds_ecosystems
ds_metaecosystems_both_disturbances = ds_metaecosystems
```

```{r}
#Filter data sets according to the global disturbance
ds_individuals = ds_individuals %>%
  filter(disturbance == disturbance_global_selected)
ds_ecosystems = ds_ecosystems %>%
  filter(disturbance == disturbance_global_selected)
ds_ecosystems_effect_size = ds_ecosystems_effect_size %>%
  filter(disturbance == disturbance_global_selected)
ds_metaecosystems = ds_metaecosystems %>%
  filter(disturbance == disturbance_global_selected)
```

```{r eval = FALSE}
ds_classes = ds_classes %>%
  filter(disturbance == disturbance_global_selected)
ds_classes_effect_size = ds_classes_effect_size %>%
  filter(disturbance == disturbance_global_selected)
```

