---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

```{r}

# Plots parameters

response_variable_selected = "shannon"
legend_row_n_input = 2
size_y_axis = 22

x_min = -0.2
x_max = 30
y_min = -0.8
y_max = 3


ecosystem_type_all = c("Small connected to large",
                       "Small unconnected",
                       "Small connected to small",
                       "Large connected to small",
                       "Large unconnected",
                       "Large connected to large")
```

```{r}

# Construct plots

plots = NULL

plots[[1]] = plot.ecosystems.empty.presentations(y_min_alpha,
                                              y_max_alpha,
                                              "shannon")

for (i in 1:length(ecosystem_type_all)+1) {
  
  plots[[i+1]] = plot.ecosystems.points.presentations(data = ds_ecosystems,
                                                      ecosystem_type_selected = ecosystem_type_all[1:i],
                                                      response_variable_selected) +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left),
                             "cm"),
          legend.position = "none") +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01)) + 
    xlim(x_min, x_max) +
    ylim(y_min, y_max)
  
  }
```

```{r}

# Combine plots

p_combined = NULL
p_combined[[1]] = plots[[1]]

for(i in 1:length(ecosystem_type_all)+1){
  
  p_combined[[i]] = ggarrange(
  plots[[i]] +
    theme(axis.text = element_text(size = presentation_axes_size)) + 
    font("legend.text", size = size_legend) +
    font("xlab", size = size_y_axis) +
    font("ylab", size = size_y_axis),
  nrow = 1,
  align = "v",
  label.x = 0.1,
  label.y = 0.8)

  }
```

```{r results=FALSE}

# Save combined plots

for(i in 1:length(ecosystem_type_all)+1){
  
  png(file = here("6_results", 
                  "figures", 
                  disturbance_global_selected, 
                  "presentations", 
                  paste0("ecosystems_connected_diversity_", i, ".png")),
      width = presentation_figure_width,
      height = presentation_figure_height,
      units = presentation_figure_units,
      res = presentation_figure_res)
  
  print(p_combined[[i]])
  
  dev.off()
  
  }
```