---
title: "Data manipulation: PatchSizePilot"
author: "Emanuele Giacomuzzo"
date: "2022-08-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Patches (`ds_ecosystems`)

In this dataset (`ds_ecosystems`) each row represents a ecosystem at a time point. I use the data from the 40 threshold analysis for Ble, Cep, Spi and the data from the 13 threshold analysis for all the other protists (Col, Eup, Lox, Pau, Pca, Spi te, Tet).

```{r}

# Import & bind t0 datasets.

ds_ecosystems_t0 = read.csv(here("2_data", 
                              "ecosystems_13_threshold", 
                              "t0.csv")) %>%
  mutate(time_point =  as.numeric(str_extract(time_point, "\\d+")),
         day = 0,
         video_replicate = file) %>%
  select(time_point,
         day,
         video_replicate,
         file,
         bioarea_per_volume,
         indiv_per_volume)

species_ID_13_threshold_t0 = read.csv(here("2_data", 
                                           "species_ID_13_threshold", 
                                           paste0("t0.csv"))) %>%
  rename(Ble_indiv_per_volume = Ble,
         Cep_indiv_per_volume = Cep,
         Col_indiv_per_volume = Col,
         Eug_indiv_per_volume = Eug,
         Eup_indiv_per_volume = Eup,
         Lox_indiv_per_volume = Lox,
         Pau_indiv_per_volume = Pau,
         Pca_indiv_per_volume = Pca,
         Spi_indiv_per_volume = Spi,
         Spi_te_indiv_per_volume = Spi_te,
         Tet_indiv_per_volume = Tet) %>%
  select(file,
         all_of(species_IDD_with_13_threshold_indiv_per_volume))

species_ID_40_threshold_t0 = read.csv(here("2_data", 
                                           "species_ID_40_threshold", 
                                           paste0("t0.csv"))) %>%
  rename(Ble_indiv_per_volume = Ble,
         Cep_indiv_per_volume = Cep,
         Col_indiv_per_volume = Col,
         Eug_indiv_per_volume = Eug,
         Eup_indiv_per_volume = Eup,
         Lox_indiv_per_volume = Lox,
         Pau_indiv_per_volume = Pau,
         Pca_indiv_per_volume = Pca,
         Spi_indiv_per_volume = Spi,
         Spi_te_indiv_per_volume = Spi_te,
         Tet_indiv_per_volume = Tet) %>%
  select(file,
         all_of(species_IDD_with_40_threshold_indiv_per_volume))

ds_ecosystems_t0 = ds_ecosystems_t0 %>%
  left_join(species_ID_13_threshold_t0,
            by = "file") %>%
  left_join(species_ID_40_threshold_t0,
            by = "file") %>%
  mutate(file =  as.numeric(str_extract(file, "\\d+")))
```

```{r}

# Elongate t0 dataset.

ds_ecosystems_t0_elongated <- list()

for (video_i in 1 : n_videos_taken_t0) {
  
  single_video = ds_ecosystems_t0 %>%
    filter(file == video_i)
  
  ds_ecosystems_t0_elongated[[video_i]] = culture_info %>%
    mutate(
      time_point = 0,
      day = 0,
      file = single_video$file,
      video_replicate = single_video$video_replicate,
      bioarea_per_volume = single_video$bioarea_per_volume,
      indiv_per_volume = single_video$indiv_per_volume,
      Ble_indiv_per_volume = single_video$Ble_indiv_per_volume,
      Cep_indiv_per_volume = single_video$Cep_indiv_per_volume,
      Col_indiv_per_volume = single_video$Col_indiv_per_volume,
      Eug_indiv_per_volume = single_video$Eug_indiv_per_volume,
      Eup_indiv_per_volume = single_video$Eup_indiv_per_volume,
      Lox_indiv_per_volume = single_video$Lox_indiv_per_volume,
      Pau_indiv_per_volume = single_video$Pau_indiv_per_volume,
      Pca_indiv_per_volume = single_video$Pca_indiv_per_volume,
      Spi_indiv_per_volume = single_video$Spi_indiv_per_volume,
      Spi_te_indiv_per_volume = single_video$Spi_te_indiv_per_volume,
      Tet_indiv_per_volume = single_video$Tet_indiv_per_volume)
}

ds_ecosystems_t0_elongated = ds_ecosystems_t0_elongated %>%
  bind_rows()
```

```{r}

# Clean the columns of t0

ds_ecosystems_t0 = ds_ecosystems_t0_elongated %>%
  select(
    file,
    time_point,
    day,
    culture_ID,
    video_replicate,
    bioarea_per_volume,
    indiv_per_volume,
    all_of(protist_species_indiv_per_volume))

expect_equal(nrow(ds_ecosystems_t0), sum(n_videos_taken_t0 * n_cultures))
```

```{r}

# Import and bind t1-t4

ds_ecosystems_t1_to_t4 = NULL

for (time_point_i in time_points_without_t0) {
  
  species_ID_13_threshold = read.csv(here("2_data", 
                                          "species_ID_13_threshold", 
                                          paste0("t", time_point_i, ".csv"))) %>%
    rename(Ble_indiv_per_volume = Ble,
         Cep_indiv_per_volume = Cep,
         Col_indiv_per_volume = Col,
         Eug_indiv_per_volume = Eug,
         Eup_indiv_per_volume = Eup,
         Lox_indiv_per_volume = Lox,
         Pau_indiv_per_volume = Pau,
         Pca_indiv_per_volume = Pca,
         Spi_indiv_per_volume = Spi,
         Spi_te_indiv_per_volume = Spi_te,
         Tet_indiv_per_volume = Tet) %>%
    select(file,
           all_of(species_IDD_with_13_threshold_indiv_per_volume))
  
  
  species_ID_40_threshold = read.csv(here("2_data", 
                                          "species_ID_40_threshold", 
                                          paste0("t", time_point_i, ".csv"))) %>%
    rename(Ble_indiv_per_volume = Ble,
         Cep_indiv_per_volume = Cep,
         Col_indiv_per_volume = Col,
         Eug_indiv_per_volume = Eug,
         Eup_indiv_per_volume = Eup,
         Lox_indiv_per_volume = Lox,
         Pau_indiv_per_volume = Pau,
         Pca_indiv_per_volume = Pca,
         Spi_indiv_per_volume = Spi,
         Spi_te_indiv_per_volume = Spi_te,
         Tet_indiv_per_volume = Tet) %>%
    select(file,
           all_of(species_IDD_with_40_threshold_indiv_per_volume))
  
  
  ds_ecosystems_t1_to_t4[[time_point_i]] = read.csv(here("2_data", 
                                                      "ecosystems_13_threshold", 
                                                      paste0("t", time_point_i, ".csv"))) %>%
    arrange(file) %>%
    mutate(video_replicate = rep(1 : time_point_day$video_replicates[time_point_i+1],
                                 each = n_cultures),
           day = time_point_day$day[time_point_day$time_point == time_point_i]) %>%
    select(
      file,
      time_point,
      day,
      video_replicate,
      file,
      culture_ID,
      bioarea_per_volume,
      indiv_per_volume)
  
  ds_ecosystems_t1_to_t4[[time_point_i]] = ds_ecosystems_t1_to_t4[[time_point_i]] %>%
    left_join(species_ID_13_threshold,
                by = "file") %>%
    left_join(species_ID_40_threshold,
                by = "file")
    
}

ds_ecosystems_t1_to_t4 = ds_ecosystems_t1_to_t4 %>%
  bind_rows()
```

```{r}

# Bind t0 with t1-t4

ds_ecosystems = rbind(ds_ecosystems_t0,
                   ds_ecosystems_t1_to_t4) %>%
             left_join(culture_info,
                       by = "culture_ID") 
    
expect_equal(nrow(ds_ecosystems),
             sum(sum(time_point_day$video_replicates) * n_cultures))
```

```{r}

# Reorder and rename columns

ds_ecosystems = ds_ecosystems %>%
  rename(ecosystem_size = patch_size,
         ecosystem_size_ml = patch_size_volume) %>%
  select(
    file,
    time_point,
    day,
    disturbance,
    culture_ID,
    system_nr,
    eco_metaeco_type,
    ecosystem_size,
    ecosystem_size_ml,
    metaecosystem,
    metaecosystem_type,
    video_replicate,
    bioarea_per_volume,
    indiv_per_volume,
    all_of(protist_species_indiv_per_volume)
  ) %>%
  rename(ecosystem_type = eco_metaeco_type,
         bioarea_µm2_per_μL = bioarea_per_volume) %>%
  rename_all( ~ gsub("volume", "μL", .))
```

```{r}

# Rename and reorder levels

ds_ecosystems <- ds_ecosystems %>%
  mutate(
    ecosystem_type = case_when(
      ecosystem_type == "S" ~ "Small unconnected",
      ecosystem_type == "M" ~ "Medium unconnected",
      ecosystem_type == "L" ~ "Large unconnected",
      ecosystem_type == "S (S_S)" ~ "Small connected to small",
      ecosystem_type == "S (S_L)" ~ "Small connected to large",
      ecosystem_type == "M (M_M)" ~ "Medium connected to medium",
      ecosystem_type == "L (S_L)" ~ "Large connected to small",
      ecosystem_type == "L (L_L)" ~ "Large connected to large",
      TRUE ~ ecosystem_type
    ),
    ecosystem_type = factor(x = ecosystem_type,
                        levels = ecosystem_types_ordered),
    ecosystem_size = case_when(
      ecosystem_size == "S" ~ "Small",
      ecosystem_size == "M" ~ "Medium",
      ecosystem_size == "L" ~ "Large",
      TRUE ~ ecosystem_size
    ),
    metaecosystem_type = case_when(
      metaecosystem_type == "S_S" ~ "Small-Small meta-ecosystem",
      metaecosystem_type == "M_M" ~ "Medium-Medium meta-ecosystem",
      metaecosystem_type == "L_L" ~ "Large-Large meta-ecosystem",
      metaecosystem_type == "S_L" ~ "Small-Large meta-ecosystem",
      TRUE ~ metaecosystem_type
    ),
    size_connected_ecosystem = case_when(
      ecosystem_type == "Small connected to small" ~ "Small",
      ecosystem_type == "Small connected to large" ~ "Large",
      ecosystem_type == "Medium connected to medium" ~ "Medium",
      ecosystem_type == "Large connected to large" ~ "Large",
      ecosystem_type == "Large connected to small" ~ "Small",
      TRUE ~ NA_character_
      ),
    time_point =  as.numeric(str_extract(time_point, "\\d+")),
    file =  as.numeric(str_extract(file, "\\d+")),
  )
```

```{r}

# Change units of measurments to ml

ds_ecosystems = ds_ecosystems %>%
  mutate(bioarea_µm2_per_ml = bioarea_µm2_per_μL * 10^3,
         bioarea_mm2_per_ml = bioarea_µm2_per_ml * 10^(-6),
         Ble_indiv_per_ml = Ble_indiv_per_μL * 10^3,
         Cep_indiv_per_ml = Cep_indiv_per_μL * 10^3,
         Col_indiv_per_ml = Col_indiv_per_μL * 10^3,
         Eug_indiv_per_ml = Eug_indiv_per_μL * 10^3,
         Eup_indiv_per_ml = Eup_indiv_per_μL * 10^3,
         Lox_indiv_per_ml = Lox_indiv_per_μL * 10^3,
         Pau_indiv_per_ml = Pau_indiv_per_μL * 10^3,
         Pca_indiv_per_ml = Pca_indiv_per_μL * 10^3,
         Spi_indiv_per_ml = Spi_indiv_per_μL * 10^3,
         Spi_te_indiv_per_ml = Spi_te_indiv_per_μL * 10^3,
         Tet_indiv_per_ml = Tet_indiv_per_μL * 10^3)
```

```{r}

# Take off problematic videos

ds_ecosystems_before_taking_off_videos = ds_ecosystems

ds_ecosystems = ds_ecosystems %>%
  filter(!(time_point %in% videos_to_take_off$time_point & file %in% videos_to_take_off$file))

diff = setdiff(ds_ecosystems_before_taking_off_videos, ds_ecosystems)

expect_equal(nrow(videos_to_take_off),
             nrow(expand.grid(diff$culture_ID, diff$time_point, diff$file) %>% unique()))
```

```{r}

# Take off problematic cultures 

ds_ecosystems_before_taking_off_cultures = ds_ecosystems

ds_ecosystems = ds_ecosystems %>%
  filter(!culture_ID %in% ecosystems_to_take_off)

expect_equal(setdiff(ds_ecosystems_before_taking_off_cultures, 
                     ds_ecosystems) %>% 
               pull(culture_ID) %>% 
               unique(),
             ecosystems_to_take_off)
```


```{r}

# Average videos

ds_ecosystems = ds_ecosystems %>%
  group_by(across(all_of(columns_ecosystems))) %>%
  summarise(across(contains("_per_ml"), mean),
            across(contains("_tot"), mean)) %>%
  ungroup()

expect_equal(nrow(ds_ecosystems), 
             (n_cultures - length(ecosystems_to_take_off)) * length(time_points))
```

```{r}

# Add connection and individuals

ds_ecosystems = ds_ecosystems %>%
  mutate(indiv_per_ml = !!rlang::parse_expr(paste(protist_species_indiv_per_ml, 
                                                  collapse = " + ")))

ds_ecosystems = ds_ecosystems %>%
  mutate(connection = ifelse(str_detect(ecosystem_type, "unconnected"), 
                             "unconnected", 
                             "connected"),
         connection = factor(x = connection,
                        levels = c("unconnected", "connected")))
```

```{r}

# Calculate total response variable for the whole ecosystem

ds_ecosystems = ds_ecosystems %>%
  mutate(bioarea_tot_mm2 = bioarea_mm2_per_ml * ecosystem_size_ml,
         indiv_tot = indiv_per_ml * ecosystem_size_ml,
         Ble_tot_indiv = Ble_indiv_per_ml * ecosystem_size_ml,
         Cep_tot_indiv = Cep_indiv_per_ml * ecosystem_size_ml,
         Col_tot_indiv = Col_indiv_per_ml * ecosystem_size_ml,
         Eug_tot_indiv = Eug_indiv_per_ml * ecosystem_size_ml,
         Eup_tot_indiv = Eup_indiv_per_ml * ecosystem_size_ml,
         Lox_tot_indiv = Lox_indiv_per_ml * ecosystem_size_ml,
         Pau_tot_indiv = Pau_indiv_per_ml * ecosystem_size_ml,
         Pca_tot_indiv = Pca_indiv_per_ml * ecosystem_size_ml,
         Spi_tot_indiv = Spi_indiv_per_ml * ecosystem_size_ml,
         Spi_te_tot_indiv = Spi_te_indiv_per_ml * ecosystem_size_ml,
         Tet_tot_indiv = Tet_indiv_per_ml * ecosystem_size_ml)
```

```{r}

# Calculate species dominance

ds_ecosystems = ds_ecosystems %>%
  mutate(across(.cols = all_of(protist_species_indiv_per_ml), 
                .fns = list(dominance = ~ (. / indiv_per_ml) * 100), 
                .names = "{col}_dominance"))

expect_equal(unique(ds_ecosystems$Ble_indiv_per_ml_dominance[ds_ecosystems$indiv_per_ml == 0]), NaN)

if (FALSE %in% unique((ds_ecosystems$Ble_indiv_per_ml/ds_ecosystems$indiv_per_ml) *100 == ds_ecosystems$Ble_indiv_per_ml_dominance)) stop()
```

```{r}

# Calculate alpha diversity (Shannon, Simpson, Inverse Simpson, Evenness)

n_rows_ds_ecosystems_before_calculating_alpha = nrow(ds_ecosystems)

ds_ecosystems = calculate.alpha.diversity()

expect_equal(max(ds_ecosystems$species_richness), 
             length(protist_species))

expect_equal(nrow(ds_ecosystems),
             n_rows_ds_ecosystems_before_calculating_alpha)
```

```{r}

# Calculate median body size

n_rows_ds_ecosystems_before_median_size = nrow(ds_ecosystems)

ds_median_body_size = ds_individuals %>%
  group_by(time_point,
           culture_ID,
           file) %>%
  summarise(median_body_area_µm2 = median(body_area_µm2)) %>%
  group_by(time_point,
           culture_ID) %>%
  summarise(median_body_area_µm2 = mean(median_body_area_µm2))

expect_true(nrow(ds_median_body_size) <= nrow(ds_ecosystems)) #Ds median body size could be less because some cultures might be crashed and not have any individual.

ds_ecosystems_before_full_join = ds_ecosystems

ds_ecosystems = full_join(ds_ecosystems, ds_median_body_size)

expect_equal(nrow(ds_ecosystems), 
             n_rows_ds_ecosystems_before_median_size)
```

```{r}

# Calculate auto/heterotrophic ratio

ds_ecosystems = ds_ecosystems %>%
  mutate(auto_hetero_ratio = (Eug_indiv_per_ml + Eup_indiv_per_ml) / 
                             (Ble_indiv_per_ml + 
                              Cep_indiv_per_ml + 
                              Col_indiv_per_ml + 
                              Lox_indiv_per_ml + 
                              Pau_indiv_per_ml + 
                              Pca_indiv_per_ml +
                              Spi_indiv_per_ml + 
                              Spi_te_indiv_per_ml +
                              Tet_indiv_per_ml))
```