---
title: "Untitled"
output: html_document
date: "2024-06-27"
editor_options: 
  chunk_output_type: console
---

```{r}

# Modify dataset

ds_ecosystems_filtered = ds_ecosystems %>% 
  filter(!is.na(water_addition_ml))
```

```{r}

# Plot mean +- 95 % confidence intervals of evaporation rates

p = NULL
for(time_point_i in 1:length(time_points_with_water_addtion)){
  
  p[[time_point_i]] = ds_ecosystems_filtered %>%
    filter(time_point == time_points_with_water_addtion[time_point_i]) %>%
    mutate(ecosystem_type = forcats::fct_recode(ecosystem_type, 
                                                S = "Small unconnected",
                                                M = "Medium unconnected",
                                                L = "Large unconnected",
                                                S_S = "Small connected to small",
                                                S_L = "Small connected to large",
                                                M_M = "Medium connected to medium",
                                                L_S = "Large connected to small",
                                                L_L = "Large connected to large")) %>%
    summarySE(measurevar = "water_addition_ml",
              groupvars = c("time_point", "ecosystem_type")) %>%
    ggplot(aes(x = ecosystem_type,
               y = water_addition_ml)) +
    geom_point(stat = "summary",
               fun = "mean",
               position = position_dodge(dodging),
               size = treatment_points_size) +
  labs(title = paste("Time point", time_points_with_water_addtion[time_point_i]),
       x = "", 
       y = "Evaporation (ml)") +
  theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          legend.position = legend_position) +
  geom_errorbar(aes(ymax = water_addition_ml + ci,
                    ymin = water_addition_ml - ci),
                width = width_errorbar,
                position = position_dodge(dodging)) 
  
}

grid.arrange(p[[1]], p[[2]], p[[3]], p[[4]], p[[5]], ncol = 2, nrow = 3)
```

```{r}

# Construct a model to study the evaporation rates among treatments

full_model = lmer(water_addition_ml ~
                  ecosystem_type +
                    (1 | day) +
                    (1 | culture_ID),
                    REML = FALSE,
                  data = ds_ecosystems_filtered)

null_model = lmer(water_addition_ml ~
                    (1 | day) +
                    (1 | culture_ID),
                  data = ds_ecosystems_filtered,
                  REML = FALSE)

compute.model.stats(full_model,
                    null_model,
                    "mixed_model")

emmeans(full_model,
        specs = pairwise ~ ecosystem_type,
        adjust = "tukey",
        bias.adj = TRUE,
        lmer.df = "satterthwaite")

qqnorm(resid(full_model))
ds_ecosystems_filtered %>%
    mutate(predicted = fitted(full_model),
           residuals = resid(full_model)) %>%
    plot_ly(x = ~predicted,
            y = ~residuals,
            type = "scatter",
            mode = "markers",
            marker = list(size = 5, color = "#4C78A8"),
            text = paste(" ID: ", 
                         ds_ecosystems_filtered$culture_ID, 
                         "<br>",
                         "Day: ", 
                         ds_ecosystems_filtered$day, 
                         "<br>",
                         "Ecosystem Type: ", 
                         ds_ecosystems_filtered$ecosystem_type),
            hoverinfo = "text") %>%
    plotly::layout(title = "Residuals vs. Fitted Values",
                   xaxis = list(title = "Fitted Values"),
                   yaxis = list(title = "Residuals"))
```