---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

We want here to plot the final paper version of the ratio between autotrophic and heterotrophic biomass in small, medium, and large unconnected ecosystems. We need to plot it again instead of using the plots we used in the analysis because we want to have S, M, and L in the legend.

```{r}

# Define ecosystems and response variable you want to plot.

ecosystem_type_input = c("S",
                     "M",
                     "L")

response_variable = "auto_hetero_ratio"
```

```{r fig.height = figures_height_rmd_output}

# Construct plot

p = ds_ecosystems %>%
  
  # Manipulate
  
  mutate(ecosystem_type = case_when(ecosystem_type == "Small unconnected" ~ "S",
                                ecosystem_type == "Medium unconnected" ~ "M",
                                ecosystem_type == "Large unconnected" ~ "L")) %>%
  filter(ecosystem_type %in% ecosystem_type_input,
         !is.na(!!sym(response_variable))) %>%
  summarySE(measurevar = response_variable,
            groupvars = c("day", "ecosystem_type", "ecosystem_size", "connection")) %>%
  
  # Create plot
  
  ggplot(aes(x = day,
             y = get(response_variable),
             group = interaction(day, ecosystem_type),
             color = ecosystem_type)) +
  
  # Points
  
  geom_point(stat = "summary",
             fun = "mean",
             position = position_dodge(dodging),
             size = treatment_points_size) +
  geom_errorbar(aes(ymax = get(response_variable) + ci,
                    ymin = get(response_variable) - ci),
                width = width_errorbar,
                position = position_dodge(dodging)) +
  
  # Lines
  
  geom_line(stat = "summary",
            fun = "mean",
            aes(group = ecosystem_type),
            position = position_dodge(dodging),
            linewidth = treatment_lines_linewidth) +
  
  # Axes and legend
  
  labs(x = axis_names$axis_name[axis_names$variable == "day"],
       y = axis_names$axis_name[axis_names$variable == response_variable],
       color = "") +
  scale_x_continuous(breaks = unique(ds_ecosystems$day)) +
  guides(color = guide_legend(title = NULL,
                              nrow = 1),
         linetype = guide_legend(title = NULL,
                                 nrow = 1)) +
  scale_color_manual(values = c("#000000",
                                "#737373",
                                "#bdbdbd")) +
  
  # Extra graphic elements
  
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = legend_position,
        legend.key.width = unit(legend_width_cm, "cm"),
        axis.title.x = element_text(size = paper_labels_size),
        axis.title.y = element_text(size = paper_labels_size),
        legend.text = element_text(size = paper_labels_size)) +
  geom_rect(xmin = grey_background_xmin, 
            xmax = grey_background_xmax,
            ymin = grey_background_ymin, 
            ymax = grey_background_ymax, 
            fill = grey_background_fill, 
            alpha = grey_background_alpha,
            color = grey_background_color) + 
  geom_hline(yintercept = 0,
             color = zero_line_colour,
             linetype = zero_line_line_type,
             linewidth = zero_line_line_width) +
  
  geom_vline(xintercept = resource_flow_days,
             linetype = resource_flow_line_type,
             color = resource_flow_line_colour,
             linewidth = resource_flow_line_width)

p
```

```{r echo = FALSE, results=FALSE}

# Save plot

png(file = here("6_results", "figures", disturbance_global_input, "paper", "ecosystem_auto_heterotrophic_ratio.png"),
    width = paper_width,
    height = paper_height,
    units = paper_units,
    res = paper_res)

p

dev.off()
```