---
title: "Data manipulation: PatchSizePilot"
author: "Emanuele Giacomuzzo"
date: "2022-08-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Ecosystems (`ds_ecosystems`)

In this dataset (`ds_ecosystems`) each row represents a ecosystem at a time point. I use the data from the 40 threshold analysis for Ble, Cep, Spi and the data from the 13 threshold analysis for all the other protists (Col, Eup, Lox, Pau, Pca, Spi te, Tet).

```{r}

# ---  IMPORT & BIND T0 DATASETS --- #

# Import t0 ecosystem level information - biomass and individuals

ds_ecosystems_t0 = read.csv(here("..",
                                 "1_data", 
                                 "ecosystems_13_threshold", 
                                 "t0.csv")) %>%
  mutate(time_point =  as.numeric(str_extract(time_point, "\\d+")),
         day = 0,
         video_replicate = file) %>%
  select(time_point,
         day,
         video_replicate,
         file,
         bioarea_per_volume,
         indiv_per_volume)

# Import t0 ecosystem level information - species indiv/µl (threshold 13)

species_ID_13_threshold_t0 = read.csv(here("..",
                                           "1_data", 
                                           "species_ID_13_threshold", 
                                           paste0("t0.csv"))) %>%
  rename(Ble_indiv_per_volume = Ble,
         Cep_indiv_per_volume = Cep,
         Col_indiv_per_volume = Col,
         Eug_indiv_per_volume = Eug,
         Eup_indiv_per_volume = Eup,
         Lox_indiv_per_volume = Lox,
         Pau_indiv_per_volume = Pau,
         Pca_indiv_per_volume = Pca,
         Spi_indiv_per_volume = Spi,
         Spi_te_indiv_per_volume = Spi_te,
         Tet_indiv_per_volume = Tet) %>%
  select(file,
         all_of(species_IDD_with_13_threshold_indiv_per_volume))

# Import t0 ecosystem level information - species indiv/µl (threshold 40)

species_ID_40_threshold_t0 = read.csv(here("..",
                                           "1_data", 
                                           "species_ID_40_threshold", 
                                           paste0("t0.csv"))) %>%
  rename(Ble_indiv_per_volume = Ble,
         Cep_indiv_per_volume = Cep,
         Col_indiv_per_volume = Col,
         Eug_indiv_per_volume = Eug,
         Eup_indiv_per_volume = Eup,
         Lox_indiv_per_volume = Lox,
         Pau_indiv_per_volume = Pau,
         Pca_indiv_per_volume = Pca,
         Spi_indiv_per_volume = Spi,
         Spi_te_indiv_per_volume = Spi_te,
         Tet_indiv_per_volume = Tet) %>%
  select(file,
         all_of(species_IDD_with_40_threshold_indiv_per_volume))

# Bind the three previous datasets

ds_ecosystems_t0 = ds_ecosystems_t0 %>%
  left_join(species_ID_13_threshold_t0,
            by = "file") %>%
  left_join(species_ID_40_threshold_t0,
            by = "file") %>%
  mutate(file =  as.numeric(str_extract(file, "\\d+")))
```

```{r}

# ---  ELONGATE T0 DATASET --- # 

# Initialize an empty list to store elongated datasets for each video at time 
# point 0

ds_ecosystems_t0_elongated <- list() 

# Loop over each video taken at time point 0

for (video_i in 1:n_videos_taken_t0) { 
  
  # Filter the original dataset to select data for the current video
  
  single_video = ds_ecosystems_t0 %>% 
    filter(file == video_i) 
  
  # Create an elongated dataset for the current video, mutating it with new time point and related variables
  
  ds_ecosystems_t0_elongated[[video_i]] = ecosystems_info %>% 
    mutate(
      time_point = 0,  # Assign the time point (0 indicates the start or baseline)
      day = 0,  # Assign the day (0 indicates the starting day)
      file = single_video$file,  # Add the current video's file name
      video_replicate = single_video$video_replicate,  # Add the replicate information for the video
      bioarea_per_volume = single_video$bioarea_per_volume,  # Add biological area per volume from the single video
      indiv_per_volume = single_video$indiv_per_volume,  # Add individual count per volume
      Ble_indiv_per_volume = single_video$Ble_indiv_per_volume,  # Add Ble individual count per volume
      Cep_indiv_per_volume = single_video$Cep_indiv_per_volume,  # Add Cep individual count per volume
      Col_indiv_per_volume = single_video$Col_indiv_per_volume,  # Add Col individual count per volume
      Eug_indiv_per_volume = single_video$Eug_indiv_per_volume,  # Add Eug individual count per volume
      Eup_indiv_per_volume = single_video$Eup_indiv_per_volume,  # Add Eup individual count per volume
      Lox_indiv_per_volume = single_video$Lox_indiv_per_volume,  # Add Lox individual count per volume
      Pau_indiv_per_volume = single_video$Pau_indiv_per_volume,  # Add Pau individual count per volume
      Pca_indiv_per_volume = single_video$Pca_indiv_per_volume,  # Add Pca individual count per volume
      Spi_indiv_per_volume = single_video$Spi_indiv_per_volume,  # Add Spi individual count per volume
      Spi_te_indiv_per_volume = single_video$Spi_te_indiv_per_volume,  # Add Spi_te individual count per volume
      Tet_indiv_per_volume = single_video$Tet_indiv_per_volume  # Add Tet individual count per volume
    ) 
}

# Combine all elongated datasets into a single data frame

ds_ecosystems_t0_elongated = ds_ecosystems_t0_elongated %>% 
  bind_rows() 
```

```{r}

# ---  CLEAN THE COLUMNS OF T0 --- #

ds_ecosystems_t0 = ds_ecosystems_t0_elongated %>%
  select(file,
         time_point,
         day,
         ecosystem_ID,
         video_replicate,
         bioarea_per_volume,
         indiv_per_volume,
         all_of(protist_species_indiv_per_volume))

# Test code

expect_equal(nrow(ds_ecosystems_t0), 
             sum(n_videos_taken_t0 * n_cultures))
```

```{r}

# ---  IMPORT AND BIND ALL TIME POINTS BUT T0 --- #

ds_ecosystems_t1_to_t7 = NULL

for (time_point_i in time_points_without_t0) {
  
  species_ID_13_threshold = read.csv(here("..",
                                          "1_data", 
                                          "species_ID_13_threshold", 
                                          paste0("t", time_point_i, ".csv"))) %>%
    rename(Ble_indiv_per_volume = Ble,
           Cep_indiv_per_volume = Cep,
           Col_indiv_per_volume = Col,
           Eug_indiv_per_volume = Eug,
           Eup_indiv_per_volume = Eup,
           Lox_indiv_per_volume = Lox,
           Pau_indiv_per_volume = Pau,
           Pca_indiv_per_volume = Pca,
           Spi_indiv_per_volume = Spi,
           Spi_te_indiv_per_volume = Spi_te,
           Tet_indiv_per_volume = Tet) %>% 
    select(file,
           all_of(species_IDD_with_13_threshold_indiv_per_volume))
  
  
  species_ID_40_threshold = read.csv(here("..",
                                          "1_data", 
                                          "species_ID_40_threshold", 
                                          paste0("t", time_point_i, ".csv"))) %>%
    rename(Ble_indiv_per_volume = Ble,
           Cep_indiv_per_volume = Cep,
           Col_indiv_per_volume = Col,
           Eug_indiv_per_volume = Eug,
           Eup_indiv_per_volume = Eup,
           Lox_indiv_per_volume = Lox,
           Pau_indiv_per_volume = Pau,
           Pca_indiv_per_volume = Pca,
           Spi_indiv_per_volume = Spi,
           Spi_te_indiv_per_volume = Spi_te,
           Tet_indiv_per_volume = Tet) %>% 
    select(file,
           all_of(species_IDD_with_40_threshold_indiv_per_volume))
  
  
  ds_ecosystems_t1_to_t7[[time_point_i]] = read.csv(here("..",
                                                         "1_data", 
                                                         "ecosystems_13_threshold", 
                                                         paste0("t", 
                                                                time_point_i, 
                                                                ".csv"))) %>%
    arrange(file) %>%
    rename(ecosystem_ID = culture_ID) %>%
    mutate(video_replicate = rep(1 : time_point_day$video_replicates[time_point_i+1],
                                 each = n_cultures),
           day = time_point_day$day[time_point_day$time_point == time_point_i]) %>%
    select(file,
           time_point,
           day,
           video_replicate,
           file,
           ecosystem_ID,
           bioarea_per_volume,
           indiv_per_volume)
  
  ds_ecosystems_t1_to_t7[[time_point_i]] = ds_ecosystems_t1_to_t7[[time_point_i]] %>%
    left_join(species_ID_13_threshold,
                by = "file") %>%
    left_join(species_ID_40_threshold,
                by = "file")
    
}

ds_ecosystems_t1_to_t7 = ds_ecosystems_t1_to_t7 %>%
  bind_rows()
```

```{r}

# ---  BIND T0 WITH ALL OTHER TIME POINTS --- #

ds_ecosystems = rbind(ds_ecosystems_t0,
                      ds_ecosystems_t1_to_t7) %>%
  left_join(ecosystems_info,
            by = "ecosystem_ID") 
    
expect_equal(nrow(ds_ecosystems),
             sum(sum(time_point_day$video_replicates) * n_cultures))
```

```{r}

# ---  MODIFY COLUMNS & CALCULATE DIVERSITY METRICS --- #

ds_ecosystems <- ds_ecosystems %>%
  
  # Extract numerical values
  
  mutate(time_point =  as.numeric(str_extract(time_point, "\\d+")),
         file =  as.numeric(str_extract(file, "\\d+"))) %>%
  
  # Change from the word volume to the word μL
  
  rename(bioarea_µm2_per_μL = bioarea_per_volume) %>%
  rename_all( ~ gsub("volume", "μL", .)) %>%
  
  # Change units of measurements to ml
  
  mutate(bioarea_µm2_per_ml = bioarea_µm2_per_μL * 10^3,
         bioarea_mm2_per_ml = bioarea_µm2_per_ml * 10^(-6),
         Ble_indiv_per_ml = Ble_indiv_per_μL * 10^3,
         Cep_indiv_per_ml = Cep_indiv_per_μL * 10^3,
         Col_indiv_per_ml = Col_indiv_per_μL * 10^3,
         Eug_indiv_per_ml = Eug_indiv_per_μL * 10^3,
         Eup_indiv_per_ml = Eup_indiv_per_μL * 10^3,
         Lox_indiv_per_ml = Lox_indiv_per_μL * 10^3,
         Pau_indiv_per_ml = Pau_indiv_per_μL * 10^3,
         Pca_indiv_per_ml = Pca_indiv_per_μL * 10^3,
         Spi_indiv_per_ml = Spi_indiv_per_μL * 10^3,
         Spi_te_indiv_per_ml = Spi_te_indiv_per_μL * 10^3,
         Tet_indiv_per_ml = Tet_indiv_per_μL * 10^3) %>%
  
  # Take off problematic videos
  
  filter(!(time_point %in% videos_to_take_off$time_point & 
           file %in% videos_to_take_off$file)) %>%
  
  # Take off problematic ecosystems
  
  filter(!ecosystem_ID %in% ecosystems_to_take_off) %>%
  
  # Average videos

  group_by(across(all_of(columns_ecosystems))) %>%
  summarise(across(contains("_per_ml"), mean),
            across(contains("_tot"), mean)) %>%
  ungroup() %>%
  
  # Calculate ecosystem-level metrics
  
  mutate(indiv_per_ml = !!rlang::parse_expr(paste(protist_species_indiv_per_ml, 
                                                  collapse = " + ")),
         
         bioarea_tot_mm2 = bioarea_mm2_per_ml * ecosystem_size_ml,
         
         indiv_tot = indiv_per_ml * ecosystem_size_ml,
         
         Ble_tot_indiv = Ble_indiv_per_ml * ecosystem_size_ml,
         Cep_tot_indiv = Cep_indiv_per_ml * ecosystem_size_ml,
         Col_tot_indiv = Col_indiv_per_ml * ecosystem_size_ml,
         Eug_tot_indiv = Eug_indiv_per_ml * ecosystem_size_ml,
         Eup_tot_indiv = Eup_indiv_per_ml * ecosystem_size_ml,
         Lox_tot_indiv = Lox_indiv_per_ml * ecosystem_size_ml,
         Pau_tot_indiv = Pau_indiv_per_ml * ecosystem_size_ml,
         Pca_tot_indiv = Pca_indiv_per_ml * ecosystem_size_ml,
         Spi_tot_indiv = Spi_indiv_per_ml * ecosystem_size_ml,
         Spi_te_tot_indiv = Spi_te_indiv_per_ml * ecosystem_size_ml,
         Tet_tot_indiv = Tet_indiv_per_ml * ecosystem_size_ml,
         
         across(.cols = all_of(protist_species_indiv_per_ml), 
                .fns = list(dominance = ~ (. / indiv_per_ml) * 100), 
                .names = "{col}_dominance"),
         
         auto_hetero_ratio = (Eug_indiv_per_ml + Eup_indiv_per_ml) / 
                             (Ble_indiv_per_ml + 
                              Cep_indiv_per_ml + 
                              Col_indiv_per_ml + 
                              Lox_indiv_per_ml + 
                              Pau_indiv_per_ml + 
                              Pca_indiv_per_ml +
                              Spi_indiv_per_ml + 
                              Spi_te_indiv_per_ml +
                              Tet_indiv_per_ml))

# Add biodiversity metrics
  
ds_ecosystems = calculate.alpha.diversity()

# Add median body size

ds_median_body_size = ds_individuals %>%
  group_by(time_point,
           ecosystem_ID,
           file) %>%
  summarise(median_body_area_µm2 = median(body_area_µm2)) %>%
  group_by(time_point,
           ecosystem_ID) %>%
  summarise(median_body_area_µm2 = mean(median_body_area_µm2))
  
ds_ecosystems = full_join(ds_ecosystems, ds_median_body_size)
```