---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

```{r}

# --- PLOT BIOMASS-SPECIES RICHNESS RELATIONSHIP --- #

ds_ecosystems %>%
    filter(is.na(species_richness) != TRUE) %>%
    ggplot(aes(x = species_richness,
               y = bioarea_mm2_per_ml)) +
    geom_point() +
    xlim(0, length(protist_species)) +
    labs(x = axis_names$axis_name[axis_names$variable == "species_richness"],
         y = axis_names$axis_name[axis_names$variable == "bioarea_mm2_per_ml"]) + 
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          legend.position = legend_position,
          legend.key.width = unit(legend_width_cm, "cm"))
```

```{r}

# --- PLOT BIOMASS-SHANNON RELATIONSHIP --- #

ds_ecosystems %>%
  filter(is.na(shannon) != TRUE) %>%
  ggplot(aes(x = shannon,
             y = bioarea_mm2_per_ml)) +
  geom_point() +
  labs(x = axis_names$axis_name[axis_names$variable == "shannon"],
       y = axis_names$axis_name[axis_names$variable == "bioarea_mm2_per_ml"]) + 
  theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          legend.position = legend_position,
          legend.key.width = unit(legend_width_cm, "cm"))
```

```{r}

# --- PLOT BIOMASS-EVENESS RELATIONSHIP --- #

ds_ecosystems %>%
  filter(is.na(evenness_pielou) != TRUE) %>%
  ggplot(aes(x = evenness_pielou,
             y = bioarea_mm2_per_ml)) +
  geom_point() +
  labs(x = axis_names$axis_name[axis_names$variable == "evenness_pielou"],
       y = axis_names$axis_name[axis_names$variable == "bioarea_mm2_per_ml"]) + 
  theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          legend.position = legend_position,
          legend.key.width = unit(legend_width_cm, "cm"))

```