---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

```{r}

# --- DEFINE PLOTTING PARAMETERS --- #

legend_row_n_input = 2

x_min = -0.2
x_max = 30

y_min_alpha = 0.3
y_max_alpha = 2.1

y_min_beta = 0
y_max_beta = 1
```

```{r}

# --- PREPARE DATA FOR PLOTTING --- #

metaecosystem_type_all = c("Medium-Medium unconnected",
                           "Medium-Medium connected",
                           "Small-Large unconnected",
                           "Small-Large connected")

data_for_plotting = ds_metaecosystems %>%
  mutate(metaecosystem_type = paste(metaecosystem_type, connection),
         disturbance == disturbance_selected)

```

```{r}

# --- CONSTRUCT PLOTS FOR ALPHA DIVERSITY (MEAN SHANNON) --- #

# Define parameters

response_variable = "mean_shannon"
alpha_plots = NULL
alpha_plots[[1]] = plot.empty.plot.presentations(y_min_alpha,
                                                 y_max_alpha,
                                                 "mean_shannon")

# Construct plots for alpha diversity

for (i in 1:length(metaecosystem_type_all)) {
  
  alpha_plots[[i+1]] = plot.metaecos.points.presentations(data_for_plotting,
                                                          metaecosystem_type_all[1:i],
                                                          response_variable,
                                                          legend_row_n_input) +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left),
                             "cm"),
          legend.position = "none") +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01)) + 
    xlim(x_min, x_max) +
    ylim(y_min_alpha, y_max_alpha)
  
  }
```

```{r}

# --- CONSTRUCT PLOTS FOR BETA DIVERSITY (BRAY CURTIS) --- #

# Define parameters

response_variable = "bray_curtis"
beta_plots = NULL

beta_plots[[1]] = plot.empty.plot.presentations(y_min_beta,
                                                y_max_beta,
                                                "bray_curtis")

# Construct plots for beta diversity

for (i in 1:length(metaecosystem_type_all)) {
  
  beta_plots[[i+1]] = plot.metaecos.points.presentations(data_for_plotting,
                                                         metaecosystem_type_all[1:i],
                                                         response_variable,
                                                         legend_row_n_input) +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left),
                             "cm"),
          legend.position = "none") +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01)) +
    xlim(x_min, x_max) +
    ylim(y_min_beta, y_max_beta)
  
  }
```

```{r}

# --- COMBINE PLOTS FOR ALPHA AND BETA DIVERSITY --- #

p_combined = NULL
alpha_beta_plot_number = data.frame(alpha = as.double(c("1", "2", "3", "4", "5", "5", "5", "5", "5")),
                                    beta = as.double(c("1", "1", "1", "1", "1", "2", "3", "4", "5")))

for(i in 1:length(alpha_beta_plot_number$alpha)){
  
  p_combined[[i]] = ggarrange(
  alpha_plots[[alpha_beta_plot_number$alpha[i]]] +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text = element_text(size = presentation_axes_size)) +
    font("legend.text", size = size_legend) +
    font("ylab", size = presentation_y_axis_size),
  NULL,
  beta_plots[[alpha_beta_plot_number$beta[i]]] +
    theme(axis.text = element_text(size = presentation_axes_size)) + 
    font("legend.text", size = size_legend) +
    font("xlab", size = presentation_y_axis_size) +
    font("ylab", size = presentation_y_axis_size),
  heights = c(0.999, 0.001, 0.999),
  nrow = 3,
  align = "v",
  label.x = 0.1,
  label.y = 0.8)

  }
```

```{r results=FALSE}

# --- SAVE COMBINED PLOTS --- #

for(i in 1:length(alpha_beta_plot_number$alpha)){
  
  png(file = here("..",
                  "3_results", 
                  "figures", 
                  disturbance_selected, 
                  "presentations", 
                  paste0(i, "_metaecos_diversity.png")),
      width = presentation_figure_width,
      height = presentation_figure_height,
      units = presentation_figure_units,
      res = presentation_figure_res)
  
  print(p_combined[[i]])
  
  dev.off()
  
  }
```