---
title: "Video analysis script"
output: html_document
date: "2022-11-09"
editor_options: 
  chunk_output_type: console
---

Here I want to check whether I can distinguish between Tet and Chi (food of Ble). To do so, let's look at the traits of Ble and Chi.

```{r}
load(here("data", "morphology", "training.RData"))
training = morph_mvt
rm(morph_mvt)
```

```{r}
training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = mean_grey)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = mean_area)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = mean_perimeter)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = mean_major)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = mean_minor)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = mean_ar)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = mean_turning)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = duration)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = N_frames)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = max_net)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = net_disp)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = net_speed)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = gross_disp)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = gross_speed)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = max_step)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = min_step)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = max_gross_speed)) +
  geom_boxplot()

training %>%
  filter(species == "Ble" | species == "Tet") %>%
  ggplot(aes(x = species,
             y = min_gross_speed)) +
  geom_boxplot()
```

It seems like there's no great way of telling them apart. 
