---
title: "Untitled"
output: html_document
date: "2024-10-02"
editor_options: 
  chunk_output_type: console
---

```{r}

# --- FILTER DATA AND CHANGE THE NAME OF LEVELS --- #

data_for_analysis = data_for_analysis %>%
  filter(time_point %in% time_points_model,
         metaecosystem_type %in% metaecosystem_type_selected,
         !is.na(!!sym(response_variable_selected)),
         !is.na(total_water_addition_ml)) %>%
  mutate(metaecosystem_type = case_when(metaecosystem_type == "Small-Large unconnected" ~ "SL unc",
                                    metaecosystem_type == "Medium-Medium unconnected" ~ "MM unc",
                                    metaecosystem_type == "Small-Small meta-ecosystem" ~ "SS con",
                                    metaecosystem_type == "Medium-Medium meta-ecosystem" ~ "MM con",
                                    metaecosystem_type == "Large-Large meta-ecosystem" ~ "LL con",
                                    metaecosystem_type == "Small-Large meta-ecosystem" ~ "SL con",
                                    TRUE ~ metaecosystem_type),
         type_n_conn = paste(metaecosystem_type, connection))
```

```{r}

# --- PREPARE TO COMPARE FULL, REDUCED, AND NULL MODEL WHILE RESHUFFLING ECOSYSTEM COMBINATIONS --- #

unconnected_combinations_sets_filtered =  unconnected_combinations_sets %>%
  filter(disturbance == disturbance_global_selected,
         metaecosystem_type %in% metaecosystem_type_selected)

n_sets = unconnected_combinations_sets_filtered %>%
  pull(set) %>%
  max()

iterated_results_table = data.frame(Response = as.character(NA),
                                    Levels = as.character(NA),
                                    ΔAIC_full = NA,
                                    p_full = NA,
                                    ΔR2_full = NA,
                                    ΔAIC_fix = NA,
                                    p_fix = NA,
                                    ΔR2_fix = NA,
                                    combination_set = NA,
                                    system_nr_unconnected_systems = as.character(NA)) %>%
  slice(-1)
```

```{r}
high_MM_conn = c(1, 0, 0, 0, 0, 0, 0, 0)
high_MM_unc = c(0, 1, 0, 0, 0, 0, 0, 0)
high_SL_conn = c(0, 0, 1, 0, 0, 0, 0, 0)
high_SL_unc = c(0, 0, 0, 1, 0, 0, 0, 0)
low_MM_conn = c(0, 0, 0, 0, 1, 0, 0, 0)
low_MM_unc = c(0, 0, 0, 0, 0, 1, 0, 0)
low_SL_conn = c(0, 0, 0, 0, 0, 0, 1, 0)
low_SL_unc = c(0, 0, 0, 0, 0, 0, 0, 1)
```

```{r}

for (set_i in 1:n_sets) {
  
  system_nr_unconnected_systems_selected = unconnected_combinations_sets_filtered %>%
    filter(metaecosystem_type %in% metaecosystem_type_selected,
           connection == "unconnected",
           set == set_i) %>%
    pull(system_nr)
  
  filtered_data_2 = filtered_data %>%
    filter(connection == "connected" | 
          (connection == "unconnected" &
           system_nr %in% system_nr_unconnected_systems_selected))
  
  full_model = try.different.optimizer.full.model.holistic(data_for_analysis)
  
  # If all the optimisers fail, move on to the next iteration

  if (is.null(full_model)) {
    
    cat("This model could not be fitted with any optimiser. The unconnected meta-ecosystems in this iteration were:", 
        system_nr_unconnected_systems_selected, 
        "\n")
    next
    
  }
  
  emmeans_output = emmeans(full_model,
                           specs = ~ type_conn * day * disturbance ,
                           method = "pairwise", 
                           by = "disturbance",
                           adjust = "sidak",
                           bias.adj = TRUE,
                           lmer.df = "satterthwaite") 
  
  summary(emmeans_output)

  
  contrasts = contrast(emmeans_output, 
                       method = list("high SL_conn - SL_unc" = high_SL_conn - high_SL_unc,
                                     "high MM_conn - MM_unc" = high_MM_conn - high_MM_unc,
                                     "low SL_conn - SL_unc" = low_SL_conn - low_SL_unc,
                                     "low MM_conn - MM_unc" = low_MM_conn - low_MM_unc)) %>%
    as.data.frame() %>%
    mutate(combination_set = set_i,
           system_nr_unconnected_systems = paste(system_nr_unconnected_systems_selected, collapse = ", "))
  
}

```