---
title: "patches_all"
author: "Emanuele Giacomuzzo"
date: "2022-08-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

### All patches {.tabset .tabset-pills}

#### Bioarea density

*Research question: how does the density of bioarea changes across patch types?*

```{r}

ds_patches %>%
          filter(disturbance == disturbance_input) %>%
          ggplot(aes(x = day,
             y = bioarea_per_ml,
             group = interaction(day, patch_type),
             fill = patch_type)) +
          geom_boxplot(width = boxplot_width) +
          labs(x = "Day",
               y = y_axis_bioarea_density,
               fill = "") +
          theme_bw() +
          theme(panel.grid.major = element_blank(),
                panel.grid.minor = element_blank(),
                      legend.position = "bottom") +
          geom_vline(xintercept = first_resource_flow + 0.6,
                     linetype="dotdash",
                     color = "grey",
                     size=0.7) +
  geom_hline(yintercept=0,
             color = zero_line_colour,
             linetype = zero_line_line_type,
             size = zero_line_line_width)
  
```

#### Total bioarea

*Research question: how does total bioarea changes across patch types?*

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(
    aes(
      x = day,
      y = bioarea_tot,
      group = interaction(day, patch_type),
      fill = patch_type
    )
  ) +
  geom_boxplot(width = boxplot_width) +
  labs(
    x = "Day",
    y = y_axis_total_bioarea,
    fill = ""
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_hline(yintercept=0,
             color = zero_line_colour,
             linetype = zero_line_line_type,
             size = zero_line_line_width)
```