---
title: "metaecosystems"
author: "Emanuele Giacomuzzo"
date: "2022-10-18"
output: html_document
editor_options: 
  chunk_output_type: console
---

#### Differently sized patches

```{r}
for (disturbance_input in c("low", "high")) {
  print(
    ds_regional_biomass %>%
      filter(disturbance == disturbance_input) %>%
      filter (metaecosystem_type == "S_L" |
                metaecosystem_type == "M_M") %>%
      ggplot (
        aes(
          x = day,
          y = beta_diversity,
          group = interaction(day, metaecosystem_type),
          fill = metaecosystem_type
        )
      ) +
      geom_boxplot() +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Beta diversity (Jaccard index)",
        color = '',
        fill = ''
      ) +
      scale_fill_manual(
        values = c(colour_MM, colour_SL),
        labels = c("Medium-Medium",
                   "Small-Large")) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.3, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)
      )  +
      geom_vline(
        xintercept = first_perturbation_day + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      labs(caption = "Vertical grey line: first perturbation")
  )
}
```

**Model time series**

```{r eval = FALSE}
data = ds_regional_biomass %>%
  filter (metaecosystem_type == "S_L" |
            metaecosystem_type == "M_M",
          time_point >= 2)

stepswise_AIC = glmulti(
  y = total_regional_bioarea ~
    day * metaecosystem_type * disturbance +
    (day | system_nr),
  data = data,
  fitfunc = lmer
)

summary(stepswise_AIC)
```

#### Equally sized patches

```{r}
for (disturbance_input in c("low", "high")) {
  print(
    ds_regional_biomass %>%
      filter(disturbance == disturbance_input) %>%
      filter(!metaecosystem_type == "S_L") %>%
      filter(!metaecosystem_type == "S_L_from_isolated") %>%
      ggplot(
        aes(
          x = day,
          y = beta_diversity,
          group = interaction(day, metaecosystem_type),
          fill = metaecosystem_type
        )
      ) +
      geom_boxplot() +
      labs(
        title = paste0("Disturbance = ", disturbance_input),
        x = "Day",
        y = "Beta diversity (Jaccard index)",
        fill = ""
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.3, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)
      ) +
      scale_fill_manual(
        values = c(colour_large, colour_medium, colour_small),
        labels = c(
        "Large-Large",
        "Medium-Medium",
        "Small-Small"
      )) +
      geom_vline(
        xintercept = first_perturbation_day + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      labs(caption = "Vertical grey line: first perturbation")
  )
}
```
