---
title: "Data Classes Averaged"
output: html_document
date: "2022-11-22"
editor_options: 
  chunk_output_type: console
---

### Size classes abundance (ds_classes_averaged)

I am here creating 12 size classes as in @Jacquet2020. However, for some reason it seems like our body size classes are really different.

```{r nr_of_size_classes}
nr_of_size_classes = 12
```

```{r}
largest_size = max(ds_body_size$mean_area)
#largest_size = exp(11.4) To see what happens, let's set the largest size to the one of @Jacquet2020. 
```

The logarithm of the largest individual in the experiment was `r log(largest_size)` μm² compared to 11.4 in  @Jacquet2020. 

```{r ds_classes_averaged-create-ds_classes, eval = FALSE}
size_class_width = largest_size / nr_of_size_classes

size_class_boundaries = seq(from = 0,
                            to = largest_size,
                            by = size_class_width)
single_videos_rows = NULL

row = 0
for (class in 1:nr_of_size_classes) {
  bin_lower_limit = size_class_boundaries[class]
  bin_upper_limit = size_class_boundaries[class + 1]
  mean_size = (size_class_boundaries[class] + size_class_boundaries[class + 1]) / 2
  
  
  for (time_point_input in 0:last_time_point) {
    for (culture_ID_input in 1:n_cultures) {
      for (replicate_video_input in 1:nr_videos[time_point_input + 1]) {
        row = row + 1
        
        video_class_abundance = ds_body_size %>%
          filter(
            bin_lower_limit <= mean_area,
            mean_area <= bin_upper_limit,
            time_point == time_point_input,
            culture_ID == culture_ID_input,
            replicate_video == replicate_video_input
          ) %>%
          summarise(size_class_abundance = n()) %>%
          pull(size_class_abundance)
        
        single_videos_rows[[row]] = ds_biomass_abund %>%
          filter(
            time_point == time_point_input,
            culture_ID == culture_ID_input
          ) %>%
          mutate(
            replicate_video = replicate_video_input,
            size_class_abundance = video_class_abundance,
            size_class_n = class,
            size_class = mean_size,
            log_size_class = log(size_class),
            log_abundance = log(size_class_abundance + 1)
          )
        
      }
    }
  }
}
ds_classes = single_videos_rows %>%
  bind_rows()

saveRDS(ds_classes, file = here("results", "ds_classes.RData"))
```

```{r ds_classes_averaged-average}
ds_classes = readRDS(here("results", "ds_classes.RData")) #Watch out: it contains 27468 rows instead of 27720 because we excluded already culture_ID = 60, which I spilled during the experiment.

ds_classes_averaged = ds_classes %>%
  group_by(
    culture_ID,
    metaecosystem,
    eco_metaeco_type,
    patch_size,
    disturbance,
    day,
    time_point,
    size_class_n,
    log_size_class
  ) %>%
  summarise(log_abundance = mean(log_abundance),
            size_class_abundance = mean(size_class_abundance)) %>%
  group_by(
    eco_metaeco_type,
    metaecosystem,
    patch_size,
    disturbance,
    day,
    time_point,
    size_class_n,
    log_size_class
  ) %>%
  summarise(
    log_abundance_sd = sd(log_abundance),
    abundance = mean(size_class_abundance),
    abundance_sd = sd(size_class_abundance),
    log_abundance = mean(log_abundance),
    sample_size = n(),
  ) %>%
  mutate(
    log_abundance_se = log_abundance_sd / sqrt(sample_size),
    log_abundance_lower_ci = log_abundance - qt(1 - (0.05 / 2), sample_size - 1) * log_abundance_se,
    log_abundance_upper_ci = log_abundance + qt(1 - (0.05 / 2), sample_size - 1) * log_abundance_se
  ) #Expected number of rows: 12 size classes * 8 eco_metaeco_types * 2 disturbance types * 8 time points = 1536
```

```{r}
ds_classes_averaged$abundance_hedges_d = NA

treatments_and_controls = data.frame(
  treatment = c("S (S_S)", "S (S_L)", "L (L_L)", "L (S_L)"),
  control = c("S", "S", "L", "L")
)

n_of_treatments = nrow(treatments_and_controls)

row_n = 0
for (disturbance_input in c("low", "high")) {
  for (treatment_n in 1:n_of_treatments) {
    for (time_point_input in 0:7) {
      for (size_class_input in 1:nr_of_size_classes) {
        row_n = row_n + 1
        
        eco_metaeco_treatment = treatments_and_controls$treatment[treatment_n]
        
        treatment = ds_classes_averaged %>%
          filter(
            disturbance == disturbance_input,
            eco_metaeco_type == eco_metaeco_treatment,
            time_point == time_point_input,
            size_class_n == size_class_input
          )
        
        eco_metaeco_control = treatments_and_controls$control[treatment_n]
        
        control = ds_classes_averaged %>%
          filter(
            disturbance == disturbance_input,
            eco_metaeco_type == eco_metaeco_control,
            time_point == time_point_input,
            size_class_n == size_class_input
          ) 
        
        #Body size class abundance
        
        hedges_d_size_class = calculate.hedges_d(
          treatment$abundance,
          treatment$abundance_sd,
          treatment$sample_size,
          control$abundance,
          control$abundance_sd,
          control$sample_size
        )
        
        ds_classes_averaged$abundance_hedges_d[ds_classes_averaged$disturbance == disturbance_input &
                                             ds_classes_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                             ds_classes_averaged$time_point == time_point_input &
                                             ds_classes_averaged$size_class_n == size_class_input] = hedges_d_size_class$d
        
        ds_classes_averaged$abundance_hedges_d_upper[ds_classes_averaged$disturbance == disturbance_input &
                                             ds_classes_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                             ds_classes_averaged$time_point == time_point_input &
                                             ds_classes_averaged$size_class_n == size_class_input] = hedges_d_size_class$upper_CI
        
        ds_classes_averaged$abundance_hedges_d_lower[ds_classes_averaged$disturbance == disturbance_input &
                                             ds_classes_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                             ds_classes_averaged$time_point == time_point_input &
                                             ds_classes_averaged$size_class_n == size_class_input] = hedges_d_size_class$lower_CI
        
        
      }
    }
  }
}
```

```{r}
saveRDS(ds_classes_averaged, file = here("results", "ds_classes_averaged.RData"))
```

```{r ds_classes_averaged-datatable}
datatable(ds_classes_averaged,
          rownames = FALSE,
          options = list(scrollX = TRUE),
          filter = list(position = 'top', 
                        clear = FALSE))
```