---
title: "Data manipulation: PatchSizePilot"
author: "Emanuele Giacomuzzo"
date: "2022-08-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Patch biomass & community density (`ds_patches`)

-   Every row is a patch at a certain time point.
-   The value of different videos have been already averaged.

```{r import_population_data_(ds_patches), message = FALSE, echo = TRUE}

#Import data

load(here("data", "population", "t0.RData"))
t0 = pop_output
load(here("data", "population", "t1.RData"))
t1 = pop_output
load(here("data", "population", "t2.RData"))
t2 = pop_output
load(here("data", "population", "t3.RData"))
t3 = pop_output
load(here("data", "population", "t4.RData"))
t4 = pop_output
load(here("data", "population", "t5.RData"))
t5 = pop_output
load(here("data", "population", "t6.RData"))
t6 = pop_output
load(here("data", "population", "t7.RData"))
t7 = pop_output
rm(pop_output)

species_ID_t0 = read.csv(here("data", "population_species_ID", "species_ID_t0.csv")) %>%
  select(file, Cep:Tet)
species_ID_t1 = read.csv(here("data", "population_species_ID", "species_ID_t1.csv")) %>%
  select(file, Cep:Tet)
species_ID_t2 = read.csv(here("data", "population_species_ID", "species_ID_t2.csv")) %>%
  select(file, Cep:Tet)
species_ID_t3 = read.csv(here("data", "population_species_ID", "species_ID_t3.csv")) %>%
  select(file, Cep:Tet)
species_ID_t4 = read.csv(here("data", "population_species_ID", "species_ID_t4.csv")) %>%
  select(file, Cep:Tet)
species_ID_t5 = read.csv(here("data", "population_species_ID", "species_ID_t5.csv")) %>%
  select(file, Cep:Tet)
species_ID_t6 = read.csv(here("data", "population_species_ID", "species_ID_t6.csv")) %>%
  select(file, Cep:Tet)
species_ID_t7 = read.csv(here("data", "population_species_ID", "species_ID_t7.csv")) %>%
  select(file, Cep:Tet)

species_ID_t0_Ble = read.csv(here("data", "population_species_ID_Ble", "species_ID_t0.csv")) %>%
  select(file, Ble)
species_ID_t1_Ble = read.csv(here("data", "population_species_ID_Ble", "species_ID_t1.csv")) %>%
  select(file, Ble)
species_ID_t2_Ble = read.csv(here("data", "population_species_ID_Ble", "species_ID_t2.csv")) %>%
  select(file, Ble)
species_ID_t3_Ble = read.csv(here("data", "population_species_ID_Ble", "species_ID_t3.csv")) %>%
  select(file, Ble)
species_ID_t4_Ble = read.csv(here("data", "population_species_ID_Ble", "species_ID_t4.csv")) %>%
  select(file, Ble)
species_ID_t5_Ble = read.csv(here("data", "population_species_ID_Ble", "species_ID_t5.csv")) %>%
  select(file, Ble)
species_ID_t6_Ble = read.csv(here("data", "population_species_ID_Ble", "species_ID_t6.csv")) %>%
  select(file, Ble)
species_ID_t7_Ble = read.csv(here("data", "population_species_ID_Ble", "species_ID_t7.csv")) %>%
  select(file, Ble)

species_ID_t0 = merge(species_ID_t0, species_ID_t0_Ble, by = "file")
species_ID_t1 = merge(species_ID_t1, species_ID_t1_Ble, by = "file")
species_ID_t2 = merge(species_ID_t2, species_ID_t2_Ble, by = "file")
species_ID_t3 = merge(species_ID_t3, species_ID_t3_Ble, by = "file")
species_ID_t4 = merge(species_ID_t4, species_ID_t4_Ble, by = "file")
species_ID_t5 = merge(species_ID_t5, species_ID_t5_Ble, by = "file")
species_ID_t6 = merge(species_ID_t6, species_ID_t6_Ble, by = "file")
species_ID_t7 = merge(species_ID_t7, species_ID_t7_Ble, by = "file")

t0 = merge(t0, species_ID_t0, by = "file")
t1 = merge(t1, species_ID_t1, by = "file")
t2 = merge(t2, species_ID_t2, by = "file")
t3 = merge(t3, species_ID_t3, by = "file")
t4 = merge(t4, species_ID_t4, by = "file")
t5 = merge(t5, species_ID_t5, by = "file")
t6 = merge(t6, species_ID_t6, by = "file")
t7 = merge(t7, species_ID_t7, by = "file")

rm(
  species_ID_t0,
  species_ID_t1,
  species_ID_t2,
  species_ID_t3,
  species_ID_t4,
  species_ID_t5,
  species_ID_t6,
  species_ID_t7
)
```

```{r tidy_time_points_(ds_patches), message = FALSE, echo = TRUE}

#Manipulate the columns "time" & "replicate_video"

t2$time = NULL
t3$time = NULL
t4$time = NULL
t5$time = NULL
t6$time = NULL
t7$time = NULL

t0$replicate_video = 1:12 #In t1 I took 12 videos of a single
t1$replicate_video = 1 #In t1 I took only 1 video/culture
t2$replicate_video = 1 #In t2 I took only 1 video/culture
t3$replicate_video = 1 #In t3 I took only 1 video/culture
t4$replicate_video = 1 #In t4 I took only 1 video/culture
t5$replicate_video = 1 #In t5 I took only 1 video/culture
t6$replicate_video = t6$replicate
t6$replicate = NULL
t7$replicate_video = t7$replicate
t7$replicate = NULL
```

```{r elongate-t0-to-merge-with-culture-info}

#Elongate t0 so that it can be joined with the information about the cultures.

number_of_columns_t0 = ncol(t0)
nr_of_cultures = nrow(culture_info)
nr_of_videos = nrow(t0)

t0 = t0[rep(row.names(t0), 
            nr_of_cultures), ] %>%
  arrange(file) %>%
  mutate(culture_ID = rep(1:nr_of_cultures, 
                          times = nr_of_videos))
```

```{r ds_patches-join-time-points, message = FALSE, echo = TRUE}

#Merge time points

t0 = merge(culture_info, t0, by = "culture_ID")
t1 = merge(culture_info, t1, by = "culture_ID")
t2 = merge(culture_info, t2, by = "culture_ID")
t3 = merge(culture_info, t3, by = "culture_ID")
t4 = merge(culture_info, t4, by = "culture_ID")
t5 = merge(culture_info, t5, by = "culture_ID")
t6 = merge(culture_info, t6, by = "culture_ID")
t7 = merge(culture_info, t7, by = "culture_ID")
ds_patches = rbind(t0, t1, t2, t3, t4, t5, t6, t7)
rm(t0, t1, t2, t3, t4, t5, t6, t7)
```

```{r ds_patches-tidy-dataset-columns, message = FALSE, echo = TRUE}

#Tidy dataset. 

ds_patches = ds_patches %>%
  filter(! culture_ID %in% ecosystems_to_take_off)

ds_patches$time_point[ds_patches$time_point=="t0"] = 0
ds_patches$time_point[ds_patches$time_point=="t1"] = 1
ds_patches$time_point[ds_patches$time_point=="t2"] = 2
ds_patches$time_point[ds_patches$time_point=="t3"] = 3
ds_patches$time_point[ds_patches$time_point=="t4"] = 4
ds_patches$time_point[ds_patches$time_point=="t5"] = 5
ds_patches$time_point[ds_patches$time_point=="t6"] = 6
ds_patches$time_point[ds_patches$time_point=="t7"] = 7
ds_patches$time_point = as.character(ds_patches$time_point)

ds_patches$day = NA
ds_patches$day[ds_patches$time_point== 0] = 0
ds_patches$day[ds_patches$time_point== 1] = 4
ds_patches$day[ds_patches$time_point== 2] = 8
ds_patches$day[ds_patches$time_point== 3] = 12
ds_patches$day[ds_patches$time_point== 4] = 16
ds_patches$day[ds_patches$time_point== 5] = 20
ds_patches$day[ds_patches$time_point== 6] = 24
ds_patches$day[ds_patches$time_point== 7] = 28

ds_for_evaporation = ds_patches #Keep this dataset for the evaporation effects

### Average videos

ds_patches = ds_patches %>%
  group_by(
    culture_ID,
    patch_size,
    patch_size_volume,
    disturbance,
    metaecosystem_type,
    time_point,
    day,
    metaecosystem,
    system_nr,
    eco_metaeco_type
  ) %>%
  summarise(
    bioarea_per_volume = mean(bioarea_per_volume),
    indiv_per_volume = mean(indiv_per_volume),
    Ble = mean(Ble),
    Cep = mean(Cep),
    Col = mean(Col),
    Eug = mean(Eug),
    Eup = mean(Eup),
    Lox = mean(Lox),
    Pau = mean(Pau),
    Pca = mean(Pca),
    Spi = mean(Spi),
    Spi_te = mean(Spi_te),
    Tet = mean(Tet)
  ) %>%
  ungroup()

#Change all the measures to ml
#bioarea_per_volume in the original data is in µm2 / µl -> convert to µm2 / ml
#indiv_per_volume & all protists in the original data are in individuals / µl -> convert to individuals / ml

ds_patches = ds_patches %>%
  mutate(bioarea_per_volume = bioarea_per_volume * 1000,
         bioarea_tot = bioarea_per_volume * patch_size_volume,
         indiv_per_volume = indiv_per_volume * 1000,
         indiv_tot = indiv_per_volume * patch_size_volume,
         Ble = Ble * 1000,
         Cep = Cep * 1000,
         Col = Col * 1000,
         Eug = Eug * 1000,
         Eup = Eup * 1000,
         Lox = Lox * 1000,
         Pau = Pau * 1000,
         Pca = Pca * 1000,
         Spi = Spi * 1000,
         Spi_te = Spi_te * 1000,
         Tet = Tet * 1000,
         Ble_tot = Ble * patch_size_volume,
         Cep_tot = Cep * patch_size_volume,
         Col_tot = Col * patch_size_volume,
         Eug_tot = Eug * patch_size_volume,
         Eup_tot = Eup * patch_size_volume,
         Lox_tot = Lox * patch_size_volume,
         Pau_tot = Pau * patch_size_volume,
         Pca_tot = Pca * patch_size_volume,
         Spi_tot = Spi * patch_size_volume,
         Spi_te_tot = Spi_te * patch_size_volume,
         Tet_tot = Tet * patch_size_volume)
```

```{r calculate_alpha_diversity_(ds_patches)}


# Calculate species richness
ds_patches = ds_patches %>%
  mutate(Ble_presence = case_when(Ble > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Cep_presence = case_when(Cep > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Col_presence = case_when(Col > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Eug_presence = case_when(Eup > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Eup_presence = case_when(Eug > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Lox_presence = case_when(Lox > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Pau_presence = case_when(Pau > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Pca_presence = case_when(Pca > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Spi_presence = case_when(Spi > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Spi_te_presence = case_when(Spi_te > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(Tet_presence = case_when(Tet > 0 ~ 1,
                                  TRUE ~ 0)) %>%
  mutate(species_richness = Ble_presence +
                            Cep_presence +
                            Col_presence +
                            Eug_presence +
                            Eup_presence +
                            Lox_presence +
                            Pau_presence +
                            Pca_presence +
                            Spi_presence +
                            Spi_te_presence +
                            Tet_presence) %>%
  select(-one_of(
    c(
      "Ble_presence",
        "Cep_presence",
        "Col_presence",
        "Eug_presence",
        "Eup_presence",
        "Lox_presence",
        "Pau_presence",
        "Pca_presence",
        "Spi_presence",
        "Spi_te_presence",
        "Tet_presence"
    )
  ))

#Calculate alpha diversity (shannon, simpson, inv simpson)

ds_patches$shannon = NA
ds_patches$simpson = NA
ds_patches$inv_simpson = NA
for (row in 1:nrow(ds_patches)){
  
  species_vector = ds_patches %>%
    slice(row) %>%
    select(Ble:Tet)
  
  shannon = diversity(species_vector, index = "shannon")
  simpson = diversity(species_vector, index = "simpson")
  inv_simpson = diversity(species_vector, index = "invsimpson")
  
  ds_patches[row,]$shannon = shannon
  ds_patches[row,]$simpson = simpson
  ds_patches[row,]$inv_simpson = inv_simpson
  
}
```

```{r add_baselines_(ds_patches)}

#Add baselines (from t1).

baselines = ds_patches %>%
  filter(time_point == 1) %>%
  group_by(culture_ID) %>%
  summarise(bioarea_per_volume_across_videos = mean(bioarea_per_volume),
            indiv_per_volume_across_videos = mean(indiv_per_volume),
            species_richness_across_videos = mean(species_richness),
            shannon_across_videos = mean(shannon),
            Ble_across_videos = mean(Ble),
            Cep_across_videos = mean(Cep),
            Col_across_videos = mean(Col),
            Eug_across_videos = mean(Eug),
            Eup_across_videos = mean(Eup),
            Lox_across_videos = mean(Lox),
            Pau_across_videos = mean(Pau),
            Pca_across_videos = mean(Pca),
            Spi_across_videos = mean(Spi),
            Spi_te_across_videos = mean(Spi_te),
            Tet_across_videos = mean(Tet)) %>%
  rename(baseline_bioarea = bioarea_per_volume_across_videos,
         baseline_indiv_per_volume = indiv_per_volume_across_videos,
         baseline_species_richness = species_richness_across_videos,
         baseline_shannon = shannon_across_videos,
         baseline_Ble = Ble_across_videos,
         baseline_Cep = Cep_across_videos,
         baseline_Col = Col_across_videos,
         baseline_Eug = Eug_across_videos,
         baseline_Eup = Eup_across_videos,
         baseline_Lox = Lox_across_videos,
         baseline_Pau = Pau_across_videos,
         baseline_Pca = Pca_across_videos,
         baseline_Spi = Spi_across_videos,
         baseline_Spi_te = Spi_te_across_videos,
         baseline_Tet = Tet_across_videos)

ds_patches = full_join(ds_patches, baselines)
```

```{r save_ds_biomas_abund}
saveRDS(ds_for_evaporation, file = here("results", "ds_for_evaporation.RData"))
saveRDS(ds_patches, file = here("results", "ds_patches.RData"))
```

```{r show_ds_patches, eval = displays_datasets}
datatable(ds_patches,
          rownames = FALSE,
          options = list(scrollX = TRUE),
          filter = list(position = 'top', 
                        clear = FALSE))
```
