---
title: "Data Patches Averaged"
output: html_document
date: "2022-11-22"
editor_options: 
  chunk_output_type: console
---

### Patch effect sizes (`ds_patches_averaged`)

```{r ds_patches_averaged}
ds_patches_averaged = ds_patches %>%
  group_by(
    culture_ID,
    system_nr,
    disturbance,
    time_point,
    day,
    patch_size,
    eco_metaeco_type 
  ) %>%
  summarise(
    baseline_bioarea_across_videos = mean(baseline_bioarea),
    baseline_indiv_per_volume_across_videos = mean(baseline_bioarea),
    baseline_species_richness_across_videos = mean(baseline_species_richness),
    baseline_shannon_across_videos = mean(baseline_shannon),
    baseline_Ble_across_videos = mean(baseline_Ble),
    baseline_Cep_across_videos = mean(baseline_Cep),
    baseline_Col_across_videos = mean(baseline_Col),
    baseline_Eug_across_videos = mean(baseline_Eug),
    baseline_Eup_across_videos = mean(baseline_Eup),
    baseline_Lox_across_videos = mean(baseline_Lox),
    baseline_Pau_across_videos = mean(baseline_Pau),
    baseline_Pca_across_videos = mean(baseline_Pca),
    baseline_Spi_across_videos = mean(baseline_Spi),
    baseline_Spi_te_across_videos = mean(baseline_Spi_te),
    baseline_Tet_across_videos = mean(baseline_Tet),
    bioarea_per_volume_across_videos = mean(bioarea_per_volume),
    indiv_per_volume_across_videos = mean(indiv_per_volume),
    species_richness_across_videos = max(species_richness),
    shannon_across_videos = mean(shannon),
    Ble_across_videos = mean(Ble),
    Cep_across_videos = mean(Cep),
    Col_across_videos = mean(Col),
    Eug_across_videos = mean(Eug),
    Eup_across_videos = mean(Eup),
    Lox_across_videos = mean(Lox),
    Pau_across_videos = mean(Pau),
    Pca_across_videos = mean(Pca),
    Spi_across_videos = mean(Spi),
    Spi_te_across_videos = mean(Spi_te),
    Tet_across_videos = mean(Tet)
  ) %>%
  group_by(disturbance, 
           eco_metaeco_type, 
           patch_size, 
           time_point, 
           day) %>%
  summarise(
    sample_size = n(),
    baseline_bioarea = mean(baseline_bioarea_across_videos),
    baseline_indiv_per_volume = mean(indiv_per_volume_across_videos),
    baseline_species_richness = mean(species_richness_across_videos),
    baseline_shannon = mean(shannon_across_videos),
    baseline_Ble = mean(Ble_across_videos),
    baseline_Cep = mean(Cep_across_videos),
    baseline_Col = mean(Col_across_videos),
    baseline_Eug = mean(Eug_across_videos),
    baseline_Eup = mean(Eup_across_videos),
    baseline_Lox = mean(Lox_across_videos),
    baseline_Pau = mean(Pau_across_videos),
    baseline_Pca = mean(Pca_across_videos),
    baseline_Spi = mean(Spi_across_videos),
    baseline_Spi_te = mean(Spi_te_across_videos),
    baseline_Tet = mean(Tet_across_videos),
    bioarea_per_volume_mean = mean(bioarea_per_volume_across_videos),
    bioarea_per_volume_sd = sd(bioarea_per_volume_across_videos),
    indiv_per_volume_mean = mean(indiv_per_volume_across_videos),
    indiv_per_volume_sd = sd(indiv_per_volume_across_videos),
    species_richness_mean = mean(species_richness_across_videos),
    species_richness_sd = sd(species_richness_across_videos),
    shannon_mean = mean(shannon_across_videos),
    shannon_sd = sd(shannon_across_videos),
    Ble_mean = mean(Ble_across_videos),
    Ble_sd = sd(Ble_across_videos),
    Cep_mean = mean(Cep_across_videos),
    Cep_sd = sd(Cep_across_videos),
    Col_mean = mean(Col_across_videos),
    Col_sd = sd(Col_across_videos),
    Eug_mean = mean(Eug_across_videos),
    Eug_sd = sd(Eug_across_videos),
    Eup_mean = mean(Eup_across_videos),
    Eup_sd = sd(Eup_across_videos),
    Lox_mean = mean(Lox_across_videos),
    Lox_sd = sd(Lox_across_videos),
    Pau_mean = mean(Pau_across_videos),
    Pau_sd = sd(Pau_across_videos),
    Pca_mean = mean(Pca_across_videos),
    Pca_sd = sd(Pca_across_videos),
    Spi_mean = mean(Spi_across_videos),
    Spi_sd = sd(Spi_across_videos),
    Spi_te_mean = mean(Spi_te_across_videos),
    Spi_te_sd = sd(Spi_te_across_videos),
    Tet_mean = mean(Tet_across_videos),
    Tet_sd = sd(Tet_across_videos)
  ) %>% #Initialise columns
  mutate(bioarea_per_volume_d = NA,
         bioarea_per_volume_d_upper = NA,
         bioarea_per_volume_d_lower = NA,
         bioarea_per_volume_lnRR = NA,
         indiv_per_volume_d = NA,
         indiv_per_volume_d_upper = NA,
         indiv_per_volume_d_lower = NA,
         indiv_per_volume_lnRR = NA,
         species_richness_d = NA,
         species_richness_d_upper = NA,
         species_richness_d_lower = NA,
         species_richness_lnRR = NA,
         shannon_d = NA,
         shannon_d_upper = NA,
         shannon_d_lower = NA,
         shannon_lnRR = NA,
         Ble_d = NA,
         Cep_d = NA,
         Col_d = NA,
         Eug_d = NA,
         Eup_d = NA,
         Lox_d = NA,
         Pau_d = NA,
         Pca_d = NA,
         Spi_d = NA,
         Spi_te_d = NA,
         Tet_d = NA,
         Ble_d_upper = NA,
         Ble_d_lower = NA,
         Ble_lnRR = NA,
         Cep_d_upper = NA,
         Cep_d_lower = NA,
         Cep_lnRR = NA,
         Col_d_upper = NA,
         Col_d_lower = NA,
         Col_lnRR = NA,
         Eug_d_upper = NA,
         Eug_d_lower = NA,
         Eug_lnRR = NA,
         Eup_d_upper = NA,
         Eup_d_lower = NA,
         Eup_lnRR = NA,
         Lox_d_upper = NA,
         Lox_d_lower = NA,
         Lox_lnRR = NA,
         Pau_d_upper = NA,
         Pau_d_lower = NA,
         Pau_lnRR = NA,
         Pca_d_upper = NA,
         Pca_d_lower = NA,
         Pca_lnRR = NA,
         Spi_d_upper = NA,
         Spi_d_lower = NA,
         Spi_lnRR = NA,
         Spi_te_d_upper = NA,
         Spi_te_d_lower = NA,
         Spi_te_lnRR = NA,
         Tet_d_upper = NA,
         Tet_d_lower = NA,
         Tet_lnRR = NA)
```

```{r}
treatments_and_controls = data.frame(
  treatment = c("S (S_S)", "S (S_L)", "L (L_L)", "L (S_L)"),
  control = c("S", "S", "L", "L")
)

n_of_treatments = nrow(treatments_and_controls)

row_n = 0
for (disturbance_input in c("low", "high")) {
  for (treatment_n in 1:n_of_treatments) {
    for (time_point_input in 0:7) {
      row_n = row_n + 1
      
      eco_metaeco_treatment = treatments_and_controls$treatment[treatment_n]
      
      treatment_row = ds_patches_averaged %>%
        filter(
          disturbance == disturbance_input,
          eco_metaeco_type == eco_metaeco_treatment,
          time_point == time_point_input
        )
      
      eco_metaeco_control = treatments_and_controls$control[treatment_n]
      
      control_row = ds_patches_averaged %>%
        filter(
          disturbance == disturbance_input,
          eco_metaeco_type == eco_metaeco_control,
          time_point == time_point_input
        )
      
      ### Bioarea density
      
      hedges_d_bioarea = calculate.hedges_d(
        treatment_row$bioarea_per_volume_mean,
        treatment_row$bioarea_per_volume_sd,
        treatment_row$sample_size,
        control_row$bioarea_per_volume_mean,
        control_row$bioarea_per_volume_sd,
        control_row$sample_size
      )
      
      ds_patches_averaged$bioarea_per_volume_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                 ds_patches_averaged$time_point == time_point_input &
                                                 ds_patches_averaged$disturbance == disturbance_input] = hedges_d_bioarea$d
      
      ds_patches_averaged$bioarea_per_volume_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                       ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_bioarea$upper_CI
      
      ds_patches_averaged$bioarea_per_volume_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                       ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_bioarea$lower_CI
      
      ds_patches_averaged$bioarea_per_volume_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                    ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$bioarea_per_volume_mean / control_row$bioarea_per_volume_mean)
      
      
      ### Individuals per volume
    
    hedges_d_indiv_per_volume = calculate.hedges_d(
      treatment_row$indiv_per_volume_mean,
      treatment_row$indiv_per_volume_sd,
      treatment_row$sample_size,
      control_row$indiv_per_volume_mean,
      control_row$indiv_per_volume_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$indiv_per_volume_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                             ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_indiv_per_volume$d
    
    ds_patches_averaged$indiv_per_volume_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_indiv_per_volume$lower_CI
    
    ds_patches_averaged$indiv_per_volume_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_indiv_per_volume$upper_CI
    
    ds_patches_averaged$indiv_per_volume_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$indiv_per_volume_mean / control_row$indiv_per_volume_mean)
    
    ### Species richness
    
    hedges_d_species_richness = calculate.hedges_d(
      treatment_row$species_richness_mean,
      treatment_row$species_richness_sd,
      treatment_row$sample_size,
      control_row$species_richness_mean,
      control_row$species_richness_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$species_richness_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                             ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_species_richness$d
    
    ds_patches_averaged$species_richness_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_species_richness$upper_CI
    
    ds_patches_averaged$species_richness_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_species_richness$lower_CI
    
    ds_patches_averaged$species_richness_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$species_richness_mean / control_row$species_richness_mean)
    
    ### Shannon Index
    
    hedges_d_shannon = calculate.hedges_d(
      treatment_row$shannon_mean,
      treatment_row$shannon_sd,
      treatment_row$sample_size,
      control_row$shannon_mean,
      control_row$shannon_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$shannon_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                             ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_shannon$d
    
    ds_patches_averaged$shannon_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_shannon$upper_CI
    
    ds_patches_averaged$shannon_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_shannon$lower_CI
    
    ds_patches_averaged$shannon_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$shannon_mean / control_row$shannon_mean)
    
    ### Ble
    
    hedges_d_Ble = calculate.hedges_d(
      treatment_row$Ble_mean,
      treatment_row$Ble_sd,
      treatment_row$sample_size,
      control_row$Ble_mean,
      control_row$Ble_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Ble_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Ble$d
    
    ds_patches_averaged$Ble_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Ble$lower_CI
    
    ds_patches_averaged$Ble_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Ble$upper_CI
    
    ds_patches_averaged$Ble_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Ble_mean / control_row$Ble_mean)
    
    ### Cep
    
    hedges_d_Cep = calculate.hedges_d(
      treatment_row$Cep_mean,
      treatment_row$Cep_sd,
      treatment_row$sample_size,
      control_row$Cep_mean,
      control_row$Cep_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Cep_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Cep$d
    
    ds_patches_averaged$Cep_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Cep$lower_CI
    
    ds_patches_averaged$Cep_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Cep$upper_CI
    
    ds_patches_averaged$Cep_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Cep_mean / control_row$Cep_mean)
    
    ### Col
    
    hedges_d_Col = calculate.hedges_d(
      treatment_row$Col_mean,
      treatment_row$Col_sd,
      treatment_row$sample_size,
      control_row$Col_mean,
      control_row$Col_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Col_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Col$d
    
    ds_patches_averaged$Col_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Col$lower_CI
    
    ds_patches_averaged$Col_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Col$upper_CI
    
    ds_patches_averaged$Col_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Col_mean / control_row$Col_mean)
    
    ### Eug
    
    hedges_d_Eug = calculate.hedges_d(
      treatment_row$Eug_mean,
      treatment_row$Eug_sd,
      treatment_row$sample_size,
      control_row$Eug_mean,
      control_row$Eug_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Eug_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Eug$d
    
    ds_patches_averaged$Eug_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Eug$lower_CI
    
    ds_patches_averaged$Eug_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Eug$upper_CI
    
    ds_patches_averaged$Eug_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Eug_mean / control_row$Eug_mean)
    
    ### Eup
    
    hedges_d_Eup = calculate.hedges_d(
      treatment_row$Eup_mean,
      treatment_row$Eup_sd,
      treatment_row$sample_size,
      control_row$Eup_mean,
      control_row$Eup_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Eup_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Eup$d
    
    ds_patches_averaged$Eup_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Eup$lower_CI
    
    ds_patches_averaged$Eup_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Eup$upper_CI
    
    ds_patches_averaged$Eup_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Eup_mean / control_row$Eup_mean)
    
    ### Lox
    
    hedges_d_Lox = calculate.hedges_d(
      treatment_row$Lox_mean,
      treatment_row$Lox_sd,
      treatment_row$sample_size,
      control_row$Lox_mean,
      control_row$Lox_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Lox_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Lox$d
    
    ds_patches_averaged$Lox_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Lox$lower_CI
    
    ds_patches_averaged$Lox_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Lox$upper_CI
    
    ds_patches_averaged$Lox_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Lox_mean / control_row$Lox_mean)
    
    ### Pau
    
    hedges_d_Pau = calculate.hedges_d(
      treatment_row$Pau_mean,
      treatment_row$Pau_sd,
      treatment_row$sample_size,
      control_row$Pau_mean,
      control_row$Pau_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Pau_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Pau$d
    
    ds_patches_averaged$Pau_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Pau$lower_CI
    
    ds_patches_averaged$Pau_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Pau$upper_CI
    
    ds_patches_averaged$Pau_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Pau_mean / control_row$Pau_mean)
    
    ### Pca
    
    hedges_d_Pca = calculate.hedges_d(
      treatment_row$Pca_mean,
      treatment_row$Pca_sd,
      treatment_row$sample_size,
      control_row$Pca_mean,
      control_row$Pca_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Pca_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Pca$d
    
    ds_patches_averaged$Pca_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Pca$lower_CI
    
    ds_patches_averaged$Pca_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Pca$upper_CI
    
    ds_patches_averaged$Pca_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Pca_mean / control_row$Pca_mean)
    
    ### Spi
    
    hedges_d_Spi = calculate.hedges_d(
      treatment_row$Spi_mean,
      treatment_row$Spi_sd,
      treatment_row$sample_size,
      control_row$Spi_mean,
      control_row$Spi_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Spi_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Spi$d
    
    ds_patches_averaged$Spi_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Spi$lower_CI
    
    ds_patches_averaged$Spi_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Spi$upper_CI
    
    ds_patches_averaged$Spi_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Spi_mean / control_row$Spi_mean)
    
    ### Spi te
    
    hedges_d_Spi_te = calculate.hedges_d(
      treatment_row$Spi_te_mean,
      treatment_row$Spi_te_sd,
      treatment_row$sample_size,
      control_row$Spi_te_mean,
      control_row$Spi_te_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Spi_te_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Spi_te$d
    
    ds_patches_averaged$Spi_te_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                         ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Spi_te$lower_CI
    
    ds_patches_averaged$Spi_te_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                         ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Spi_te$upper_CI
    
    ds_patches_averaged$Spi_te_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Spi_te_mean / control_row$Spi_te_mean)
    
    ### Tet
    
    hedges_d_Tet = calculate.hedges_d(
      treatment_row$Tet_mean,
      treatment_row$Tet_sd,
      treatment_row$sample_size,
      control_row$Tet_mean,
      control_row$Tet_sd,
      control_row$sample_size
    )
    
    ds_patches_averaged$Tet_d[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Tet$d
    
    ds_patches_averaged$Tet_d_lower[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Tet$lower_CI
    
    ds_patches_averaged$Tet_d_upper[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                      ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = hedges_d_Tet$upper_CI
    
    ds_patches_averaged$Tet_lnRR[ds_patches_averaged$eco_metaeco_type == eco_metaeco_treatment &
                                   ds_patches_averaged$time_point == time_point_input &
                                                       ds_patches_averaged$disturbance == disturbance_input] = ln(treatment_row$Tet_mean / control_row$Tet_mean)
    
    }
  }
}
```

```{r}
saveRDS(ds_patches_averaged, file = here("results", "ds_patches_averaged.RData"))
```

```{r ds_patches_averaged-datatable}
datatable(ds_patches_averaged,
          rownames = FALSE,
          options = list(scrollX = TRUE),
          filter = list(position = 'top', 
                        clear = FALSE))
```