---
title: "Data manipulation of body size data"
author: "Emanuele Giacomuzzo"
date: "2022-08-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r eval = FALSE}

#####IN PROGRESS#######

time_points_ds = NULL
for (time_point in first_time_point:last_time_point) {
  
  load(here("data", "morphology", paste0("t",time_point,".RData")))
  
  time_points_ds[[time_point+1]] = morph_mvt
  
  #Initially, at time point 0, 12 videos were captured of the large bottle from which the community was assembled. In order to analyze the data, each of these 12 videos are assigned to each culture. 
  if(time_point == 0) {
    
    original_n_rows = nrow(time_points_ds[[time_point+1]])
    ID_vector = rep(1:cultures_n, 
                    each = original_n_rows)
    time_points_ds[[time_point+1]] = time_points_ds[[time_point+1]] %>%
      slice(rep(1:n(), 
                cultures_n)) %>%
      mutate(culture_ID = ID_vector)
  }
  
  time_points_ds[[time_point+1]] = time_points_ds[[time_point+1]] %>%
    select(file,
           culture_ID,
           bioarea_per_volume,
           indiv_per_volume,
           protist_species[1]:protist_species[n_protist_species]) %>%
    mutate(time_point = time_point,
           day = sampling_days[time_point + 1])
  
}

```


```{r ds_individuals-import-time-points}
load(here("data", "morphology", "t0.RData"));t0 = morph_mvt; rm(morph_mvt)
load(here("data", "morphology", "t1.RData"));t1 = morph_mvt; rm(morph_mvt)
load(here("data", "morphology", "t2.RData"));t2 = morph_mvt; rm(morph_mvt)
load(here("data", "morphology", "t3.RData"));t3 = morph_mvt; rm(morph_mvt)
load(here("data", "morphology", "t4.RData"));t4 = morph_mvt; rm(morph_mvt)
load(here("data", "morphology", "t5.RData"));t5 = morph_mvt; rm(morph_mvt)
load(here("data", "morphology", "t6.RData"));t6 = morph_mvt; rm(morph_mvt)
load(here("data", "morphology", "t7.RData"));t7 = morph_mvt; rm(morph_mvt)
```

```{r ds_individuals-tidy-time-points}
t0$time = NA
t1$time = NA

t0$replicate_video[t0$file == "sample_00001"] = 1
t0$replicate_video[t0$file == "sample_00002"] = 2
t0$replicate_video[t0$file == "sample_00003"] = 3
t0$replicate_video[t0$file == "sample_00004"] = 4
t0$replicate_video[t0$file == "sample_00005"] = 5
t0$replicate_video[t0$file == "sample_00006"] = 6
t0$replicate_video[t0$file == "sample_00007"] = 7
t0$replicate_video[t0$file == "sample_00008"] = 8
t0$replicate_video[t0$file == "sample_00009"] = 9
t0$replicate_video[t0$file == "sample_00010"] = 10
t0$replicate_video[t0$file == "sample_00011"] = 11
t0$replicate_video[t0$file == "sample_00012"] = 12
t1$replicate_video = 1 #In t1 I took only 1 video/culture
t2$replicate_video = 1 #In t2 I took only 1 video/culture
t3$replicate_video = 1 #In t3 I took only 1 video/culture
t4$replicate_video = 1 #In t4 I took only 1 video/culture
t5$replicate_video = 1 #In t5 I took only 1 video/culture
t6 = t6 %>% rename(replicate_video = replicate)
t7 = t7 %>% rename(replicate_video = replicate)
```

```{r ds-body-size-join-time-points}
cultures_n = max(culture_info$culture_ID)
original_t0_rows = nrow(t0)
ID_vector = rep(1:cultures_n, each = original_t0_rows)
t0 = t0 %>%
  slice(rep(1:n(), cultures_n)) %>%
  mutate(culture_ID = ID_vector)

t0 = merge(culture_info, t0, by="culture_ID")
t1 = merge(culture_info, t1, by="culture_ID")
t2 = merge(culture_info, t2, by="culture_ID")
t3 = merge(culture_info, t3, by="culture_ID")
t4 = merge(culture_info, t4, by="culture_ID")
t5 = merge(culture_info, t5, by="culture_ID")
t6 = merge(culture_info, t6, by="culture_ID")
t7 = merge(culture_info, t7, by="culture_ID")
ds_individuals = rbind(t0, t1, t2, t3, t4, t5, t6, t7)
rm(t0, t1, t2, t3, t4, t5, t6, t7)
```

```{r ds_individuals-tidy-columns}
ds_individuals$day = ds_individuals$time_point
ds_individuals$day[ds_individuals$day=="t0"] = "0"
ds_individuals$day[ds_individuals$day=="t1"] = "4"
ds_individuals$day[ds_individuals$day=="t2"] = "8"
ds_individuals$day[ds_individuals$day=="t3"] = "12"
ds_individuals$day[ds_individuals$day=="t4"] = "16"
ds_individuals$day[ds_individuals$day=="t5"] = "20"
ds_individuals$day[ds_individuals$day=="t6"] = "24"
ds_individuals$day[ds_individuals$day=="t7"] = "28"
ds_individuals$day = as.numeric(ds_individuals$day)

ds_individuals$time_point[ds_individuals$time_point=="t0"] = 0
ds_individuals$time_point[ds_individuals$time_point=="t1"] = 1
ds_individuals$time_point[ds_individuals$time_point=="t2"] = 2
ds_individuals$time_point[ds_individuals$time_point=="t3"] = 3
ds_individuals$time_point[ds_individuals$time_point=="t4"] = 4
ds_individuals$time_point[ds_individuals$time_point=="t5"] = 5
ds_individuals$time_point[ds_individuals$time_point=="t6"] = 6
ds_individuals$time_point[ds_individuals$time_point=="t7"] = 7
ds_individuals$time_point = as.character(ds_individuals$time_point)

#Select useful columns
ds_individuals = ds_individuals %>% 
  rename(patch_type = eco_metaeco_type) %>%
  select(culture_ID, 
         patch_size, 
         patch_size_volume,
         disturbance, 
         metaecosystem_type, 
         mean_area, 
         replicate_video, 
         time_point,
         day, 
         metaecosystem, 
         system_nr, 
         patch_type) %>%
  rename(patch_size_ml = patch_size_volume)
```

```{r}
#Rename the patches

ds_individuals$patch_type[ds_individuals$patch_type == "S"] = "Small isolated"
ds_individuals$patch_type[ds_individuals$patch_type == "S (S_S)"] = "Small connected to small"
ds_individuals$patch_type[ds_individuals$patch_type == "S (S_L)"] = "Small connected to large"
ds_individuals$patch_type[ds_individuals$patch_type == "M"] = "Medium isolated"
ds_individuals$patch_type[ds_individuals$patch_type == "M (M_M)"] = "Medium connected to medium"
ds_individuals$patch_type[ds_individuals$patch_type == "L"] = "Large isolated"
ds_individuals$patch_type[ds_individuals$patch_type == "L (L_L)"] = "Large connected to large"
ds_individuals$patch_type[ds_individuals$patch_type == "L (S_L)"] = "Large connected to small"

#Reorder the patches

ds_individuals = ds_individuals %>%
  mutate(patch_type = factor(
    patch_type,
    levels = c(
      "Small isolated",
      "Small connected to small",
      "Small connected to large",
      "Medium isolated",
      "Medium connected to medium",
      "Large isolated",
      "Large connected to large",
      "Large connected to small"
    )
  ))
```