---
title: "Find combination sets for isolated SL / MM systems"
output: html_document
date: "2023-05-19"
editor_options: 
  chunk_output_type: console
---

```{r isolated-SL-systems-combination-sets-create}

#Create combination sets for SL isolated.

# Each set contains each patch only one time. I keep the small patches on the same order and perform permutations on large patches.

disturbance_nr = 0
SL_isolated_sys_sets <- vector("list",
                               length(disturbance_levels))

for (disturbance_input in disturbance_levels) {
  
  disturbance_nr = disturbance_nr + 1
  
  ID_small_patches = ds_patches %>%
    filter(disturbance == disturbance_input,
           patch_type == "Small isolated") %>%
    pull(culture_ID) %>%
    unique()
  
  ID_large_patches = ds_patches %>%
    filter(disturbance == disturbance_input,
           patch_type == "Large isolated") %>%
    pull(culture_ID) %>%
    unique()
  
  #Force small and large patches vectors to have the same length
  length_difference <- length(ID_small_patches) - length(ID_large_patches)
  if (length_difference > 0) {
    
    ID_large_patches = c(ID_large_patches,
                       rep("Patch taken off",
                           times = abs(length(ID_small_patches) - 
                                       length(ID_large_patches))))
    
    } else if (length_difference < 0) {
      
    ID_small_patches = c(ID_small_patches,
                         rep("Patch taken off",
                             times = abs(length(ID_large_patches) - 
                                         length(ID_small_patches))))
    }

  # Create dataframe
  permutations_large = permn(ID_large_patches)
  
  SL_isolated_sys_sets[[disturbance_nr]] = data.frame(
    disturbance = disturbance_input,
    metaecosystem_type = "Small-Large isolated",
    ID_first_patch = rep(ID_small_patches, 
                         times = length(permutations_large)),
    ID_second_patch = unlist(permutations_large),
    connection = "isolated",
    set = rep(1 : length(permutations_large), 
              each = length(ID_small_patches)))
  
  expect_equal(nrow(SL_isolated_sys_sets[[disturbance_nr]]),
               length(ID_small_patches) * length(permutations_large))
  
  SL_isolated_sys_sets[[disturbance_nr]] = SL_isolated_sys_sets[[disturbance_nr]] %>%
    filter(!ID_first_patch == "Patch taken off",
           !ID_second_patch == "Patch taken off") %>%
    mutate(ID_first_patch = as.double(ID_first_patch),
           ID_second_patch = as.double(ID_second_patch)) %>%
    full_join(patch_combinations %>%
                filter(disturbance == disturbance_input, 
                       metaecosystem_type == "Small-Large isolated"))

}

SL_isolated_sys_sets_before_binding = SL_isolated_sys_sets
SL_isolated_sys_sets = SL_isolated_sys_sets %>%
  bind_rows()
```

```{r}
expect_equal(nrow(SL_isolated_sys_sets),
             nrow(SL_isolated_sys_sets_before_binding[[1]]) + nrow(SL_isolated_sys_sets_before_binding[[2]]))

expect_equal(length(SL_isolated_sys_sets %>% 
                      pull(system_nr) %>% 
                      unique()),
             length(patch_combinations %>%
                      filter(metaecosystem_type == "Small-Large isolated") %>%
                      pull(system_nr) %>%
                      unique()))
```

```{r isolated-MM-systems-combination-sets-create}

#WORK HERE

#Create combination sets for MM isolated where each sets contains each patch only one time. To find all combinations where all the patches are included, but only one at the time, I ... 

disturbance_nr = 0
MM_isolated_sys_sets <- vector("list", 
                               length(disturbance_levels))

for (disturbance_input in disturbance_levels) {
  
  disturbance_nr = disturbance_nr + 1
  
  ID_medium_patches = ds_patches %>%
    filter(disturbance == disturbance_input,
           patch_type == "Medium isolated") %>%
    pull(culture_ID) %>%
    unique()
  
  MM_isolated_sys_combos = combn(ID_medium_patches, 
                          2) %>%
                    t()
  
  MM_isolated_sys_sets[[disturbance_nr]] = matrix(nrow = 10 ^ 4,
                                                  ncol = 4)
  
  matrix_row = 0
  
  #Trying something new
  for (first_system_i in 1:nrow(MM_isolated_sys_combos)) {
    for (second_system_i in 1:nrow(MM_isolated_sys_combos)) {
      if(length(intersect(MM_isolated_sys_combos[first_system_i,], MM_isolated_sys_combos[second_system_i,])) > 0){
        
        matrix_row = matrix_row + 1
        
        MM_isolated_sys_sets[[disturbance_nr]][matrix_row,] = c(MM_isolated_sys_combos[first_system_i,],
                                                              MM_isolated_sys_combos[second_system_i,])
      }
    }
  }
  
  first_method = MM_isolated_sys_sets[[disturbance_nr]]
  
  


  
  matrix_row = 0
  #Good code already working
  for (first_system_n in 1:nrow(MM_isolated_sys_combos)) {
    #Find culture IDs of the first system
    first_system = MM_isolated_sys_combos[first_system_n, ]
    
    for (second_system_n in 1:nrow(MM_isolated_sys_combos)) {
      #Find culture IDs of the second system
      second_system = MM_isolated_sys_combos[second_system_n, ]
      
      shared_elements_first_n_second_system = intersect(first_system,
                                                        second_system)
      
      if (length(shared_elements_first_n_second_system) == 0) {
        matrix_row = matrix_row + 1
        
        #Make first and second system into a set
        MM_isolated_sys_sets[[disturbance_nr]][matrix_row,] = c(first_system,
                                                                second_system)
        
      }
    }
  }
  
  second_method = MM_isolated_sys_sets[[disturbance_nr]]
  
  first_method == second_method
  
  #Tidy the dataset with all the patch combinations
  MM_isolated_sys_sets[[disturbance_nr]] = MM_isolated_sys_sets[[disturbance_nr]] %>%
    as.data.frame() %>%
    drop_na()
  
  expect_equal(MM_isolated_sys_sets[[disturbance_nr]] %>% 
                 filter(V1 == V2 | V1 == V3 | V1 == V4 | V2 == V3 | V2 == V4 | V3 == V4) %>% 
                 nrow(),
               0)
  
  #Reorder the dataset with all the patch combinations
  MM_isolated_sys_sets_reordered = data.frame(
    ID_first_patch = NA,
    ID_second_patch = NA,
    set = NA
  )
  
  n_sets = nrow(MM_isolated_sys_sets[[disturbance_nr]])
  
  for (set_input in 1:n_sets) {
    MM_isolated_sys_sets_reordered = MM_isolated_sys_sets_reordered %>%
      add_row(
        ID_first_patch = MM_isolated_sys_sets[[disturbance_nr]][set_input, 1],
        ID_second_patch = MM_isolated_sys_sets[[disturbance_nr]][set_input, 2],
        set = set_input
      ) %>%
      add_row(
        ID_first_patch = MM_isolated_sys_sets[[disturbance_nr]][set_input, 3],
        ID_second_patch = MM_isolated_sys_sets[[disturbance_nr]][set_input, 4],
        set = set_input
      )
  }
  
  #Add to a list
  MM_isolated_sys_sets[[disturbance_nr]] = MM_isolated_sys_sets_reordered %>%
    drop_na() %>%
    mutate(
      disturbance = disturbance_input,
      metaecosystem_type = "Medium-Medium isolated",
      connection = "isolated"
    )
  
  #Add system nr
  ID_combinations_MM_isolated = patch_combinations %>%
    filter(disturbance == disturbance_input,
           metaecosystem_type == "Medium-Medium isolated")
  
  MM_isolated_sys_sets[[disturbance_nr]] = full_join(MM_isolated_sys_sets[[disturbance_nr]],
                                                     ID_combinations_MM_isolated)
  
}

#Bind all sets of MM isolated
MM_isolated_sys_sets = MM_isolated_sys_sets %>%
  bind_rows()
```

```{r}
expect_equal(length(MM_isolated_sys_sets %>%
                      pull(system_nr) %>%
                      unique()),
             length(patch_combinations %>%
                      filter(metaecosystem_type == "Medium-Medium isolated") %>%
                      pull(system_nr) %>%
                      unique()))
```


```{r isolated-systems-combination-sets-join}

#Bind SL and MM isolated systems

isolated_combinations_sets = rbind(SL_isolated_sys_sets, 
                                   MM_isolated_sys_sets) %>%
  select(disturbance,
         metaecosystem_type,
         connection,
         set,
         system_nr,
         ID_first_patch,
         ID_second_patch)
```
