---
title: "Find combinations of patches"
output: html_document
date: "2023-05-02"
editor_options: 
  chunk_output_type: console
---

### Meta-ecosystems (`ds_metaecosystems`)

In this dataset (`ds_metaecosystems`) each row represents a meta-ecosystem or a two-patch isolated system at a time point.

```{r isolated-IDs-find}

#Find combinations of patches in isolated two-patch systems.

ID_isolated_S_low = ds_patches %>%
  filter(patch_type == "Small isolated",
         disturbance == "low") %>%
  pull(culture_ID) %>%
  unique()

ID_isolated_L_low = ds_patches %>%
  filter(patch_type == "Large isolated",
         disturbance == "low") %>%
  pull(culture_ID) %>%
  unique()

ID_isolated_S_high = ds_patches %>%
  filter(patch_type == "Small isolated",
         disturbance == "high") %>%
  pull(culture_ID) %>%
  unique()

ID_isolated_L_high = ds_patches %>%
  filter(patch_type == "Large isolated",
         disturbance == "high") %>%
  pull(culture_ID) %>%
  unique()

ID_isolated_M_low = ds_patches %>%
  filter(patch_type == "Medium isolated",
         disturbance == "low") %>%
  pull(culture_ID) %>%
  unique()

ID_isolated_M_high = ds_patches %>%
  filter(patch_type == "Medium isolated",
         disturbance == "high") %>%
  pull(culture_ID) %>%
  unique()

combinations_S_and_L_low = crossing(ID_isolated_S_low,
                                    ID_isolated_L_low) %>%
                            mutate(disturbance = "low",
                                   metaecosystem_type = "Small-Large isolated") %>%
                            rename(ID_first_patch = ID_isolated_S_low,
                                   ID_second_patch = ID_isolated_L_low) %>%
                            select(disturbance,
                                   metaecosystem_type,
                                   ID_first_patch,
                                   ID_second_patch)

expect_equal(nrow(combinations_S_and_L_low),
             length(ID_isolated_S_low) * length(ID_isolated_L_low))

combinations_S_and_L_high = crossing(ID_isolated_S_high,
                                     ID_isolated_L_high) %>%
                            mutate(disturbance = "high",
                                   metaecosystem_type = "Small-Large isolated") %>%
                            rename(ID_first_patch = ID_isolated_S_high,
                                   ID_second_patch = ID_isolated_L_high) %>%
                            select(disturbance,
                                   metaecosystem_type,
                                   ID_first_patch,
                                   ID_second_patch)

expect_equal(nrow(combinations_S_and_L_high),
             length(ID_isolated_S_high) * length(ID_isolated_L_high))

combinations_M_and_M_low = combinat::combn(ID_isolated_M_low,
                                   m = 2) %>%
                            t() %>%
                            as.data.frame() %>%
                            rename(ID_first_patch = V1,
                                   ID_second_patch = V2) %>%
                            mutate(disturbance = "low",
                                   metaecosystem_type = "Medium-Medium isolated") %>%
                            select(disturbance,
                                   metaecosystem_type,
                                   ID_first_patch,
                                   ID_second_patch)

expect_equal(nrow(combinations_M_and_M_low),
             sum(seq(length(ID_isolated_M_low) - 1)))

combinations_M_and_M_high = combinat::combn(ID_isolated_M_high,
                                   m = 2) %>%
                            t() %>%
                            as.data.frame() %>%
                            rename(ID_first_patch = V1,
                                   ID_second_patch = V2) %>%
                            mutate(disturbance = "high",
                                   metaecosystem_type = "Medium-Medium isolated") %>%
                            select(disturbance,
                                   metaecosystem_type,
                                   ID_first_patch,
                                   ID_second_patch)

expect_equal(nrow(combinations_M_and_M_high),
             sum(seq(length(ID_isolated_M_high) - 1)))

combinations_isolated_systems = rbind(combinations_S_and_L_low,
                                      combinations_S_and_L_high,
                                      combinations_M_and_M_low,
                                      combinations_M_and_M_high) %>%
  mutate(system_nr = 1001:(1000 + nrow(.))) %>%
  select(system_nr,
         disturbance,
         metaecosystem_type,
         ID_first_patch,
         ID_second_patch)
```

```{r meta-ecosystems-create}

#Find combinations of patches in meta-ecosystems.

combinations_metaecos = ds_patches %>%
  filter(time_point == 0,
         metaecosystem == "yes") %>%
  select(system_nr,
         disturbance,
         metaecosystem_type,
         culture_ID) %>%
  group_by(system_nr,
           disturbance,
           metaecosystem_type) %>%
  summarise(ID_first_patch = (mean(culture_ID) - 0.5),
            ID_second_patch = (mean(culture_ID) + 0.5)) %>%
  as.data.frame()
```

```{r isolated-and-metaeco-system-join}

#Bind isolated systems and meta-ecosystems

combinations_isolated_n_metaecos = rbind(combinations_isolated_systems,
                                         combinations_metaecos) %>%
  mutate(connection = ifelse(metaecosystem_type %in% c("Medium-Medium isolated",
                                                       "Small-Large isolated"),
                             yes = "isolated",
                             no = "connected"),
         patches_combined = paste0(ID_first_patch, "|", ID_second_patch))

n_patches_combinations = nrow(combinations_isolated_n_metaecos)

expect_equal(nrow(combinations_isolated_n_metaecos), 
             nrow(combinations_isolated_systems) + nrow(combinations_metaecos))
```