---
title: "Data Patches Averaged"
output: html_document
date: "2022-11-22"
editor_options: 
  chunk_output_type: console
---

```{r}

#Calculate the mean & sd of response variables for each treatment at each time point
ds_patches_effect_size <- ds_patches %>%
  group_by(across(all_of(columns_patches))) %>%
  summarise(across(all_of(variables_patches),
                   list(mean = mean, sd = sd)),
            sample_size = n())

#Initialise columns
for (var in variables_patches) {
  ds_patches_effect_size <- ds_patches_effect_size %>%
    mutate(
      !!paste0(var, "_d") := NA,
      !!paste0(var, "_d_upper") := NA,
      !!paste0(var, "_d_lower") := NA
    )
}
```

```{r}

#Calculate the effect size (Hedge's d)
row_n = 0
for (disturbance_regime in c("low", "high")) {
  for (treatment_n in 1:n_of_treatments) {
    for (time_point_input in first_time_point:last_time_point) {
      row_n = row_n + 1
      
      treatment = treatments_and_controls$treatment[treatment_n]
      
      treatment_row = ds_patches_effect_size %>%
        filter(
          disturbance == disturbance_regime,
          patch_type == treatment,
          time_point == time_point_input
        )
      
      control = treatments_and_controls$control[treatment_n]
      
      control_row = ds_patches_effect_size %>%
        filter(
          disturbance == disturbance_regime,
          patch_type == control,
          time_point == time_point_input
        )
      
      ### Bioarea density
      
      hedges_d_bioarea = calculate.hedges_d(
        treatment_row$bioarea_µm2_per_ml_mean,
        treatment_row$bioarea_µm2_per_ml_sd,
        treatment_row$sample_size,
        control_row$bioarea_µm2_per_ml_mean,
        control_row$bioarea_µm2_per_ml_sd,
        control_row$sample_size
      )
      
      ds_patches_effect_size$bioarea_µm2_per_ml_d[
        ds_patches_effect_size$patch_type == treatment &
        ds_patches_effect_size$time_point == time_point_input &
        ds_patches_effect_size$disturbance == disturbance_regime] = 
        hedges_d_bioarea$d
      
      ds_patches_effect_size$bioarea_µm2_per_ml_d_upper[
        ds_patches_effect_size$patch_type == treatment &
        ds_patches_effect_size$time_point == time_point_input &
        ds_patches_effect_size$disturbance == disturbance_regime] = 
        hedges_d_bioarea$upper_CI
      
      ds_patches_effect_size$bioarea_µm2_per_ml_d_lower[
        ds_patches_effect_size$patch_type == treatment &
        ds_patches_effect_size$time_point == time_point_input &
        ds_patches_effect_size$disturbance == disturbance_regime] = 
        hedges_d_bioarea$lower_CI
      
      ### Individuals per volume
    
    hedges_d_indiv_per_ml = calculate.hedges_d(
      treatment_row$indiv_per_ml_mean,
      treatment_row$indiv_per_ml_sd,
      treatment_row$sample_size,
      control_row$indiv_per_ml_mean,
      control_row$indiv_per_ml_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$indiv_per_ml_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_indiv_per_ml$d
    
    ds_patches_effect_size$indiv_per_ml_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_indiv_per_ml$lower_CI
    
    ds_patches_effect_size$indiv_per_ml_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_indiv_per_ml$upper_CI

    
    ### Species richness
    
    hedges_d_species_richness = calculate.hedges_d(
      treatment_row$species_richness_mean,
      treatment_row$species_richness_sd,
      treatment_row$sample_size,
      control_row$species_richness_mean,
      control_row$species_richness_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$species_richness_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_species_richness$d
    
    ds_patches_effect_size$species_richness_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_species_richness$upper_CI
    
    ds_patches_effect_size$species_richness_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_species_richness$lower_CI
    
    ### Evenness
    
    hedges_d_evenness_pielou = calculate.hedges_d(
      treatment_row$evenness_pielou_mean,
      treatment_row$evenness_pielou_sd,
      treatment_row$sample_size,
      control_row$evenness_pielou_mean,
      control_row$evenness_pielou_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$evenness_pielou_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_evenness_pielou$d
    
    ds_patches_effect_size$evenness_pielou_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_evenness_pielou$upper_CI
    
    ds_patches_effect_size$evenness_pielou_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_evenness_pielou$lower_CI
    
    ### Shannon Index
    
    hedges_d_shannon = calculate.hedges_d(
      treatment_row$shannon_mean,
      treatment_row$shannon_sd,
      treatment_row$sample_size,
      control_row$shannon_mean,
      control_row$shannon_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$shannon_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_shannon$d
    
    ds_patches_effect_size$shannon_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_shannon$upper_CI
    
    ds_patches_effect_size$shannon_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_shannon$lower_CI
    
    ### Ble
    
    hedges_d_Ble = calculate.hedges_d(
      treatment_row$Ble_mean,
      treatment_row$Ble_sd,
      treatment_row$sample_size,
      control_row$Ble_mean,
      control_row$Ble_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Ble_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Ble$d
    
    ds_patches_effect_size$Ble_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Ble$lower_CI
    
    ds_patches_effect_size$Ble_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Ble$upper_CI
    
    ### Cep
    
    hedges_d_Cep = calculate.hedges_d(
      treatment_row$Cep_mean,
      treatment_row$Cep_sd,
      treatment_row$sample_size,
      control_row$Cep_mean,
      control_row$Cep_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Cep_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Cep$d
    
    ds_patches_effect_size$Cep_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Cep$lower_CI
    
    ds_patches_effect_size$Cep_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Cep$upper_CI
    
    ### Col
    
    hedges_d_Col = calculate.hedges_d(
      treatment_row$Col_mean,
      treatment_row$Col_sd,
      treatment_row$sample_size,
      control_row$Col_mean,
      control_row$Col_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Col_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Col$d
    
    ds_patches_effect_size$Col_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Col$lower_CI
    
    ds_patches_effect_size$Col_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Col$upper_CI
    
    ### Eug
    
    hedges_d_Eug = calculate.hedges_d(
      treatment_row$Eug_mean,
      treatment_row$Eug_sd,
      treatment_row$sample_size,
      control_row$Eug_mean,
      control_row$Eug_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Eug_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eug$d
    
    ds_patches_effect_size$Eug_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eug$lower_CI
    
    ds_patches_effect_size$Eug_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eug$upper_CI
    
    ### Eup
    
    hedges_d_Eup = calculate.hedges_d(
      treatment_row$Eup_mean,
      treatment_row$Eup_sd,
      treatment_row$sample_size,
      control_row$Eup_mean,
      control_row$Eup_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Eup_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eup$d
    
    ds_patches_effect_size$Eup_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eup$lower_CI
    
    ds_patches_effect_size$Eup_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eup$upper_CI
    
    ### Lox
    
    hedges_d_Lox = calculate.hedges_d(
      treatment_row$Lox_mean,
      treatment_row$Lox_sd,
      treatment_row$sample_size,
      control_row$Lox_mean,
      control_row$Lox_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Lox_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Lox$d
    
    ds_patches_effect_size$Lox_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Lox$lower_CI
    
    ds_patches_effect_size$Lox_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Lox$upper_CI
    
    ### Pau
    
    hedges_d_Pau = calculate.hedges_d(
      treatment_row$Pau_mean,
      treatment_row$Pau_sd,
      treatment_row$sample_size,
      control_row$Pau_mean,
      control_row$Pau_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Pau_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pau$d
    
    ds_patches_effect_size$Pau_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pau$lower_CI
    
    ds_patches_effect_size$Pau_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pau$upper_CI
    
    ### Pca
    
    hedges_d_Pca = calculate.hedges_d(
      treatment_row$Pca_mean,
      treatment_row$Pca_sd,
      treatment_row$sample_size,
      control_row$Pca_mean,
      control_row$Pca_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Pca_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pca$d
    
    ds_patches_effect_size$Pca_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pca$lower_CI
    
    ds_patches_effect_size$Pca_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pca$upper_CI
    
    ### Spi
    
    hedges_d_Spi = calculate.hedges_d(
      treatment_row$Spi_mean,
      treatment_row$Spi_sd,
      treatment_row$sample_size,
      control_row$Spi_mean,
      control_row$Spi_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Spi_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi$d
    
    ds_patches_effect_size$Spi_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi$lower_CI
    
    ds_patches_effect_size$Spi_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi$upper_CI
    
    ### Spi te
    
    hedges_d_Spi_te = calculate.hedges_d(
      treatment_row$Spi_te_mean,
      treatment_row$Spi_te_sd,
      treatment_row$sample_size,
      control_row$Spi_te_mean,
      control_row$Spi_te_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Spi_te_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_te$d
    
    ds_patches_effect_size$Spi_te_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_te$lower_CI
    
    ds_patches_effect_size$Spi_te_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_te$upper_CI
    
    ### Tet
    
    hedges_d_Tet = calculate.hedges_d(
      treatment_row$Tet_mean,
      treatment_row$Tet_sd,
      treatment_row$sample_size,
      control_row$Tet_mean,
      control_row$Tet_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Tet_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Tet$d
    
    ds_patches_effect_size$Tet_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Tet$lower_CI
    
    ds_patches_effect_size$Tet_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Tet$upper_CI
    
    ### Ble dominance
    
    hedges_d_Ble_dominance = calculate.hedges_d(
      treatment_row$Ble_dominance_mean,
      treatment_row$Ble_dominance_sd,
      treatment_row$sample_size,
      control_row$Ble_dominance_mean,
      control_row$Ble_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Ble_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Ble_dominance$d
    
    ds_patches_effect_size$Ble_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Ble_dominance$lower_CI
    
    ds_patches_effect_size$Ble_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Ble_dominance$upper_CI
    
    ### Cep dominance
    
    hedges_d_Cep_dominance = calculate.hedges_d(
      treatment_row$Cep_dominance_mean,
      treatment_row$Cep_dominance_sd,
      treatment_row$sample_size,
      control_row$Cep_dominance_mean,
      control_row$Cep_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Cep_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Cep_dominance$d
    
    ds_patches_effect_size$Cep_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Cep_dominance$lower_CI
    
    ds_patches_effect_size$Cep_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Cep_dominance$upper_CI
    
    ### Col dominance
    
    hedges_d_Col_dominance = calculate.hedges_d(
      treatment_row$Col_dominance_mean,
      treatment_row$Col_dominance_sd,
      treatment_row$sample_size,
      control_row$Col_dominance_mean,
      control_row$Col_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Col_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Col_dominance$d
    
    ds_patches_effect_size$Col_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Col_dominance$lower_CI
    
    ds_patches_effect_size$Col_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Col_dominance$upper_CI
    
    ### Eug dominance
    
    hedges_d_Eug_dominance = calculate.hedges_d(
      treatment_row$Eug_dominance_mean,
      treatment_row$Eug_dominance_sd,
      treatment_row$sample_size,
      control_row$Eug_dominance_mean,
      control_row$Eug_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Eug_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eug_dominance$d
    
    ds_patches_effect_size$Eug_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eug_dominance$lower_CI
    
    ds_patches_effect_size$Eug_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eug_dominance$upper_CI
    
    ### Eup dominance
    
    hedges_d_Eup_dominance = calculate.hedges_d(
      treatment_row$Eup_dominance_mean,
      treatment_row$Eup_dominance_sd,
      treatment_row$sample_size,
      control_row$Eup_dominance_mean,
      control_row$Eup_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Eup_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eup_dominance$d
    
    ds_patches_effect_size$Eup_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eup_dominance$lower_CI
    
    ds_patches_effect_size$Eup_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Eup_dominance$upper_CI
    
    ### Lox dominance
    
    hedges_d_Lox_dominance = calculate.hedges_d(
      treatment_row$Lox_dominance_mean,
      treatment_row$Lox_dominance_sd,
      treatment_row$sample_size,
      control_row$Lox_dominance_mean,
      control_row$Lox_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Lox_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Lox_dominance$d
    
    ds_patches_effect_size$Lox_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Lox_dominance$lower_CI
    
    ds_patches_effect_size$Lox_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Lox_dominance$upper_CI
    
    ### Pau dominance
    
    hedges_d_Pau_dominance = calculate.hedges_d(
      treatment_row$Pau_dominance_mean,
      treatment_row$Pau_dominance_sd,
      treatment_row$sample_size,
      control_row$Pau_dominance_mean,
      control_row$Pau_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Pau_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pau_dominance$d
    
    ds_patches_effect_size$Pau_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pau_dominance$lower_CI
    
    ds_patches_effect_size$Pau_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pau_dominance$upper_CI
    
    ### Pca dominance
    
    hedges_d_Pca_dominance = calculate.hedges_d(
      treatment_row$Pca_dominance_mean,
      treatment_row$Pca_dominance_sd,
      treatment_row$sample_size,
      control_row$Pca_dominance_mean,
      control_row$Pca_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Pca_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pca_dominance$d
    
    ds_patches_effect_size$Pca_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pca_dominance$lower_CI
    
    ds_patches_effect_size$Pca_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Pca_dominance$upper_CI

    ### Spi dominance
    
    hedges_d_Spi_dominance = calculate.hedges_d(
      treatment_row$Spi_dominance_mean,
      treatment_row$Spi_dominance_sd,
      treatment_row$sample_size,
      control_row$Spi_dominance_mean,
      control_row$Spi_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Spi_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_dominance$d
    
    ds_patches_effect_size$Spi_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_dominance$lower_CI
    
    ds_patches_effect_size$Spi_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_dominance$upper_CI
    
    ### Spi te dominance
    
    hedges_d_Spi_te_dominance = calculate.hedges_d(
      treatment_row$Spi_te_dominance_mean,
      treatment_row$Spi_te_dominance_sd,
      treatment_row$sample_size,
      control_row$Spi_te_dominance_mean,
      control_row$Spi_te_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Spi_te_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_te_dominance$d
    
    ds_patches_effect_size$Spi_te_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_te_dominance$lower_CI
    
    ds_patches_effect_size$Spi_te_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Spi_te_dominance$upper_CI
    
    ### Tet dominance
    
    hedges_d_Tet_dominance = calculate.hedges_d(
      treatment_row$Tet_dominance_mean,
      treatment_row$Tet_dominance_sd,
      treatment_row$sample_size,
      control_row$Tet_dominance_mean,
      control_row$Tet_dominance_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$Tet_dominance_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Tet_dominance$d
    
    ds_patches_effect_size$Tet_dominance_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Tet_dominance$lower_CI
    
    ds_patches_effect_size$Tet_dominance_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_Tet_dominance$upper_CI
    
    ### Beta diversity from previous time
    
    hedges_d_beta_diversity_from_previous_time = calculate.hedges_d(
      treatment_row$beta_diversity_from_previous_time_mean,
      treatment_row$beta_diversity_from_previous_time_sd,
      treatment_row$sample_size,
      control_row$beta_diversity_from_previous_time_mean,
      control_row$beta_diversity_from_previous_time_sd,
      control_row$sample_size
    )
    
    ds_patches_effect_size$beta_diversity_from_previous_time_d[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_beta_diversity_from_previous_time$d
    
    ds_patches_effect_size$beta_diversity_from_previous_time_d_lower[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_beta_diversity_from_previous_time$lower_CI
    
    ds_patches_effect_size$beta_diversity_from_previous_time_d_upper[
      ds_patches_effect_size$patch_type == treatment &
      ds_patches_effect_size$time_point == time_point_input &
      ds_patches_effect_size$disturbance == disturbance_regime] = 
      hedges_d_beta_diversity_from_previous_time$upper_CI
    
    }
  }
}
```

```{r}
#Add baselines (from t1).
baselines <- ds_patches_effect_size %>%
  filter(time_point == 1) %>%
  group_by(patch_type) %>%
  summarise(across(paste0(variables_patches, "_d"), 
                   .names = "baseline_{.col}"))

ds_patches_effect_size = full_join(ds_patches_effect_size, baselines)
```