---
title: "isolated_patches"
author: "Emanuele Giacomuzzo"
date: "2022-10-17"
output: html_document
editor_options: 
  chunk_output_type: console
---

#### Species Densities {.tabset .tabset-pills}

##### Ble

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Ble,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Ble Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Cep

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Cep,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Cep Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Col

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Col,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Col Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Eug

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Eug,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Eug Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Eup

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Eup,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Eup Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Lox

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Lox,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Lox Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Pau

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Pau,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Pau Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Pca

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Pca,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Pca Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Spi

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Spi,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Spi Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Spi_te

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Spi_te,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Spi_te Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

##### Tet

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
       metaecosystem == "no") %>%
  mutate(eco_metaeco_type = fct_reorder(eco_metaeco_type, patch_size_volume)) %>%
  ggplot(aes(
    x = day,
    y = Tet,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot() +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Tet Density (indiv/μl ?)",
    fill = "",
    caption = "Vertical grey line: resource flow"
  ) +
  scale_fill_manual(
    values = c(colour_small, colour_medium, colour_large),
    labels = c("Small isolated",
               "Medium isolated",
               "Large isolated")
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```