---
title: "Isolated patches - Evenness"
output: html_document
date: "2023-02-15"
editor_options: 
  chunk_output_type: console
---

##### Day - Evenness {.tabset .tabset-pills}

```{r}
response_variable = "evenness_pielou"
```

```{r}
plot.patches.boxplots(eco_metaeco_type_input,
                       response_variable)

plot.patches.points(eco_metaeco_type_input,
                       response_variable)
```

##### Patch size - Evenness {.tabset .tabset-pills}

###### Isolated

```{r}
plot.patches.size.response.boxplots(metaecosystem_input = "no",
                                  trophic_type_input = "NA",
                                  flow_input = "NA",
                                  response_variable = response_variable)
```

###### Connected

```{r}
plot.patches.size.response.boxplots(metaecosystem_input = "yes",
                                  trophic_type_input = "NA",
                                  flow_input = "NA",
                                  response_variable = response_variable)
```
