---
title: "isolated_patches"
author: "Emanuele Giacomuzzo"
date: "2022-09-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Isolated patches {.tabset .tabset-pill}

#### Low disturbance

```{r}
for(time_point_input in 0:7) {
  print(
    ds_classes_effect_size %>%
      filter(disturbance == "low",
             metaecosystem == "no",
             day == time_point_input*4) %>%
      ggplot(
        aes(
          x = log_size_class,
          y = log_abundance,
          group = interaction(log_size_class, eco_metaeco_type),
          color = eco_metaeco_type
        )
      ) +
      geom_point(stat = "summary", fun = "mean") +
      geom_line(
        stat = "summary",
        fun = "mean",
        aes(group = eco_metaeco_type)
      ) +
      geom_errorbar(
        aes(ymax = log_abundance_upper_ci,
            ymin = log_abundance_lower_ci),
        width = .2,
        position = position_dodge(0.05)
      ) +
      scale_color_manual(
        values = c(colour_large, colour_medium, colour_small),
        labels = c(name_L_isolated,
                   name_M_isolated,
                   name_S_isolated)
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)
      ) +
      labs(
        title = paste0("Day = ", (time_point_input*4)),
        x = 'Log size (μm2)',
        y = 'Log abundance + 1 (indiv/μm2)',
        color = ""
      )
  )
}
```

#### High disturbance

```{r}
for(time_point_input in 0:7) {
  print(
    ds_classes_effect_size %>%
      filter(disturbance == "high",
             metaecosystem == "no",
             day == time_point_input*4) %>%
      ggplot(
        aes(
          x = log_size_class,
          y = log_abundance,
          group = interaction(log_size_class, eco_metaeco_type),
          color = eco_metaeco_type
        )
      ) +
      geom_point(stat = "summary", fun = "mean") +
      geom_line(
        stat = "summary",
        fun = "mean",
        aes(group = eco_metaeco_type)
      ) +
      geom_errorbar(
        aes(ymax = log_abundance_upper_ci,
            ymin = log_abundance_lower_ci),
        width = .2,
        position = position_dodge(0.05)
      ) +
      scale_color_manual(
        values = c(colour_large, colour_medium, colour_small),
        labels = c(name_L_isolated,
                   name_M_isolated,
                   name_S_isolated)
      ) +
      labs(
        title = paste0("Day = ", (time_point_input*4)),
        x = 'Log size (μm2)',
        y = 'Log abundance + 1 (indiv/μm2)',
        color = ""
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      )
  )
}
```