---
title: "Large patches - size classes"
output: html_document
date: "2022-12-21"
editor_options: 
  chunk_output_type: console
---

#### Size Classes {.tabset .tabset-pills}

##### Means & 95% CI

```{r}
filtered_data = ds_classes %>%
  filter(disturbance == disturbance_input,
         patch_size == "L") %>%
  ungroup() %>%
  summarySE(measurevar = "size_class_abundance",
            groupvars = c("day", 
                          "size_class_n",
                          "eco_metaeco_type"))

for(size_class_input in 1:nr_of_size_classes) {

  p = filtered_data %>%
    filter(size_class_n == size_class_input) %>%
    ggplot(aes(x = day,
               y = size_class_abundance,
               color = eco_metaeco_type)) +
    geom_point(position = position_dodge(0.5)) +
    geom_line(position = position_dodge(0.5)) +
    geom_errorbar(
      aes(ymin = size_class_abundance + ci,
          ymax = size_class_abundance - ci),
      width = .2,
      position = position_dodge(0.5)
    ) +
    geom_hline(
      yintercept = 0,
      linetype = "dotted",
      color = "black",
      size = 0.7
    ) +
    labs(
      x = name_time_axis,
      y = paste0(
        "Class ",
        size_class_input,
        " ",
        name_y_axis_size_class
      ),
      color = ""
    ) +
    scale_color_manual(
      values = c(colour_isolated,
                 colour_same_size,
                 colour_different_size),
      labels = c(name_L,
                 name_L_connected_to_L,
                 name_L_connected_to_S)
    ) +
    theme_bw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "bottom"
    )
  
  print(p)
}
```


##### Effect sizes

```{r}
small_class = NULL
for(size_class_input in 1:nr_of_size_classes){

 filtered_data = ds_classes_effect_size %>%
    filter(
      disturbance == disturbance_input,
      time_point >= first_time_point_model,
      time_point <= last_time_point_model,
      eco_metaeco_type %in% c("L (S_L)", "L (L_L)"),
      disturbance == disturbance_input,
      size_class_n == size_class_input
    ) %>%
    ungroup()

p_effect_size = filtered_data %>%
    ggplot(aes(x = day,
               y = abundance_hedges_d,
               color = eco_metaeco_type)) +
    geom_point(position = position_dodge(0.5)) +
    geom_line(position = position_dodge(0.5)) +
    geom_errorbar(
      aes(ymin = abundance_hedges_d_lower,
          ymax = abundance_hedges_d_upper),
      width = .2,
      position = position_dodge(0.5)
    ) +
    geom_hline(
      yintercept = 0,
      linetype = "dotted",
      color = "black",
      size = 0.7
    ) +
    labs(
      x = 'Day',
      y = paste0(
        "Class ",
        size_class_input,
        " ",
        name_y_axis_size_class_effect_size
      ),
      color = ""
    ) +
    scale_color_manual(
      values = c(colour_different_size, colour_same_size),
      labels = c(name_L_connected_to_L,
                 name_L_connected_to_S)
    ) +
    theme_bw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "bottom"
    )

print(p_effect_size)

# full_model = lm(abundance_hedges_d ~                  
#                   eco_metaeco_type +
#                   eco_metaeco_type : day,
#                   data = filtered_data)
# 
# # par(mfrow = c(2,3))
# # plot(full_model, which = 1:5)
# 
# null_model = lm(abundance_hedges_d ~                  
#                   1,
#                   data = filtered_data)
# 
# AIC = AIC(full_model, null_model)
# AIC
# AIC_full = AIC$AIC[1]
# AIC_null = AIC$AIC[2]
# deltaAIC = AIC_full - AIC_null
# deltaAIC = round(deltaAIC, digits = 2)
# 
# anova = anova(full_model, null_model)
# anova
# 
# p_value = anova$`Pr(>F)`[2]
# p_value = round(p_value, digits = 3)
# 
# R2_full = glance(full_model)$r.squared
# R2_null = glance(null_model)$r.squared
# R2_P =  R2_full - R2_null
# R2_P = round(R2_P, digits = 2)
# 
# small_class[[size_class_input]] = p_effect_size +
#   labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
}
```