---
title: "large_patches"
author: "Emanuele Giacomuzzo"
date: "2022-10-17"
output: html_document
editor_options: 
  chunk_output_type: console
---

##### Boxplots

```{r}
for (species_input in protist_species){
  
  response_variable = species_input
  
  print(plot.patches.boxplots(patch_type_input,
                              response_variable))
  
}
```

##### Mean +- 95%

```{r}
for (species_input in protist_species){
  
  response_variable = species_input
  
  print(plot.patches.points(patch_type_input,
                              response_variable))
  
}
```

##### Effect size

```{r}
for (species_input in protist_species){
  
  response_variable = species_input
  
  print(plot.patches.points.ES(patch_type_input,
                              paste0(response_variable, "_d")))
  
}
```

##### Analysis

```{r}
patch_size_input = "L"
```

###### Ble

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Ble_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Ble_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

###### Cep

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Cep_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Cep_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

###### Col

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Col_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Col_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

###### Eug

```{r eval = include_incomplete_time_series}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r eval = include_incomplete_time_series}
full_model = lm(Eug_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Eug_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

###### Eup

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Eup_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Eup_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

##### Lox

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Lox_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Lox_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

##### Pau

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Pau_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Pau_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

##### Pca

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Pca_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Pca_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

##### Spi

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Spi_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Spi_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

##### Spi_te

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Spi_te_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Spi_te_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```

##### Tet

```{r eval = include_incomplete_time_series}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r eval = include_incomplete_time_series}
full_model = lm(Tet_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Tet_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
print(paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))
```