---
title: "small_patches"
author: "Emanuele Giacomuzzo"
date: "2022-09-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
response_variable = "median_body_area_µm2"
```

```{r}
plot.patches.points(ds_patches,
                    patch_type_input,
                    response_variable)
```

<details>
  <summary>Click for boxplots</summary>
```{r}
plot.patches.boxplots(patch_type_input,
                      response_variable)
```
</details>

<details>
  <summary>Click for replicates</summary>
```{r}
plot.patches.replicates(patch_type_input,
                        response_variable)
```
</details>

<details>
  <summary>Click for effect sizes</summary>
```{r}
plot.patches.points.ES(ds_patches_effect_size, 
                       patch_type_input,
                       paste0(response_variable, "_d"))
```
</details>

##### Large isolated vs Large connected to large

```{r}
patch_type_input_model = c("Large isolated",
                           "Large connected to large")
```

```{r child = here("r_files", "analysis_small_n_large_patches.Rmd")}
```

##### Large connected to small vs Large connected to large

```{r}
patch_type_input_model = c("Large connected to small",
                           "Large connected to large")
```

```{r child = here("r_files", "analysis_small_n_large_patches.Rmd")}
```