---
title: "large_patches"
author: "Emanuele Giacomuzzo"
date: "2022-09-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

#### Body Size Distribution {.tabset .tabset-pills}

##### Mean & 95% CI

```{r}

#Body Size Distribution mean + 95% CI

for(time_point_input in 0:7) {
  print(
    ds_classes_effect_size %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("Large isolated", "Large connected to large", "Large connected to small"),
             day == time_point_input*4) %>%
      ggplot(
        aes(
          x = log_size_class,
          y = log_abundance,
          group = interaction(log_size_class, eco_metaeco_type),
          color = eco_metaeco_type
        )
      ) +
      geom_point(stat = "summary", fun = "mean") +
      geom_line(
        stat = "summary",
        fun = "mean",
        aes(group = eco_metaeco_type)
      ) +
      geom_errorbar(
        aes(ymax = log_abundance_upper_ci,
            ymin = log_abundance_lower_ci),
        width = .2,
        position = position_dodge(0.05)
      ) +
      scale_color_manual(
        values = c(colour_L,
                   colour_same_size,
                   colour_different_size),
        labels = c(name_L_isolated,
                   name_L_connected_to_L,
                   name_L_connected_to_S)
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      labs(
        title = paste0("Day = ", (time_point_input*4)),
        x = x_axis_size_class,
        y = 'Log abundance + 1 (indiv/μm2)',
        color = ""
      )
      # ) +
      # scale_x_continuous(breaks = unique(round(ds_classes_effect_size$log_size_class, digits = 1)))
  )
}
```

##### Effect size

```{r}

#Effect size

for(time_point_input in 0:7) {
  print(
    ds_classes_effect_size %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("Large connected to large", "Large connected to small"),
             day == time_point_input * 4) %>%
      ggplot(
        aes(
          x = log_size_class,
          y = abundance_hedges_d,
          color = eco_metaeco_type
        )
      ) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = abundance_hedges_d_lower,
            ymax = abundance_hedges_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      scale_color_manual(
        values = c(colour_same_size,
                   colour_different_size),
        labels = c(name_L_connected_to_L,
                   name_L_connected_to_S)
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      labs(
        title = paste0("Day = ", (time_point_input * 4)),
        x = x_axis_size_class,
        y = y_axis_size_class_effect_size,
        color = ""
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )
  )
}
```
