---
title: "Medium Patches - Species Densities"
output: html_document
date: "2022-12-09"
editor_options: 
  chunk_output_type: console
---

#### Species Densities {.tabset .tabset-pills}

```{r}
patch_size_input = "M"
```

##### Ble

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Ble,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Ble Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Ble_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Ble_d_lower,
            ymax = Ble_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Ble Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Ble_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Ble_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Ble_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Ble_small
```

##### Cep

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Cep,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Cep Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Cep_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Cep_d_lower,
            ymax = Cep_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Cep Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Cep_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Cep_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Cep_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Cep_small
```

##### Col

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Col,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Col Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Col_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Col_d_lower,
            ymax = Col_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Col Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Col_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Col_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Col_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Col_small
```

##### Eug

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Eug,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Eug Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Eug_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Eug_d_lower,
            ymax = Eug_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Eug Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r eval = include_incomplete_time_series}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r eval = include_incomplete_time_series}
full_model = lm(Eug_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Eug_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r eval = include_incomplete_time_series}
density_Eug_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Eug_small
```

##### Eup

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Eup,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Eup Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Eup_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Eup_d_lower,
            ymax = Eup_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Eup Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Eup_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Eup_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Eup_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Eup_small
```

##### Lox

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Lox,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Lox Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Lox_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Lox_d_lower,
            ymax = Lox_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Lox Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Lox_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Lox_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Lox_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Lox_small
```

##### Pau

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Pau,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Pau Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Pau_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Pau_d_lower,
            ymax = Pau_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Pau Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Pau_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Pau_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Pau_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Pau_small
```

##### Pca

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Pca,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Pca Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Pca_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Pca_d_lower,
            ymax = Pca_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Pca Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Pca_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Pca_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Pca_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Pca_small
```

##### Spi

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Spi,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Spi Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Spi_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Spi_d_lower,
            ymax = Spi_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Spi Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Spi_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Spi_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Spi_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Spi_small
```

##### Spi_te

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Spi_te,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Spi_te Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Spi_te_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Spi_te_d_lower,
            ymax = Spi_te_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Spi_te Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r}
full_model = lm(Spi_te_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Spi_te_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r}
density_Spi_te_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Spi_te_small
```

##### Tet

```{r}
ds_patches %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input
      ) %>%
      ggplot(
        aes(
          x = day,
          y = Tet,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = "Tet Density (indiv/ml)",
        fill = "",
        caption = caption_resource_flow
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          name_M_isolated,
          "Medium connected to medium"
          
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Tet_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Tet_d_lower,
            ymax = Tet_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        x = "Day",
        y = "Tet Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Medium connected to medium"
                    )
       ) +
      scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

p_effect_size
```

```{r eval = include_incomplete_time_series}
filtered_data = ds_patches_effect_size %>%
  filter(patch_size == patch_size_input,
         disturbance == disturbance_input,
         time_point >= first_time_point_model,
         time_point <= last_time_point_model)
```

```{r eval = include_incomplete_time_series}
full_model = lm(Tet_d ~                  
                  eco_metaeco_type +
                  eco_metaeco_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(Tet_d ~                  
                  1,
                  data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P =  R2_full - R2_null
R2_P = round(R2_P, digits = 2)
```

```{r eval = include_incomplete_time_series}
density_Tet_small = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC , ", p = ", p_value, ", Adjusted R2 = ", R2_P))

density_Tet_small
```