---
title: "MM all vs SL all – alpha diversity"
output: html_document
date: "2022-12-13"
editor_options: 
  chunk_output_type: console
---

#### Alpha diversity {.tabset .tabset-pills}

```{r}
ds_metaecosystems %>%
  filter(
    disturbance == disturbance_input,
    metaecosystem_type %in% c("S_L", "S_L_from_isolated", "M_M", "M_M")
  ) %>%
  ggplot(
    aes(
      x = day,
      y = mean_shannon,
      group = interaction(day, metaecosystem_type),
      fill = metaecosystem_type
    )
  ) +
  geom_boxplot(width = boxplot_width) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = name_y_axis_alpha_diversity,
    fill = "",
    caption = caption_resource_flow
  ) +
  # scale_fill_manual(values = c(colour_SL, colour_isolated),
  #                   labels = c(name_SL, name_SL_from_isolated)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

```{r}
p_all_metaecos_alpha = ds_metaecosystems %>%
  filter(disturbance == disturbance_input) %>%
  summarySE(measurevar = "mean_shannon", 
            groupvars = c("day", "metaecosystem_type")) %>%
  filter(metaecosystem_type %in% c("S_L", 
                              "S_L_from_isolated", 
                              "M_M",
                              "M_M_from_isolated")
  ) %>%
  ggplot(
    aes(
      x = day,
      y = mean_shannon,
      group = interaction(day, metaecosystem_type),
      color = metaecosystem_type
    )
  ) +
  geom_point(stat = "summary", 
             fun = "mean",
             position = position_dodge(dodging)) +
  geom_line(stat = "summary",
            fun = "mean",
            aes(group = metaecosystem_type),
            position = position_dodge(dodging)) +
  geom_errorbar(
    aes(ymax = mean_shannon + ci,
        ymin = mean_shannon - ci),
    width = .2,
    position = position_dodge(dodging)
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = name_y_axis_alpha_diversity,
    color = "",
    caption = caption_resource_flow
  ) +
   scale_color_manual(
     values = c(colour_MM,
                colour_MM_from_isolated,
                colour_SL,
                colour_SL_from_isolated),
     labels = c(name_MM,
                name_MM_from_isolated,
                name_SL,
                name_SL_from_isolated)
   ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  guides(color = guide_legend(nrow = 2, title.position = "top"))

p_all_metaecos_alpha
```