---
title: "SL from isolated vs MM from isolated"
output: html_document
date: "2022-12-09"
editor_options: 
  chunk_output_type: console
---

#### Biomass {.tabset .tabset-pills}

```{r}
ds_metaecosystems %>%
      filter (disturbance == disturbance_input,
              metaecosystem_type %in% c("S_L_from_isolated", "M_M_from_isolated")) %>%
      ggplot (
        aes(
          x = day,
          y = total_metaecosystem_bioarea,
          group = system_nr,
          fill = system_nr,
          color = system_nr,
          linetype = metaecosystem_type
        )
      ) +
      geom_line () +
      labs(
        x = "Day",
        y = name_y_axis_total_bioarea,
        fill = "System nr",
        color = "System nr",
        linetype = ""
      ) +
      scale_linetype_discrete(labels = c(name_MM_from_isolated,
                                         name_SL_from_isolated)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_x_continuous(breaks = unique(ds_metaecosystems$day)) +
      #scale_y_continuous(labels = comma) + 
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      labs(caption = caption_resource_flow)
```

```{r}
p_boxplots = ds_metaecosystems %>%
      filter(disturbance == disturbance_input,
             metaecosystem_type %in% c("S_L_from_isolated", "M_M_from_isolated")) %>%
      ggplot (
        aes(
          x = day,
          y = total_metaecosystem_bioarea,
          group = interaction(day, metaecosystem_type),
          fill = metaecosystem_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = "Day",
        y = name_y_axis_total_bioarea,
        color = '',
        fill = ''
      ) +
      scale_fill_manual(
        values = c(colour_MM, colour_SL),
        labels = c(name_MM_from_isolated,
                   name_SL_from_isolated)
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      )  +
      scale_x_continuous(breaks = unique(ds_metaecosystems$day)) +
      geom_vline(
        xintercept = resource_flow_days[1],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6],
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      labs(caption = caption_resource_flow)

p_boxplots
```

```{r}
p_MM_isolated_SL_isolated_biomass = ds_metaecosystems %>%
  filter(disturbance == disturbance_input) %>%
  summarySE(measurevar = "total_metaecosystem_bioarea",
            groupvars = c("day", "metaecosystem_type")) %>%
  filter(day > 5,
         metaecosystem_type %in% c("S_L_from_isolated",
                                   "M_M_from_isolated")) %>%
  ggplot(
    aes(
      x = day,
      y = total_metaecosystem_bioarea,
      group = interaction(day, metaecosystem_type),
      color = metaecosystem_type
    )
  ) +
  geom_point(stat = "summary",
             fun = "mean",
             position = position_dodge(dodging)) +
  geom_line(
    stat = "summary",
    fun = "mean",
    aes(group = metaecosystem_type),
    position = position_dodge(dodging)
  ) +
  geom_errorbar(
    aes(ymax = total_metaecosystem_bioarea + ci,
        ymin = total_metaecosystem_bioarea - ci),
    width = .2,
    position = position_dodge(dodging)
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = name_y_axis_total_bioarea,
    color = "",
    caption = caption_resource_flow
  ) +
  scale_color_manual(
    values = c(
      colour_MM_from_isolated,
      colour_SL_from_isolated
    ),
    labels = c(
      name_MM_from_isolated,
      name_SL_from_isolated
    )
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )

p_MM_isolated_SL_isolated_biomass
```

```{r}
filtered_data = ds_metaecosystems %>%
    filter(metaecosystem_type %in% c("M_M_from_isolated", "S_L_from_isolated"),
           disturbance == disturbance_input,
           time_point >= first_time_point_model,
           time_point <= last_time_point_model)
```

```{r}
full_model = lmer(
  total_metaecosystem_bioarea ~
    day +
    metaecosystem_type +
    metaecosystem_type : day +
    baseline_bioarea + 
    baseline_bioarea : day +
    (day | system_nr),
  data = filtered_data,
  REML = FALSE,
  control = lmerControl(optimizer = "Nelder_Mead")
)

summary(full_model)
plot(full_model)
qqnorm(resid(full_model))
```

```{r}
null_model = lmer(
  total_metaecosystem_bioarea ~
    day +
    baseline_bioarea + 
    baseline_bioarea : day +
    (day | system_nr),
  data = filtered_data,
  REML = FALSE,
  control = lmerControl(optimizer = "Nelder_Mead")
)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC_MM_isolated_SL_isolated_biomass = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova
p_value = anova$`Pr(>Chisq)`[2]
if(p_value == 0){
  p_value_MM_isolated_SL_isolated_biomass = "< 0.001"
} else {
  p_value_MM_isolated_SL_isolated_biomass = round(p_value, digits = 3)
}
```