---
title: "Other"
output: html_document
date: "2023-08-21"
---

### Running time

```{r running-time, echo = FALSE, eval = TRUE}
end_time = Sys.time()
round(end_time - start_time, digits = 1)
```

### Disturbance input

Check that disturbance_global_input is what you set:

```{r}
print(paste0("Disturbance = ", disturbance_global_input))
```

### Change code using terminal

If you want to change a certain part of the code:

```{r eval = FALSE}
#Rmd script
cd /Users/ema/Documents/GitHub/PatchSize/r_files
sed -i '' 's/old_string/new_string/g' *.Rmd

#R script
cd /Users/ema/Documents/GitHub/PatchSize/r_files/functions
sed -i '' 's/old_string/new_string/g' *.R
```

### Code to give you back an object

```{r eval = FALSE}
dput()
```

### Crashed cultures

The only type of patch where all cultures crashed was small connected to small at high disturbance.

### Residuals

-   

-   

### References

```{r echo=FALSE, message=FALSE}
save.image(file = here("environments", "end.RData"))
```

```{r echo = FALSE, eval = FALSE}
beepr::beep("fanfare")
```
