---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

We want here to plot the final paper version of the ratio between autotrophic and heterotrophic biomass in small, medium, and large unconnected ecosystems. We need to plot it again instead of using the plots we used in the analysis because we want to have S, M, and L in the legend.

```{r}

# Define ecosystems and response variable you want to plot.

patch_type_input = c("S",
                     "M",
                     "L")

response_variable = "auto_hetero_ratio"
```

```{r fig.height = figures_height_rmd_output}

# Construct plot

p = ds_patches %>%
  mutate(patch_type = case_when(patch_type == "Small unconnected" ~ "S",
                                patch_type == "Medium unconnected" ~ "M",
                                patch_type == "Large unconnected" ~ "L")) %>%
  filter(patch_type %in% patch_type_input,
         !is.na(!!sym(response_variable))) %>%
  summarySE(measurevar = response_variable,
            groupvars = c("day", "patch_type", "patch_size", "connection")) %>%
  ggplot(aes(x = day,
             y = get(response_variable),
             group = interaction(day, patch_type),
             color = patch_type)) +
  geom_point(stat = "summary",
             fun = "mean",
             position = position_dodge(dodging),
             size = treatment_points_size) +
  geom_line(stat = "summary",
            fun = "mean",
            aes(group = patch_type),
            position = position_dodge(dodging),
            linewidth = treatment_lines_linewidth) +
  geom_errorbar(aes(ymax = get(response_variable) + ci,
                    ymin = get(response_variable) - ci),
                width = width_errorbar,
                position = position_dodge(dodging)) +
  labs(x = axis_names$axis_name[axis_names$variable == "day"],
       y = axis_names$axis_name[axis_names$variable == response_variable],
       color = "") +
  scale_color_manual(values = c("#000000",
                                "#737373",
                                "#bdbdbd")) +
  geom_vline(xintercept = resource_flow_days,
             linetype = resource_flow_line_type,
             color = resource_flow_line_colour,
             linewidth = resource_flow_line_width) +
  geom_hline(yintercept = 0,
             color = zero_line_colour,
             linetype = zero_line_line_type,
             linewidth = zero_line_line_width) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = legend_position,
        legend.key.width = unit(legend_width_cm, "cm")) +
  guides(color = guide_legend(title = NULL,
                              nrow = 1),
         linetype = guide_legend(title = NULL,
                                 nrow = 1)) +
  geom_rect(xmin = grey_background_xmin, 
            xmax = grey_background_xmax,
            ymin = grey_background_ymin, 
            ymax = grey_background_ymax, 
            fill = grey_background_fill, 
            alpha = grey_background_alpha,
            color = grey_background_color)

p
```

```{r echo = FALSE, results=FALSE}

# Save plot

png(file = here("results", "figures", disturbance_global_input, "paper", "ecosystem_auto_heterotrophic_ratio.png"),
    width = paper_width,
    height = paper_height,
    units = paper_units,
    res = paper_res)

p

dev.off()
```