---
title: "discarded"
output: html_document
date: "2023-04-05"
---

-   Here's what we know about how patch size modulates resource flow. Which actually are more frequent and widespread than any other flow. How much subsidies cross a given section of the ecotone depends on the donor ecosystem's size. Larger ecosystems create a greater flow of subsidies, as the same perimeter length covers a larger area in bigger ecosystems. This is demonstrated by the fact that larger rivers and lakes have a higher number of emerging insects crossing per meter of ecotone @Gratton2009. Resource coming into a smaller patch should increase more its secondary production. This is shown by smaller ecosystems having resource flow influence more their secondary production @Polis1996, salmon provides the most nitrogen to plants and invertebrates in smaller river watersheds @Hocking2009, experimentally algal wracks increased lizards populations the most in smaller islands @Wright2020, and resource flow structure bird community composition the most in small islands in British Columbia @Obrist2022b.

-   Two meta-ecosystems of the same total volume but of patches of different size were constructed. The first meta-ecosystem was composed of a small and a large patch (small-large meta-ecosystem). The other meta-ecosystem was composed of two medium patches (medium-medium meta-ecosystem). All patches started with the same protist community (nine water ciliates, one alga, and one rotifer). Non-living material flowed bidirectionally between the two patches, with the same magnitude. Non-living material flows were created by boiling a fixed volume of the community and poring it into the receiving patch. This caused small patches to be more disturbed than medium patches and medium patches be more disturbed than large patches. No dispersal occurred throughout the experiment. We additionally created also the following control treatments: isolated small, medium, and large patches, as well as meta-ecosystems with two small patches (small-small meta-ecosystems), meta-ecosystems with two medium patches (medium-medium meta-ecosystems), and meta-ecosystems with two large patches (large-large meta-ecosystems).

-   The inflow of non-living material coming from a productive patch have already been shown to be beneficial for the functioning of patches under perturbations (@Colombo2021). Therefore, small patches that receive a lot of non-living material will recover better from the perturbations that cause resource flow, meanwhile the larger patches will recover worse. The effects of resource flow on meta-ecosystem function will depend on how much large patches increase the function of the small patches and how much the small patches decrease the function of the large patches.

-   We here refer to biomass production as patch function, which we use interchangeably.

-   Also, as larger patches are more resistant (@Greig2022), they will produce less detritus. This is why we can actually kind of assume that other types of distrubance which are not exactly killing the same amount of individuals will have a similar effect, as larger patches are more resistant.

-   As larger patches are more resistant (@Greig2022), they will need less detritus to counteract the effects of perturbations that is creating resource flow.

-   The explanation lies in the quantity of detritus exchanged between patches. Detritus is essential for patches to recover from perturbations. In the absence of resource flows, asymmetric size would lead to a more productive meta-ecosystem since the production of large and small isolated patches together was greater than that of two medium-sized patches. However, the reciprocal flow of resources between asymmetric-sized patches can reduce the function of the meta-ecosystem. This is due to the non-symmetric effects of the reciprocal flow of resources on small and large patches. The influx of resources from a large patch enhances the function of a small patch less than the small amount of resources from small patches increases the function of large patches. Consequently, the overall function of the meta-ecosystem decreases.

-   [Not sure if this paragraph should be in, as I would like to run an experiment to test this prediction]. Our experiment showed that when patches are isolated, having small and large patches might increase function more than having medium patches. This is opposed to what @Benedetti-Cecchi2005 predicted. They predict that the patch size-productivity relationship is concave and therefore because of more Jensen's inequality function should decline with increasing variance in patch size. The reason why we think that our two conclusions are in disagreement is because @Benedetti-Cecchi2005 did a meta-analysis of biodiversity experiments where disturbance was not considered. In that case, we think that patch size-productivity will be concave. However, we believe that when patches are disturbed, as in our experiment, smaller patches are less resistant to many disturbances (e.g., fire) (@Greig2022). This should cause the small patches to go down more than large patches showing a convex relationship between patch size and productivity. This should cause a larger increase in the variance of patch size to increase the function of the landscape.

-   As the volume exchanged between patches remained the same (e.g., 5.25 ml flowed from patch 1 to 2 and 5.25 ml from patch 2 to 1), the patch volume remained constant over time.

-   To determine the 95% confidence interval of means, I used a code that can be found on a Stack Overflow thread (<https://stackoverflow.com/questions/35953394/calculating-length-of-95-ci-using-dplyr>). The code is based on the formula presented in the Lumen Learning course "Introduction to Statistics" (<https://courses.lumenlearning.com/introstats1/chapter/a-single-population-mean-using-the-student-t-distribution/>). The formula to calculate the upper and lower bounds of the 95% confidence interval is as follows:

$$
CI_{lower} = mean - (t \: score * \frac{SD}{sample \: size})
$$

$$
CI_{upper} = mean + (t \: score * \frac{SD}{sample \: size})
$$

where the t-score is computed from the student t distribution using the r function qt with percentile = 0.975 and degrees of freedom = sample size - 1.

-   To determine how response variables change across treatments, we chose to use an effect size with the control being a patch of the same size but isolated. Initially, we considered using the natural logarithm of the response ratio (lnRR), but some values of the response variables in the control or treatment were 0. Adding 1 to all null values, as suggested in the literature, would have inflated the effect sizes. As a result, we searched for alternative effect size metrics and found that Hedge's d (also known as Hedge's g) is the most commonly used and preferred metric today (@Hedges1985). Hedge's d is calculated as the difference in mean between the treatment and control groups divided by the standard deviation of the pooled data. Another option would have been Cohen's d, but this metric is less effective for sample sizes smaller than 20 (as discussed in this post on StatisticsHowTo: <https://www.statisticshowto.com/hedges-g/>).

-   To perform mixed effect modeling on our data, we utilized the R package lme4. The code syntax was obtained from the vignette available at <https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf>. Interaction terms were coded following the guidelines provided in chapter 9 of the book "An R Companion to Statistics: Data Analysis and Modeling" by Maarten Speekenbrink (<https://mspeekenbrink.github.io/sdam-r-companion/linear-mixed-effects-models.html>). Model diagnostics were conducted using quantile-quantile plots (plot(mixed_model)) and partial residual plots (qqnorm(resid(mixed_model))), as recommended by @Zuur2009 (page 487).

-   The effect size of the explanatory variables was computed as marginal and conditional R squared. The marginal R squared represents the amount of variance explained by the fixed effects, while the conditional R squared accounts for both the fixed and random effects. The calculation of marginal and conditional R squared was performed using the MuMIn package, based on the methods of @Nakagawa2017. For the coding and interpretation of these R squared values, refer to the documentation for the r.squaredGLMM function.

-   Time can either be included as a fixed or random effect. If the data points are dependent on each other (e.g. seasons), time should be included as a random effect. However, since the biomass in our experiment showed a temporal trend and exhibited autocorrelation (i.e. t2 is more similar to t3 than t4), we decided to include time as a fixed effect. For a comprehensive discussion on this topic, see this blog post: <https://dynamicecology.wordpress.com/2015/11/04/is-it-a-fixed-or-random-effect/>.

-   Some interactions cannot be tested in R, as described in this Stack Overflow thread (<https://stackoverflow.com/questions/40729701/how-to-use-formula-in-r-to-exclude-main-effect-but-retain-interaction>). This is specifically the case when the interaction is between a factor (e.g., patch_type) and a continuous variable (e.g. day), and the factor is the primary predictor. This limitation is due to the model.matrix.default function. To test the effects of day, I must remove the interaction term with patch_type.

-   Model selection was performed using the Akaike Information Criterion (AIC). A difference in AIC of 2 was considered to be the threshold that distinguishes between two models, with the model having the lower AIC being preferred. If the difference in AIC does not exceed 2, the model with the smallest number of parameters is preferred. This approach was suggested by @Halsey2019 as an alternative to using p-values. P-values are not a reliable method of model selection due to the small sample size (five replicates), which can result in larger p-values, and because p-values can be highly variable, leading to many false positives and negatives (e.g., with a p-value of 0.05, there is a 1 in 3 chance that it's a false positive).

-   To analyze local patch properties, we compared the small patch to other small patches that were either connected to another small patch or isolated instead of being connected to a large patch.

-   Additionally, we evaluated the effect of patch size by comparing isolated patches of different sizes (small, medium, and large) and meta-ecosystems with patches of different sizes (meta-ecosystems with small, medium, and large patches).

-   We called the meta-ecosystem with a small and a large patch Small-Large and the one with two medium patches Medium-Medium.

-   The size of the donor patch .... had an impact on the biomass of the small patch, but not on the large patch (as seen in Figure 4A, with ... evidence and a p-value of ...). Additionally, there was moderate evidence (with a p-value of 0.015 or 0.022 and R2 of 0.47 or 0.55) that small patches connected to large patches were more productive than those connected to small patches. However, there was no evidence that the size of the connected patch affected the Shannon index of either patch (as indicated by p-values greater than 0.1 in Figure 4B). This was shown using linear models.

-   The shape of the size-productivity relationship depends on the disturbance and resource flow. Undisturbed isolated patches have a concave relationship. Disturbance changes such relationship to a convex one. Resource flow, however, bring it back to concave.

-   One of the things including the number of In terms of productivity, we know that landscapes that have more ecosystems are more productive, as well as landscapes that are better connected (@Oehri2020). We also know that the biodiversity patterns we observe in a landscape depend upon how big, isolated, and heterogeneous its ecosystems are (?).

-   Furthermore, algal wrack could increase the species richness of dune plants ([[DalVecchio2017]]), marine-derived nitrogen could decrease the number of plant species ([[Obrist2022a]]), and salmon carcasses could decrease the species richness of riparian plants ([[Hocking2011]]).

-   This was testified by a meta-analysis which found that the effects of subsidies will depend on how productive the ecosystem is compared to the amount of subsidies that entered it. Lots of subsidies in unproductive ecosystems will have a stronger effects than few subsidies entering productive ecosystems. This can be explained by the fact that a lot of subsidies (coming from large patches) are entering into an unproductive patch (small patches). This was found already in a meta-analysis @Marczak2007.

-   We suggest testing the results of this paper in the following meta-ecosystems: island and ocean, fragmented landscapes, and forest and adjacent ecosystems. A place we suggest testing such prediction would be in the most studied meta-ecosystems. For example, we predict that the larger a forest, the larger its effect on a nearby river or lake. What we found also challenging is to characterise meta-ecosystems in the field. Not many have calculated the flow of resources between ecosystems. This makes it harder, of course.

-   *An addition to the SIB -\>* Our study also shows that the same amount of subsidies can have a greater impact on smaller patches. This can happen when smaller patches are less productive. Our study supports the hypothesis by which the species richness of smaller patches should be affected by subsidies (Subsidised Island Biogeography Hypothesis, @Anderson2001). It actually adds a novel mechanism to it. The meta-analysis of @Marczak2007 showed that if the same amount of subsidies arrive, they will have a greater effect in unproductive ecosystems. This mechanism of smaller patches being more affected by subsidies goes in addition to another mechanism. This is smaller islands having a higher perimeter to area ratio. Therefore, smaller islands will be more susbidised per square meter. For instance, @Polis1996 highlighted that unproductive islands receiving an equal amount of resources per meter of ecotone, secondary production was enhanced more on smaller islands. Additionally, a study by @Hocking2009 revealed that smaller river watersheds rely more on salmon to provide nitrogen to plants and invertebrates compared to larger watersheds.

-   The first mechanism we show mediating the effects of patch size ratio on biodiversity and function is the non-linearity of the size-biodiversity and size-productivity relationships. Landscapes are made of ecosystems of different size. To understand the biodiversity and productivity of a landscape requires us to know the variance in the size of the patches constitutes it. The higher the variance in patch size, the lower the biodiversity of the patches, but the higher their productivity. This is because the size-biodiversity relationship is concave and the size-productivity relationship is convex. This effect of variance through non-linearity is known as Jensen's inequality \@Jensen1906.

-   This is because when the relationship between size and productivity is non-linear, the higher the variance in patch size, the more the biodiversity will be different from the biodiversity of their mean. Biodiversity will be higher with higher variance when the relationship is convex and lower when the relationship is concave. This is known as Jensen's inequality \@Jensen1906. As the biodiversity was lower in landscapes with patches of different size, we can infer the species-area relationship to be concave @Matthews2021. This is because ... The convexity of the size-productivity relationship in our experiment we believe stems from the inability of small patches to recover from disturbance, as they were disturbed more. This would be in line with patches being less resistant @Greig2022.

-   Resource flows decrease the difference in biodiversity and productivity among ecosystems causing: o Lower productivity o Higher α o Lower β

-   Also, our research indicates that γ diversity, as α diversity, can be reduced by differences in patch size. This is because we believe that there is a non linear relationship between the size of a patch and its probability of extinction of each species. Species get randomly extinct in what is know as ecological drift. However, the larger the patch, the lower the probability that a species will get extinct. We suppose that the extinction probability of a species declines non linearly in a concave upward sort of way. Therefore, small and large patches will be more likely to have a lower number of species because of the high probability of species getting extinct in the small patch. But also the γ diversity can depend on other factors. For example, it is possible that when we have a large predator, mediums patches might not be large enough. Therefore, a larger predator might benefit from a large and small patches so that it can reside in the larger patch. The explanation for this is as follows. As the size-biodiversity relationship is concave, the mean biodiversity between small and large patches will be lower than in two medium patches. For example, at the end of the experiment the mean biodiversity of small patches was ... the mean biodiversity of medium patches was ... and the mean biodiversity of large patches was ... As species get lost at random, the union of the species in a small and a large patch will be higher than the union of the species in two medium patches.

-   Finally, our investigation shows that the productivity of the meta-ecosystem, in contrast, can be left unchanged by differences in patch size, even if biodiversity is changed. This is interesting because it seems like first size-biomass relationship is convex, making the small-large isolated system more productive, it seems like connecting the small and large patch changes such relationship to a linear relationship, where whether the meta-ecosystem is a medium-medium or a small-large doesn't matter. Such a linear relationship comes from the fact that the small ecosystem becomes more productive because its connection to the large ecosystem and the large ecosystem becomes less productive because connected to the small ecosystem. In other words, it seems like resource flow between ecosystems of different size defeats the non-linearity of the patch size - productivity relationship. Therefore, it seems that when flows of resources are exchanged between ecosystems they make the relative size of the ecosystems not important for their overall productivity. Furthermore, we can say that it's not uncommon for diversity to change but not their productivity (ref).

-   CONCLUSION In conclusion, what we found has a direction implication for the study of meta-ecosystem biodiversity and productivity. It does as well for subsidies research, as it highlights how the size of the connected patch can be driving the effects of subsidies. As all ecosystems in nature differ in their size, we see a great application potential of our research. It also helps us integrating a feature of natural ecosystems and moving a step closer to integrating realistic features in meta-ecosystem theory. We believe that our work is really important in bringing us a step closer to be able to use meta-ecosystem theory for the management of real world systems. Therefore, to understand the biodiversity of a landscape requires us to know the variance in the size of it constituting patches.

-   To be able to study such effects of resources, \@Loreau2003 introduced a new framework called the meta-ecosystem framework. Therefore, a meta-ecosystem represents a number of ecosystems interconnected through the flow of resources. The meta-ecosystem framework has helped us understand both the productivity and biodiversity within a landscape.

-   In order to fully grasp our findings, it's essential to become familiar with a fundamental concept called Jensen's inequality. This principle provides an elegant approach to examining the influence of variance on non-linear relationships. Jensen's inequality asserts that when there's a non-linear relationship between a predictor variable (x) and a dependent variable (y), the sum of the function of several values differs from the function applied to the mean of those values. Put formally, $f(\overline{x}) ≠ f(x_1) + f(x_2) + … + f(x_n)$ where $n$ is the number of values. The variance in the predictor variable x exerts a contrasting effect depending on whether the relationship is concave or convex. Specifically, in concave relationships, a greater variance decreases the dependent variable, while in convex relationships, it enhances it \@Jensen1906. For instance, \@BenedettiCecchi2005 investigated the impact of biodiversity variance on productivity. Given that most biodiversity-productivity relationships were concave, he discovered that among two landscapes composed of patches with the same average biodiversity, the one with a higher variance in biodiversity among patches would demonstrate lower productivity. In our study, we explore the effects of patch size variance and its subsequent impact on biodiversity and productivity. [[Tue 20 June]]{.underline}

-   This redistribution of resources results in more homogeneous productivity across patches, which has two implications. They both come from a concave productivity - biodiversity relationship. Firstly, it promotes uniformity in biodiversity across patches, thereby reducing β diversity. Secondly, a smaller variation in productivity should lead to an increase in α diversity due to Jensen's inequality. In our experiment, resource flow didn't impact γ diversity. We hypothesize this occurred because the resource flow didn't significantly influence α diversity. We speculate that in natural systems, if the resource flow were to exhibit a strong enough effect on α diversity, it could potentially affect γ diversity. Hence, through altering productivity, resource exchange can lessen the impact of patch size on biodiversity. [[Tue 20 June]]{.underline}

-   We hypothesise that patch size asymmetry influenced biodiversity and productivity because of the non-linearity of the relationships between size and diversity, as well as between size and productivity. We think that the decrease in α diversity is linked to the concave relationship between patch size and biodiversity, explained by Jensen's inequality. The reduction in γ diversity is attributed to a diminished mean α diversity, which results in a smaller pool of species and subsequently, fewer unique species on average in the meta-ecosystem. Finally, the increase in β diversity is due to the differences in species richness among patches of different sizes and hence, variations in species composition. Thus, the biodiversity within a meta-ecosystem is influenced by patch size asymmetry, mediated through the relationship between patch size and biodiversity. [I think it would be important to provide an explanation for the patterns that we see, but I'm not sure if all the explanation in a single paragraph is the best way to go about]

-   However, previous studies examining the impact of resource flows on biodiversity and productivity have focused on resource transfers occurring between ecosystems of equal size. This limitation presents a significant challenge in comprehending the effects of resource flows on real-world landscapes.

-   We know that the size of ecosystems is important. We have studied it widely. We know that bigger areas contain more species because they have more species immigrating into them and because their populations get extinct more rarely @MacArthur1963. Furthermore, we know that the size of ecosystems is important for populations to disperse, such as fore example, so that they can disperse enough so that their population doesn't decline because of inbreeding @Saccheri1998. This has implications for the way we manage our ecosystems, restore them and protect biodiversity. However, not much thought has been given to how patch size regulates the flows of resources between different ecosystems. Flows of resources are important. We know it because of many multiple things: include here all the different things. Not only this, but also because, they should even be more important than dispersal, as dispersal happens only between ecosystems of the same type and rarely, exchanges of resource happen often and between ecosystems of different types as well.

-   Ecosystem productivity and biodiversity are fundamental to the health and persistence of ecosystems, as they enable the continuous delivery of ecosystem services essential for the functioning of human societies. In recent decades, ecologists have made significant strides in comprehending how productivity and biodiversity are impact of resource exchange between ecosystems. Notably, redirecting resource flows to the most efficient ecosystem has the potential to enhance productivity \@Harvey2021. Moreover, resource flow can increase productivity by redistributing multiple nutrients that would otherwise be divided among different ecosystems, thereby alleviating co-limitations \@Gulzow2019.

    ### 
