---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

```{r}

# Modify dataset

# ds_patches_modified = ds_patches %>%
#   mutate(patch_type = case_when(
#     patch_type == "Small unconnected" ~ "Small unconnected",
#     patch_type == "Large unconnected" ~ "Large unconnected",
#     patch_type == "Small connected to large" ~ "Small connected to large",
#     patch_type == "Small connected to small" ~ "Small connected to small",
#     patch_type == "Large connected to small" ~ "Large connected to small",
#     patch_type == "Large connected to large" ~ "Large connected to large"
#   ))
```


```{r}

# Construct plots

patch_type_input = c("Small connected to large",
                     "Small connected to small",
                     "Small unconnected",
                     "Large connected to small",
                     "Large connected to large",
                     "Large unconnected")

plot.single.plot = function(response_variable){
  
  ds_patches %>%
    filter(
      patch_type %in% patch_type_input,
      !is.na(!!sym(response_variable))
    ) %>%
    summarySE(measurevar = response_variable,
              groupvars = c("day", "time_point", "patch_type", "patch_size", "connection")) %>%
    ggplot(aes(
      x = day,
      y = get(response_variable),
      group = interaction(day, patch_type),
      color = patch_type,
      linetype = patch_type
    )) +
    geom_point(
      stat = "summary",
      fun = "mean",
      position = position_dodge(dodging),
      size = treatment_points_size
      ) +
    geom_line(
      stat = "summary",
      fun = "mean",
      aes(group = patch_type),
      position = position_dodge(dodging),
      linewidth = treatment_lines_linewidth
      ) +
    geom_errorbar(aes(
      ymax = get(response_variable) + ci,
      ymin = get(response_variable) - ci),
      width = width_errorbar,
      position = position_dodge(dodging)) +
    labs(x = axis_names$axis_name[axis_names$variable == "day"],
         y = axis_names$axis_name[axis_names$variable == response_variable],
         color = "") +
    scale_color_manual(
      values = c(
        "#993404",
        "#993404",
        "#993404",
        "#3182bd",
        "#3182bd",
        "#3182bd"
      ),
      label = expression(
        S[L], 
        S[S],
        S,
        L[L], 
        L[S], 
        L
      )
    ) +
    scale_linetype_manual(
      values = c(
        "solid",
        "dotted",
        "dashed",
        "solid",
        "dotted",
        "dashed"
      ),
      label = expression(
        S[L], 
        S[S],
        S,
        L[L], 
        L[S], 
        L
      )
    ) +
    geom_vline(
      xintercept = resource_flow_days,
      linetype = resource_flow_line_type,
      color = resource_flow_line_colour,
      linewidth = resource_flow_line_width
    ) +
    geom_hline(
      yintercept = 0,
      color = zero_line_colour,
      linetype = zero_line_line_type,
      linewidth = zero_line_line_width
    ) +
    theme_bw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = legend_position,
      legend.key.width = unit(legend_width_cm, "cm")
    ) +
    guides(
      color = guide_legend(title = NULL,
                           nrow = 3),
      linetype = guide_legend(title = NULL,
                              nrow = 3)
      ) + 
    geom_rect(
      xmin = grey_background_xmin, 
      xmax = grey_background_xmax,
      ymin = grey_background_ymin, 
      ymax = grey_background_ymax, 
      fill = grey_background_fill, 
      alpha = grey_background_alpha,
      color = grey_background_color
      )
}
```

```{r}

# Combine plots

p_combined = ggarrange(
  plot.single.plot("shannon") +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank()) +
    font("legend.text", size = size_legend) +
    font("ylab", size = paper_y_axis_size),
  plot.single.plot("bioarea_mm2_per_ml") +
    font("legend.text", size = size_legend) +
    font("xlab", size = paper_y_axis_size) +
    font("ylab", size = paper_y_axis_size) +
    scale_x_continuous(breaks = unique(ds_patches$day)),
  heights = c(0.8, 0.8, 1),
  nrow = 2,
  align = "v",
  labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8,
  common.legend = TRUE
)
```

```{r fig.height = figures_height_rmd_output}

# Show combined plots

p_combined
```

```{r results=FALSE}

# Save combined plots

png(
  file = here("results", "figures", disturbance_global_input, "paper", "connected_patches.png"),
  width = paper_width,
  height = paper_height,
  units = paper_units,
  res = paper_res
)

p_combined

dev.off()
```