---
title: "parameters"
output: html_document
date: "2023-02-08"
editor_options: 
  chunk_output_type: console
---

```{r experiment}
#Disturbance parameters
disturbance_levels = c("low", "high")
n_disturbance_levels = length(disturbance_levels)

#Protist parameters
protist_species = c("Ble", "Cep", "Col", "Eug", "Eup", "Lox", "Pau", "Pca", "Spi", "Spi_te", "Tet")
protist_species_indiv_per_ml = paste0(protist_species, "_indiv_per_ml")
protist_species_dominance = paste0(protist_species_indiv_per_ml, "_dominance")
protist_species_total = paste0(protist_species, "_tot_indiv")
n_protist_species = length(protist_species)
first_protist = protist_species[1]
last_protist = protist_species[n_protist_species]
protists_low_threshold_analysis = c("Col", "Eug", "Eup", "Lox", "Pau", "Pca", "Spi_te", "Tet")
protists_high_threshold_analysis = c("Ble", "Cep", "Spi")

#Patches parameters 
culture_info = read.csv(here("data", "PatchSizePilot_culture_info.csv"), header = TRUE)
n_cultures = max(culture_info$culture_ID)
patch_types = c("Small isolated",
                "Small connected to small",
                "Small connected to large",
                "Medium isolated",
                "Medium connected to medium",
                "Large isolated",
                "Large connected to large",
                "Large connected to small")
patches_to_take_off = 60 #Culture ID = 60 because it was spilled (small isolated @ high disturbance, system nr = 40)

#Define treatments and controls
treatments_and_controls = data.frame(
  treatment = c(
    "Small connected to small",
    "Small connected to large",
    "Medium connected to medium",
    "Large connected to large",
    "Large connected to small"
  ),
  control = c(
    "Small isolated",
    "Small isolated",
    "Medium isolated",
    "Large isolated",
    "Large isolated"
  )
)
n_treatments = length(unique(treatments_and_controls$treatment))
n_controls = length(unique(treatments_and_controls$control))

#Meta-ecosystems parameters
system_nr_metaecosystems = culture_info %>%
  filter(metaecosystem == "yes") %>%
  pull(system_nr) %>%
  unique

n_metaecosystems = length(system_nr_metaecosystems)

metaecosystem_type_ordered = 

metaecosystems_to_take_off = culture_info %>%
  filter(culture_ID %in% patches_to_take_off) %>%
  pull(system_nr) %>%
  unique
 
#Sampling parameters
total_frames = 125
volume_recorded_μl = 34.4
time_points = 0:7
time_point_names = c("t0", "t1", "t2", "t3", "t4", "t5", "t6", "t7")
sampling_days = c(0, 4, 8, 12, 16, 20, 24, 28)
first_time_point = 0
last_time_point = length(sampling_days) - 1
n_time_points = last_time_point + 1
nr_videos = c(12,1,1,1,1,1,2,2) #Videos taken for each time point for each culture. At t0 we took 12 videos of the large bottle from which we started the  cultures. Write why 2 at the end. 

videos_taken = data.frame(
  time_point = 0:7,
  nr_videos = c(12,1,1,1,1,1,2,2)
)

n_videos_taken_t0 = nr_videos[1]
time_point_day = data.frame(
  time_point = first_time_point:last_time_point,
  day = sampling_days
)
videos_to_take_off = data.frame(culture_ID = NA,
                                time_point = NA,
                                file = NA) %>%
  add_row(culture_ID = 137-110, time_point = 7, file = 137) %>%
  slice(-1)
total_number_of_video_rows = (12*110) + (110*5) + (220*2)

#Resource flow parameters
resource_flow_days = c(5, 9, 13, 17, 21, 25)
first_resource_flow = resource_flow_days[1]

#Columns without baseline
columns_patches = c(
  "time_point",
  "day",
  "culture_ID",
  "system_nr",
  "disturbance",
  "patch_type",
  "patch_size",
  "patch_size_ml",
  "size_connected_patch",
  "metaecosystem",
  "metaecosystem_type"
)

columns_treatments = columns_patches[!columns_patches %in% c("system_nr", "culture_ID")]

columns_classes = c(columns_patches,
                    "size_class_n",
                    "mean_class_area_µm2")

#Variables whose effect size I want to calculate
variables_patches = c(
  "bioarea_mm2_per_ml",
  "bioarea_tot_mm2",
  "indiv_per_ml",
  "indiv_tot",
  "species_richness",
  "shannon",
  "simpson",
  "inv_simpson",
  "evenness_pielou",
  "beta_diversity_from_isolated",
  "beta_diversity_from_previous_time",
  "median_body_area_µm2",
  paste0(protist_species, "_indiv_per_ml"),
  paste0(protist_species, "_tot_indiv"),
  paste0(protist_species_indiv_per_ml, "_dominance")
)

baseline_columns = paste0("baseline_", variables_patches)

#Variables I want to calculate for meta-ecosystems
variables_metaecos = c(
  "total_metaecosystem_bioarea_mm2",
  "jaccard_index",
  "bray_curtis",
  "metaecosystem_richness"
)

#Modeling parameters. We chose the first time point as 2 because it's after the first disturbance. 
first_time_point_model = 2
last_time_point_model = last_time_point

#Size classes
n_size_classes = 12
```

```{r}
#Parameters for general plotting 
dodging = 0.5 
dodging_error_bar = 0.5
width_errorbar = 0.2
boxplot_width = 2
legend_position = "top"

#Axes names
axis_names = data.frame(variable = NA,
                        axis_name= NA) %>%
  add_row(variable = "day", axis_name = "Time (day)") %>%
  add_row(variable = "patch_size_ml", axis_name = "Patch size (ml)") %>%
  add_row(variable = "log_size_class", axis_name = "Log size (μm2)") %>%
  add_row(variable = "class_indiv_per_µl", axis_name = "Density (ind/ml)") %>%
  add_row(variable = "bioarea_mm2_per_ml", axis_name = "Bioarea density (mm²/ml)") %>%
  add_row(variable = "bioarea_mm2_per_ml_d", axis_name = "Bioarea Density ES") %>%
  add_row(variable = "bioarea_tot", axis_name = "Tot Bioarea (mm²)") %>%
  add_row(variable = "total_metaecosystem_bioarea_mm2", axis_name = "Tot Bioarea (mm²)") %>%
  add_row(variable = "species_richness", axis_name = "Species Richness") %>%
  add_row(variable = "species_richness_d", axis_name = "Species Richness ES") %>%
  add_row(variable = "mean_richness", axis_name = "mean α Diversity (Shannon)") %>%
  add_row(variable = "mean_shannon", axis_name = "mean α Diversity (Shannon)") %>%
  add_row(variable = "shannon", axis_name = "Biodiversity (Shannon)") %>%
  add_row(variable = "shannon_d", axis_name = "Biodiversity ES (Shannon ES)") %>%
  add_row(variable = "bray_curtis", axis_name = "β Diversity (Bray-Curtis)") %>%
  add_row(variable = "metaecosystem_richness", axis_name = "γ Diversity (Species Richness)") %>%
  add_row(variable = "indiv_per_ml", axis_name = "Abundance (ind/ml)") %>%
  add_row(variable = "indiv_per_ml_d", axis_name = "Abundance ES") %>%
  add_row(variable = "median_body_area_µm2", axis_name = "Median body size (µm²)") %>%
  add_row(variable = "median_body_area_µm2_d", axis_name = "Median Body Size ES") %>%
  add_row(variable = "Ble_indiv_per_ml", axis_name = "Ble Density (ind/ml)") %>% 
  add_row(variable = "Cep_indiv_per_ml", axis_name = "Cep Density (ind/ml)") %>%
  add_row(variable = "Col_indiv_per_ml", axis_name = "Col Density (ind/ml)") %>%
  add_row(variable = "Eug_indiv_per_ml", axis_name = "Eug Density (ind/ml)") %>%
  add_row(variable = "Eup_indiv_per_ml", axis_name = "Eup Density (ind/ml)") %>%
  add_row(variable = "Lox_indiv_per_ml", axis_name = "Lox Density (ind/ml)") %>%
  add_row(variable = "Pau_indiv_per_ml", axis_name = "Pau Density (ind/ml)") %>%
  add_row(variable = "Pca_indiv_per_ml", axis_name = "Pca Density (ind/ml)") %>%
  add_row(variable = "Spi_indiv_per_ml", axis_name = "Spi Density (ind/ml)") %>%
  add_row(variable = "Spi_te_indiv_per_ml", axis_name = "Spi te Density (ind/ml)") %>%
  add_row(variable = "Tet_indiv_per_ml", axis_name = "Tet Density (ind/ml)") %>%
  add_row(variable = "Ble_indiv_per_ml_d", axis_name = "Ble Density ES") %>%
  add_row(variable = "Cep_indiv_per_ml_d", axis_name = "Cep Density ES") %>%
  add_row(variable = "Col_indiv_per_ml_d", axis_name = "Col Density ES") %>%
  add_row(variable = "Eug_indiv_per_ml_d", axis_name = "Eug Density ES") %>%
  add_row(variable = "Eup_indiv_per_ml_d", axis_name = "Eup Density ES") %>%
  add_row(variable = "Lox_indiv_per_ml_d", axis_name = "Lox Density ES") %>%
  add_row(variable = "Pau_indiv_per_ml_d", axis_name = "Pau Density ES") %>%
  add_row(variable = "Pca_indiv_per_ml_d", axis_name = "Pca Density ES") %>%
  add_row(variable = "Spi_indiv_per_ml_d", axis_name = "Spi Density ES") %>%
  add_row(variable = "Spi_te_indiv_per_ml_d", axis_name = "Spi te Density ES") %>%
  add_row(variable = "Tet_indiv_per_ml_d", axis_name = "Tet Density ES") %>%
  add_row(variable = "Ble_indiv_per_ml_dominance", axis_name = "Ble Dominance (%)") %>%
  add_row(variable = "Cep_indiv_per_ml_dominance", axis_name = "Cep Dominance (%)") %>%
  add_row(variable = "Col_indiv_per_ml_dominance", axis_name = "Col Dominance (%)") %>%
  add_row(variable = "Eug_indiv_per_ml_dominance", axis_name = "Eug Dominance (%)") %>%
  add_row(variable = "Eup_indiv_per_ml_dominance", axis_name = "Eup Dominance (%)") %>%
  add_row(variable = "Lox_indiv_per_ml_dominance", axis_name = "Lox Dominance (%)") %>%
  add_row(variable = "Pau_indiv_per_ml_dominance", axis_name = "Pau Dominance (%)") %>%
  add_row(variable = "Pca_indiv_per_ml_dominance", axis_name = "Pca Dominance (%)") %>%
  add_row(variable = "Spi_indiv_per_ml_dominance", axis_name = "Spi Dominance (%)") %>%
  add_row(variable = "Spi_te_indiv_per_ml_dominance", axis_name = "Spi te Dominance (%)") %>%
  add_row(variable = "Tet_indiv_per_ml_dominance", axis_name = "Tet Dominance (%)") %>%
  add_row(variable = "Ble_indiv_per_ml_dominance_d", axis_name = "Ble Dominance ES") %>%
  add_row(variable = "Cep_indiv_per_ml_dominance_d", axis_name = "Cep Dominance ES") %>%
  add_row(variable = "Col_indiv_per_ml_dominance_d", axis_name = "Col Dominance ES") %>%
  add_row(variable = "Eug_indiv_per_ml_dominance_d", axis_name = "Eug Dominance ES") %>%
  add_row(variable = "Eup_indiv_per_ml_dominance_d", axis_name = "Eup Dominance ES") %>%
  add_row(variable = "Lox_indiv_per_ml_dominance_d", axis_name = "Lox Dominance ES") %>%
  add_row(variable = "Pau_indiv_per_ml_dominance_d", axis_name = "Pau Dominance ES") %>%
  add_row(variable = "Pca_indiv_per_ml_dominance_d", axis_name = "Pca Dominance ES") %>%
  add_row(variable = "Sp_indiv_per_mli_dominance_d", axis_name = "Spi Dominance ES") %>%
  add_row(variable = "Spi_te_indiv_per_ml_dominance_d", axis_name = "Spi te Dominance ES") %>%
  add_row(variable = "Tet_indiv_per_ml_dominance_d", axis_name = "Tet Dominance ES") %>%
  add_row(variable = "dominance", axis_name = "Dominance (%)") %>%
  add_row(variable = "log_abundance", axis_name = "Log Abundance + 1 (ind/mm²)") %>%
  add_row(variable = "abundance_hedges_d", axis_name = "Density ES") %>%
  add_row(variable = "beta_diversity_from_isolated", axis_name = "Divergence from isolated") %>%
  add_row(variable = "beta_diversity_from_previous_time", axis_name = "Temporal Divergence") %>%
  add_row(variable = "beta_diversity_from_previous_time_d", axis_name = "Temporal Divergence ES") %>%
  add_row(variable = "evenness_pielou", axis_name = "Evenness") %>%
  add_row(variable = "evenness_pielou_d", axis_name = "Evenness ES") %>%
  slice(-1)

#Colour for each of the treatments 
parameters_treatments = data.frame(treatment = NA,
                                colour = NA,
                                linetype = NA) %>%
  add_row(treatment = "Small isolated", colour = "#bdbdbd", linetype = "solid") %>% 
  add_row(treatment = "Small connected to small", colour = "#feb24c", linetype = "twodash") %>%
  add_row(treatment = "Small connected to large", colour = "#feb24c", linetype = "solid") %>%
  add_row(treatment = "Medium isolated", colour = "#737373", linetype = "solid") %>%
  add_row(treatment = "Medium connected to medium", colour = "#feb24c", linetype = "solid") %>%
  add_row(treatment = "Large isolated", colour = "#000000", linetype = "solid") %>%
  add_row(treatment = "Large connected to large", colour = "#3182bd", linetype = "twodash") %>%
  add_row(treatment = "Large connected to small", colour = "#3182bd", linetype = "solid") %>%
  add_row(treatment = "Small-Small meta-ecosystem", colour = "#fc9272", linetype = "solid") %>%
  add_row(treatment = "Medium-Medium meta-ecosystem", colour = "#1b7837", linetype = "solid") %>%
  add_row(treatment = "Medium-Medium isolated", colour = "#1b7837", linetype = "dashed") %>%
  add_row(treatment = "Large-Large meta-ecosystem", colour = "#67000d", linetype = "solid") %>%
  add_row(treatment = "Small-Large meta-ecosystem", colour = "#762a83", linetype = "solid") %>%
  add_row(treatment = "Small-Large isolated", colour = "#762a83", linetype = "dashed") %>%
  slice(-1)

#Mean lines
treatment_lines_linewidth = 1
treatment_points_size = 2.5

#Resource flow line & caption
resource_flow_line_type = "solid"
resource_flow_line_colour = "#d9d9d9"
resource_flow_line_width = 0.3
caption_resource_flow = ""

#Zero line  
zero_line_colour = "grey"
zero_line_line_type = "dotted"
zero_line_line_width = 0.5

#Zero line  ES
zero_line_ES_line_type = "dotted"
zero_line_ES_colour = "grey"
zero_line_ES_line_width = 1

#Paper
size_legend = 12
size_x_axis = 16
size_y_axis = 14
legend_width_cm = 2
paper_width = 17.3
paper_height = 20
paper_units = "cm"
paper_res = 600

#Presentation
presentation_legend_size = 20
presentation_x_axis_size = 20
presentation_y_axis_size = presentation_x_axis_size
presentation_legend_width_cm = 3
presentation_figure_width = 30
presentation_figure_height = 22
presentation_figure_units = "cm"
presentation_figure_size = 15
presentation_figure_res = 600
presentation_size = 15
presentation_treatment_points_size = 5
presentation_treatment_linewidth = 2


ggarrange_margin_top = 0
ggarrange_margin_bottom = 0
ggarrange_margin_left = 0
ggarrange_margin_right = 0
```

```{r}
results_table = data.frame(
  Response = as.character(NA),
  Levels = as.character(NA),
  ΔAIC_full = NA,
  p_full = NA,
  ΔR2_full = NA,
  ΔAIC_fix = NA,
  p_fix = NA,
  ΔR2_fix = NA
) %>%
  slice(-1)

iterated_results_table = data.frame(
  Response = as.character(NA),
  Levels = as.character(NA),
  ΔAIC_full = NA,
  p_full = NA,
  ΔR2_full = NA,
  ΔAIC_fix = NA,
  p_fix = NA,
  ΔR2_fix = NA,
  combination_set = NA
) %>%
  slice(-1)
```