---
title: "Population abundances in small patches"
author: "Emanuele Giacomuzzo"
date: "2022-10-17"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Small patches {.tabset .tabset-pills}

```{r}
patch_size_input = "S"
```

#### Boxplots {.tabset .tabset-pills}

##### Low disturbance

```{r}
disturbance_input = "low"
```

```{r}
for (species_input in 1:n_protist_species) {
  print(
    ds_patches %>%
      pivot_longer(Ble:Tet,
                   names_to = "species",
                   values_to = "population_abundance") %>%
      filter(
        disturbance == disturbance_input,
        patch_size == patch_size_input,
        species == protist_species[species_input]
      ) %>%
      ggplot(
        aes(
          x = day,
          y = population_abundance,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot() +
      labs(
        title = paste0(protist_species[species_input], " (Disturbance = ", disturbance_input, ")"),
        x = "Day",
        y = "Abundance (indiv/μl ?)",
        fill = ""
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          "Small isolated",
          "Small connected to large",
          "Small connected to small"
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      labs(caption = "Vertical grey line: resource flow")
  )
  
}
```

##### High disturbance

```{r}
disturbance_input = "high"
```

```{r}
for (species_input in 1:n_protist_species) {
  print(
    ds_patches %>%
      pivot_longer(Ble:Tet, 
                   names_to = "species", 
                   values_to = "population_abundance") %>%
      filter(disturbance == disturbance_input,
             patch_size == patch_size_input,
             species == protist_species[species_input]) %>%
      ggplot(
        aes(
          x = day,
          y = population_abundance,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot() +
      labs(
        title = paste0(protist_species[species_input], " (Disturbance = ", disturbance_input, ")"),
        x = "Day",
        y = "Abundance (indiv/μl ?)",
        fill = "",
        caption = "Vertical grey line: resource flow"
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      scale_fill_manual(
        values = c(colour_isolated, colour_different_size, colour_same_size),
        labels = c(
          "Small isolated",
          "Small connected to large",
          "Small connected to small"
        )
      )  +
      scale_x_continuous(breaks = unique(ds_patches$day)) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      )
  )
}
```

#### Effect sizes {.tabset .tabset-pills}

##### Low disturbance

```{r}
disturbance_input = "low"
```

```{r}
ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Ble_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Ble_d_lower,
            ymax = Ble_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Ble Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Ble_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Ble_d_lower,
            ymax = Ble_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Ble Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Cep_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Cep_d_lower,
            ymax = Cep_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Cep Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Col_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Col_d_lower,
            ymax = Col_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Col Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Eug_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Eug_d_lower,
            ymax = Eug_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Eug Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Eup_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Eup_d_lower,
            ymax = Eup_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Eup Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Lox_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Lox_d_lower,
            ymax = Lox_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Lox Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Pau_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Pau_d_lower,
            ymax = Pau_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Pau Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Pca_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Pca_d_lower,
            ymax = Pca_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Pca Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Spi_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Spi_d_lower,
            ymax = Spi_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Spi Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Spi_te_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Spi_te_d_lower,
            ymax = Spi_te_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Spi_te Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Tet_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Tet_d_lower,
            ymax = Tet_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Tet Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )
```

##### High disturbance

```{r}
disturbance_input = "high"
```

```{r}
ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Ble_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Ble_d_lower,
            ymax = Ble_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Ble Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Ble_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Ble_d_lower,
            ymax = Ble_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Ble Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Cep_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Cep_d_lower,
            ymax = Cep_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Cep Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Col_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Col_d_lower,
            ymax = Col_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Col Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Eug_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Eug_d_lower,
            ymax = Eug_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Eug Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Eup_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Eup_d_lower,
            ymax = Eup_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Eup Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Lox_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Lox_d_lower,
            ymax = Lox_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Lox Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Pau_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Pau_d_lower,
            ymax = Pau_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Pau Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Pca_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Pca_d_lower,
            ymax = Pca_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Pca Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Spi_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Spi_d_lower,
            ymax = Spi_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Spi Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Spi_te_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Spi_te_d_lower,
            ymax = Spi_te_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Spi_te Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )

ds_patches_averaged %>%
      filter(disturbance == disturbance_input,
             eco_metaeco_type %in% c("S (S_L)", "S (S_S)"),
             day > 0) %>%
      ggplot(aes(
        x = day,
        y = Tet_d,
        color = eco_metaeco_type
      )) +
      geom_point(position = position_dodge(0.5)) +
      geom_line(position = position_dodge(0.5)) +
      geom_errorbar(
        aes(ymin = Tet_d_lower,
            ymax = Tet_d_upper),
        width = .2,
        position = position_dodge(0.5)
      ) +
      labs(
        title = paste("Disturbance =", disturbance_input),
        x = "Day",
        y = "Tet Density Effect Size (Hedge's d)",
        color = ""
      ) +
       scale_color_discrete(
         labels = c("Small connected to large",
                    "Small connnected to small")
       ) +
      scale_x_continuous(breaks = unique(ds_patches_averaged$day)) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = resource_flow_days[1] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[2] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[3] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[4] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[5] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_vline(
        xintercept = resource_flow_days[6] + 0.7,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "black",
        size = 0.7
      )
```

#### Model

```{r}
first_time_point = 2
last_time_point = 7

filtered_data = ds_patches_averaged %>%
                         filter(time_point >= first_time_point,
                                time_point <= last_time_point,
                                eco_metaeco_type %in% c("S (S_S)","S (S_L)"))
```

##### Ble

```{r}

#Test hp 

full_model = lm(Ble_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Ble_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)
p_value
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

##### Cep

```{r}

#Test hp 

full_model = lm(Cep_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Cep_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

##### Col

```{r}

#Test hp 

full_model = lm(Col_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Col_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

```{r}
R2_full = glance(full_model)$r.squared
no_patch_type = lm(bioarea_per_volume_d ~
                  day + 
                  disturbance,
                  data = ds_patches_averaged %>%
                         filter(time_point >= first_time_point) %>%
                         filter(time_point <= last_time_point) %>%
                         filter(eco_metaeco_type== "S (S_S)" | eco_metaeco_type == "S (S_L)"))

R2_null = glance(null_model)$r.squared
R2_P = R2_full - R2_null

R2_full = round(R2_full, digits = 2)
R2_P = round(R2_P, digits = 2)
```

##### Eug

```{r}

#Test hp 

full_model = lm(Eug_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Eug_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

##### Eup

```{r}

#Test hp 

full_model = lm(Eup_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Eup_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

##### Lox

```{r}

#Test hp 

full_model = lm(Lox_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Lox_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

##### Pau

```{r}

#Test hp 

full_model = lm(Pau_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Pau_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

##### Pca

```{r}

#Test hp 

full_model = lm(Pca_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Pca_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

##### Spi

```{r}

#Test hp 

full_model = lm(Spi_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Spi_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova

p_value = anova$`Pr(>F)`[2]
p_value = round(p_value, digits = 3)
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

```{r}
R2_full = glance(full_model)$r.squared
no_patch_type = lm(bioarea_per_volume_d ~
                  day + 
                  disturbance,
                  data = ds_patches_averaged %>%
                         filter(time_point >= first_time_point) %>%
                         filter(time_point <= last_time_point) %>%
                         filter(eco_metaeco_type== "S (S_S)" | eco_metaeco_type == "S (S_L)"))

R2_null = glance(null_model)$r.squared
R2_P = R2_full - R2_null

R2_full = round(R2_full, digits = 2)
R2_P = round(R2_P, digits = 2)
```

-   p value of patch type: `r p-value`

-   R2 of patch type: `r R2_P`

##### Spi te

```{r}

#Test hp 

full_model = lm(Spi_te_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Spi_te_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

##### Tet

It doesn't work.

```{r eval = FALSE}

#Test hp 

full_model = lm(Tet_d ~                  
                  day + 
                  eco_metaeco_type + 
                  disturbance +
                  day : eco_metaeco_type +
                  day : disturbance + 
                  eco_metaeco_type : disturbance +
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

null_model = lm(Cep_d ~                  
                  day + 
                  disturbance +
                  day : disturbance + 
                  baseline_bioarea + 
                  day : baseline_bioarea,
                  data = filtered_data)

AIC(full_model, null_model)

anova = anova(full_model, null_model)
anova
```

```{r}

#Model diagnostics

par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```
