---
title: "What drives productivity?"
output: html_document
date: "2023-01-31"
editor_options: 
  chunk_output_type: console
---

### Species richness {.tabset .tabset-pills}

#### All data points

```{r}
ds_patches %>%
  ggplot(aes(x = species_richness,
             y = bioarea_mm2_per_ml)) +
  geom_point()
```

Small patches

```{r}

for(species_richness_input in 1:n_protist_species){
  
  print(ds_patches %>%
     filter(patch_size == "Small") %>%
     ggplot(aes(x = patch_type,
                y = bioarea_mm2_per_ml,
                fill = patch_type)) +
     geom_boxplot()) +
    labs(title = paste("Species richness = ", species_richness_input),
         x = "") +
    theme(axis.text.x = element_blank())
  
}
```

```{r}
ds_patches %>%
  filter(patch_size == "Small") %>%
  ggplot(aes(x = species_richness,
             y = bioarea_mm2_per_ml,
             group = interaction(species_richness, patch_type),
             fill = patch_type)) +
  geom_boxplot()
```

Large

```{r}
ds_patches %>%
  filter(patch_size == "Large",
         species_richness > 3,
         species_richness < 11) %>%
  ggplot(aes(x = species_richness,
             y = bioarea_mm2_per_ml,
             group = interaction(species_richness, patch_type),
             fill = patch_type)) +
  geom_boxplot()
```





#### Single treatments & time points {.tabset .tabset-pills}

##### Small isolated

```{r}
plot.relationship.BEF("Small isolated",
                      "species_richness")
```

##### Medium isolated

```{r}
plot.relationship.BEF("Medium isolated",
                      "species_richness")
```

##### Large isolated

```{r}
plot.relationship.BEF("Large isolated",
                      "species_richness")
```

##### Small connected to large

```{r}
plot.relationship.BEF("Small connected to large",
                      "species_richness")
```

##### Large connecred to small

```{r}
plot.relationship.BEF("Large connected to small",
                      "species_richness")
```

### Species richness {.tabset .tabset-pills}

#### All data points

```{r}
ds_metaecosystems %>%
  filter(metaecosystem_type %in% c("Small-Large isolated",
                                   "Medium-Medium isolated")) %>%
  ggplot(aes(x = mean_shannon,
             y = total_metaecosystem_bioarea_mm2,
             color = metaecosystem_type)) +
  geom_point()
```

```{r}
ds_metaecosystems %>%
  filter(metaecosystem_type %in% c("Small-Large meta-ecosystem",
                                   "Medium-Medium meta-ecosystem")) %>%
  ggplot(aes(x = mean_shannon,
             y = total_metaecosystem_bioarea_mm2,
             color = metaecosystem_type)) +
  geom_point()
```

```{r}
ds_metaecosystems %>%
  filter(metaecosystem_type %in% c("Small-Large meta-ecosystem",
                                   "Small-Large isolated")) %>%
  ggplot(aes(x = mean_shannon,
             y = total_metaecosystem_bioarea_mm2,
             color = metaecosystem_type)) +
  geom_point()
```

```{r}
ds_metaecosystems %>%
  filter(metaecosystem_type %in% c("Medium-Medium meta-ecosystem",
                                   "Medium-Medium isolated")) %>%
  ggplot(aes(x = mean_shannon,
             y = total_metaecosystem_bioarea_mm2,
             color = metaecosystem_type)) +
  geom_point()
```