---
title: "What drives productivity?"
output: html_document
date: "2023-01-31"
editor_options: 
  chunk_output_type: console
---

### Species dominance {.tabset .tabset-pills}

#### All data points

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Ble_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Cep_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Col_dominance,
             y = bioarea_per_volume)) +
  geom_point()
ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Eug_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Eup_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Lox_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Pau_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Pca_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Spi_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Spi_te_dominance,
             y = bioarea_per_volume)) +
  geom_point()

ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  ggplot(aes(x = Tet_dominance,
             y = bioarea_per_volume)) +
  geom_point()
```

#### Single treatments & time points {.tabset .tabset-pills}

```{r}
data = ds_patches %>%
  select(eco_metaeco_type,
         time_point,
         bioarea_per_volume,
         Ble_dominance:Tet_dominance) %>%
  rename(
    Ble = Ble_dominance,
    Cep = Cep_dominance,
    Col = Col_dominance,
    Eug = Eug_dominance,
    Eup = Eup_dominance,
    Lox = Lox_dominance,
    Pau = Pau_dominance,
    Pca = Pca_dominance,
    Spi = Spi_dominance,
    Spi_te = Spi_te_dominance,
    Tet = Tet_dominance
  ) %>%
  pivot_longer(Ble:Tet,
               names_to = "species",
               values_to = "dominance")

#plot_time_points = function(patch_type){
#  
#  for(time_point_input in first_time_point + 1:last_time_point) {
#    
#    print(data %>%
#      filter(eco_metaeco_type == patch_type,
#             time_point == time_point_input) %>%
#      ggplot(aes(x = dominance,
#                 y = bioarea_per_volume)) +
#      geom_point() +
#      facet_wrap( ~ species) +
#      labs(title = paste0("Patch type = ",
#                          patch_type,
#                          ", Day = ",
#                          time_point_input * 4)))
#  }
#  
#}
#plot_time_points("S")
#plot_time_points("M")
#plot_time_points("L")

plot_species = function(patch_type) {
  for (species_input in protist_species) {
    print(
      data %>%
        filter(eco_metaeco_type == patch_type,
               species == species_input) %>%
        ggplot(aes(x = dominance,
                   y = bioarea_per_volume)) +
        geom_point() +
        facet_wrap(~ time_point) +
        labs(title = paste0(
          species_input,
          " (Patch type = ",
          patch_type,
          ")"
        ))
    )
  }
}
```

##### S

```{r}
plot_species("S")
```

##### M

```{r}
plot_species("M")
```

##### L

```{r}
plot_species("L")
```

##### S connected to L

```{r}
plot_species("S (S_L)")
```

##### L connected to S

```{r}
plot_species("L (S_L)")
```