---
title: "What drives productivity?"
output: html_document
date: "2023-01-31"
editor_options: 
  chunk_output_type: console
---

### Shannon index {.tabset .tabset-pills}

#### All data points

```{r}
ds_patches %>%
  ggplot(aes(x = shannon,
             y = bioarea_mm2_per_ml)) +
  geom_point()
```

Small patches

```{r}
ds_patches %>%
  filter(patch_size == "Small") %>%
  ggplot(aes(x = shannon,
             y = bioarea_mm2_per_ml,
             color = patch_type)) +
  geom_point()
```

Large

```{r}
ds_patches %>%
  filter(patch_size == "Large") %>%
  ggplot(aes(x = shannon,
             y = bioarea_mm2_per_ml,
             color = patch_type)) +
  geom_point()
```



#### Single treatments & time points {.tabset .tabset-pills}

##### Small isolated

```{r}
plot.relationship.BEF("Small isolated",
                      "shannon")
```

##### Medium isolated

```{r}
plot.relationship.BEF("Medium isolated",
                      "shannon")
```

##### Large isolated

```{r}
plot.relationship.BEF("Large isolated",
                      "shannon")
```

##### Small connected to large

```{r}
plot.relationship.BEF("Small connected to large",
                      "shannon")
```

##### Large connecred to small

```{r}
plot.relationship.BEF("Large connected to small",
                      "shannon")
```