---
title: "Paper CHAPTER 1"
output:
  html_document: default
  pdf_document: default
date: "2022-12-16"
editor_options:
  chunk_output_type: console
---

### Tables

```{r child = here("r_files", "results_table_paper_version.Rmd"), eval = show_results}
```

### Figures {.tabset .tabset-pills}

#### Isolated patches

```{r eval = show_results}
compar_ex = "The full and fixed models are compared to the null model."
```

```{r fig-isolated-patches, eval = show_results}
### --- Isolated patches --- ###
ggarrange(
  p_isolated_biomass +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = size_legend) +
    font("ylab", size = size_y_axis), 
  p_isolated_shannon +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = size_y_axis) + 
    font("ylab", size = size_y_axis) +
  scale_x_continuous(breaks = unique(ds_patches$day)),
  nrow = 2,
  heights = c(0.9,1),
  common.legend = TRUE,
  align = "v",
  labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8
)
```

```{r results = FALSE}
dev.copy(png, 
         here("results", "figures", disturbance_global_input, "isolated_patches.png"),
         width = 17.3, 
         height = 17.3, 
         units = "cm", 
         res = 600)
dev.off()
```

```{r}
results_table %>%
  arrange(Response, 
          Levels) %>%
  filter(Levels == "Isolated patches") %>%
  mutate(ΔR2_full = NULL,
         ΔR2_int = NULL,
         ΔR2_fix = NULL) %>%
  select(-Levels) %>%
  kbl(caption = paste(
     "Table 1. 
     Isolated patches results. 
     The full model included patch size and its interaction with time. 
     The fixed model did not include such interaction.", 
     compar_ex
    )) %>%
  kable_styling()
```

#### Two-patch systems

```{r}
### --- Meta-ecosystem productivity --- ###
p_MM_SL_metaecos_biomass +
  theme(
  axis.title.y = element_text(size = size_y_axis),
  legend.text = element_text(size = size_legend)
)
```

```{r results = FALSE}
dev.copy(png, 
         here("results", "figures", disturbance_global_input, "tot_bioarea.png"),
         width = 17.3, 
         height = 17.3, 
         units = "cm", 
         res = 600)
dev.off()
```

```{r fig-connected-systems, fig.height = 9, eval = show_results}
### --- Two patch systems --- ###
ggarrange(
  p_MM_SL_metaecos_alpha +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = size_legend) +
    font("ylab", size = size_y_axis),
   p_MM_SL_metaecos_beta +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = size_legend) +
    font("ylab", size = size_y_axis),
  p_MM_SL_metaecos_gamma +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = size_y_axis) +
    font("ylab", size = size_y_axis) +
    scale_x_continuous(breaks = unique(ds_patches$day)),
  heights = c(0.8,0.8,1),
  nrow = 3,
  common.legend = TRUE,
  align = "v",
  labels = c("(a)", "(b)", "(c)"),
  label.x = 0.1,
  label.y = 0.8
) %>%
  print()
```

```{r}
results_table %>%
  arrange(Response, 
          Levels) %>%
  filter(
    Levels %in% c("Metaecos (Small-Large vs Medium-Medium)") & 
      !is.na(Response)
  ) %>%
  mutate(ΔR2_full = NULL,
         ΔR2_int = NULL,
         ΔR2_fix = NULL) %>%
  select(-Levels) %>%
  kbl(
    caption = paste(
      "Table 2. 
      Meta-ecosystems results. 
      The full model included patch size ratio and its interaction with time. 
      The fixed model did not include such interaction.",
      compar_ex
    )
  ) %>%
  kable_styling()

results_table %>%
  arrange(Response, 
          Levels) %>%
  filter(
    Levels %in% c(
      "Small-Large (connect vs isolated)"
    )
  ) %>%
  mutate(ΔR2_full = NULL,
         ΔR2_int = NULL,
         ΔR2_fix = NULL) %>%
  select(-Levels) %>%
  kbl(
    caption = paste(
      "Table 3. 
      Small-Large systems results. 
      The full model included the connection and its interaction with time. 
      The fixed model did not include such interaction.",
      compar_ex
    )
  ) %>%
  kable_styling()

results_table %>%
  arrange(Response, 
          Levels) %>%
  filter(
    Levels %in% c(
      "Medium-Medium (connect vs isolated)"
    )
  ) %>%
  mutate(ΔR2_full = NULL,
         ΔR2_int = NULL,
         ΔR2_fix = NULL) %>%
  select(-Levels) %>%
  kbl(
    caption = paste(
      "Table 4. 
      Medium-Medium systems results. 
      The full model included the connection and its interaction with time. 
      The fixed model did not include such interaction.",
      compar_ex
    )
  ) %>%
  kable_styling()
```

#### Connected patches

```{r}
ggarrange(
  p_connected_biomass_effect_size +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = size_legend) +
    font("ylab", size = size_y_axis), 
  p_connected_shannon_effect_size +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = size_y_axis) + 
    font("ylab", size = size_y_axis) +
    scale_x_continuous(breaks = unique(ds_patches$day)),
  nrow = 2,
  heights = c(0.9,1),
  common.legend = TRUE,
  align = "v",
  labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8
)
```

```{r results = FALSE}
dev.copy(png, 
         here("results", "figures", disturbance_global_input, "connected_patches.png"),
         width = 17.3, 
         height = 17.3, 
         units = "cm", 
         res = 600)
dev.off()
```

```{r fig-connected-patches, eval = show_results}
results_table %>%
  filter(Response %in% c("Bioarea Density ES", 
                         "Shannon Index ES"),
         Levels == "Small (connected to small or large)") %>%
  arrange(Response, 
          Levels) %>%
  select(-Levels) %>%
  kbl(caption = paste(
    "Table 5. 
    Small patches results. 
    The full model included the size of the donor patch and its interaction with time. 
    The fixed model did not include such interaction.", 
    compar_ex)) %>%
  kable_styling()

results_table %>%
  filter(Response %in% c("Bioarea Density ES", 
                         "Shannon Index ES"),
         Levels == "Large (connected to small or large)") %>%
  arrange(Response, 
          Levels) %>%
  select(-Levels) %>%
  kbl(caption = paste(
    "Table 6. 
    Large patches results. 
    The full model included the size of the donor patch and its interaction with time. 
    The fixed model did not include such interaction.",
    compar_ex)) %>%
  kable_styling()
```
