---
title: "Untitled"
output: html_document
date: "2023-08-31"
editor_options: 
  chunk_output_type: console
---

```{r}
compar_ex = "The full and fixed models are compared to the null model."
```

```{r}
### --- Isolated patches - PAPER --- ###
ggarrange(
  p_isolated_biomass +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = size_legend) +
    font("ylab", size = size_y_axis), 
  p_isolated_shannon +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = size_y_axis) + 
    font("ylab", size = size_y_axis) +
  scale_x_continuous(breaks = unique(ds_patches$day)),
  nrow = 2,
  heights = c(0.9,1),
  common.legend = TRUE,
  align = "v",
  labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8
)
```

```{r results = FALSE}
dev.copy(png, 
         here("results", "figures", disturbance_global_input, "paper_isolated_patches.png"),
         width = publication_width, 
         height = publication_height, 
         units = publication_units, 
         res = publication_res)
dev.off()
```

```{r}
results_table %>%
  arrange(Response, 
          Levels) %>%
  filter(Levels == "Isolated patches") %>%
  mutate(ΔR2_full = NULL,
         ΔR2_int = NULL,
         ΔR2_fix = NULL) %>%
  select(-Levels) %>%
  kbl(caption = paste(
     "Table 1. 
     Isolated patches results. 
     The full model included patch size and its interaction with time. 
     The fixed model did not include such interaction.", 
     compar_ex
    )) %>%
  kable_styling()
```

```{r}
### --- Isolated patches - PRESENTATIONS --- ###
ggarrange(
  p_isolated_biomass_presentations +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = presentation_legend_size) +
    font("ylab", size = presentation_y_axis_size), 
  p_isolated_shannon_presentations +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = presentation_x_axis_size) + 
    font("ylab", size = presentation_y_axis_size) +
  scale_x_continuous(breaks = unique(ds_patches$day)),
  nrow = 2,
  heights = c(0.9,1),
  common.legend = TRUE,
  align = "v",
  labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8
)
```

```{r results = FALSE}
dev.copy(png, 
         here("results", "figures", disturbance_global_input, "presentation_isolated_patches.png"),
         width = presentation_figure_width, 
         height = presentation_figure_height, 
         units = presentation_figure_units, 
         res = presentation_figure_res)
dev.off()
```