---
title: "Paper CHAPTER 1"
output:
  html_document: default
  pdf_document: default
date: "2022-12-16"
editor_options:
  chunk_output_type: console
---

```{r}
png(file = here("results", "figures", disturbance_global_input, "paper_connected_patches.png"),
    width = paper_width,
    height = paper_height,
    units = paper_units,
    res = paper_res)

p=ggarrange(
   p_SL_shannon +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = size_legend) +
    font("ylab", size = size_y_axis), 
  p_SL_biomass +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = size_y_axis) + 
    font("ylab", size = size_y_axis) +
    scale_x_continuous(breaks = unique(ds_patches$day)),
  nrow = 2,
  heights = c(0.9,1),
  common.legend = TRUE,
  align = "v",
  labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8
) %>%
  print()
```

```{r results=FALSE}
dev.off()
```

```{r fig.height = 7}
p
```

```{r fig-connected-patches}
results_table %>%
  filter(Response %in% c("Bioarea Density", 
                         "Shannon Index"),
         Levels == "Small (connected to small or large)") %>%
  arrange(Response, 
          Levels) %>%
  select(-Levels) %>%
  kbl(caption = paste(
    "Table 5. 
    Small patches results. 
    The full model included the size of the donor patch and its interaction with time. 
    The fixed model did not include such interaction.", 
    compar_ex)) %>%
  kable_styling()

results_table %>%
  filter(Response %in% c("Bioarea Density", 
                         "Shannon Index"),
         Levels == "Large (connected to small or large)") %>%
  arrange(Response, 
          Levels) %>%
  select(-Levels) %>%
  kbl(caption = paste(
    "Table 6. 
    Large patches results. 
    The full model included the size of the donor patch and its interaction with time. 
    The fixed model did not include such interaction.",
    compar_ex)) %>%
  kable_styling()
```

```{r results=FALSE}
### --- Isolated patches - PRESENTATIONS --- ###

png(file = here("results", "figures", disturbance_global_input, "presentation_connected_patches.png"),
    width = presentation_figure_width, 
         height = presentation_figure_height, 
         units = presentation_figure_units, 
         res = presentation_figure_res)

p=ggarrange(
   p_SL_shannon_presentations +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = presentation_legend_size) +
    font("ylab", size = presentation_y_axis_size), 
  p_SL_biomass_presentations +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = presentation_x_axis_size) + 
    font("ylab", size = presentation_y_axis_size) +
  scale_x_continuous(breaks = unique(ds_patches$day)),
  nrow = 2,
  heights = c(0.9,1),
  common.legend = TRUE,
  align = "v",
  labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8
) %>%
  print()

dev.off()
```