---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

```{r}

# Construct function to create empty plots

plot.empty = function(y_min,
                      y_max){
  
  ds_metaecosystems %>%
  filter(metaecosystem_type %in% metaecosystem_type_i,
         !is.na(!!sym(response_variable))) %>%
  ggplot(
    aes(
      x = day,
      y = get(response_variable),
      group = interaction(day, metaecosystem_type),
      color = metaecosystem_type,
      linetype = metaecosystem_type
    )
  ) +
  geom_point(
    stat = "summary",
    fun = "mean",
    position = position_dodge(dodging),
    size = presentation_treatment_points_size
  ) +
  geom_line(
    stat = "summary",
    fun = "mean",
    aes(group = metaecosystem_type),
    position = position_dodge(dodging),
    linewidth = presentation_treatment_linewidth
  ) +
  xlim(x_min, x_max) +
  ylim(y_min, y_max) +
  labs(x = axis_names$axis_name[axis_names$variable == "day"],
       y = axis_names$axis_name[axis_names$variable == response_variable],
       color = "") +
  geom_vline(
    xintercept = resource_flow_days,
    linetype = resource_flow_line_type,
    color = resource_flow_line_colour,
    linewidth = resource_flow_line_width
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = legend_position,
    legend.key.width = unit(legend_width_cm, "cm")
  ) +
  guides(color = guide_legend(title = NULL,
                              nrow = 3),
         linetype = guide_legend(title = NULL,
                                 nrow = 3)) +
  guides(color = "none", 
         linetype = "none")
}
```

```{r}

# Construct empty alpha & beta plots

metaecosystem_type_i = ""
x_min = -0.2
x_max = 30
  
response_variable = "mean_shannon"
y_min_alpha = 0
y_max_alpha = 2.5
alpha_plots = NULL
alpha_plots[[1]] = plot.empty(y_min_alpha,
                              y_max_alpha)

response_variable = "bray_curtis"
y_min_beta = 0
y_max_beta = 1
beta_plots = NULL
beta_plots[[1]] = plot.empty(y_min_beta,
                             y_max_beta)
```

```{r}

# Construct alpha & beta plots

metaecosystem_type_i = c("Medium-Medium meta-ecosystem",
                         "Medium-Medium isolated",
                         "Small-Large meta-ecosystem",
                         "Small-Large isolated")
legend_row_n_input = 2

response_variable = "mean_shannon"
for (i in 1:length(metaecosystem_type_i)) {
  
  alpha_plots[[i+1]] = plot.metaecos.points(ds_metaecosystems,
                               metaecosystem_type_i[1:i],
                               response_variable,
                               legend_row_n_input) +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left),
                             "cm"),
          legend.position = "none") +
    xlim(x_min, x_max) +
    ylim(y_min_alpha, y_max_alpha)
}

response_variable = "bray_curtis"
for (i in 1:length(metaecosystem_type_i)) {
  
  beta_plots[[i+1]] = plot.metaecos.points(ds_metaecosystems,
                               metaecosystem_type_i[1:i],
                               response_variable,
                               legend_row_n_input) +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left),
                             "cm"),
          legend.position = "none") +
    xlim(x_min, x_max) +
    ylim(y_min_beta, y_max_beta)
}
```

```{r}

# Combine plots

p_combined = NULL
for(i in 1:5){
  p_combined[[i]] = ggarrange(
  alpha_plots[[i]] +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank()) +
    font("legend.text", size = size_legend) +
    font("ylab", size = size_y_axis),
  beta_plots[[i]] +
    font("legend.text", size = size_legend) +
    font("xlab", size = size_y_axis) +
    font("ylab", size = size_y_axis) +
    scale_x_continuous(breaks = unique(ds_patches$day)),
  heights = c(0.8, 0.8, 1),
  nrow = 2,
  align = "v",
  label.x = 0.1,
  label.y = 0.8)
}
```

```{r results=FALSE}

# Save combined plots

for(i in 1:5){
  
  png(file = here("results", "figures", disturbance_global_input, "presentations", paste0(i, "_metaecos_diversity.png")),
      width = paper_width,
      height = paper_height,
      units = paper_units,
      res = paper_res)
  
  print(p_combined[[i]])
  
  dev.off()
}
```