---
title: "Untitled"
output: html_document
date: "2023-11-30"
editor_options: 
  chunk_output_type: console
---

```{r}

# Plots parameters
legend_row_n_input = 2

x_min = -0.2
x_max = 30

y_max = 300
y_min = 0

size_y_axis = 22

response_variable = "total_metaecosystem_bioarea_mm2"
metaecosystem_type_all = c("Medium-Medium isolated",
                           "Medium-Medium meta-ecosystem",
                           "Small-Large isolated",
                           "Small-Large meta-ecosystem")
```

```{r}

# Construct plots

plots = NULL
plots[[1]] = plot.empty.plot.presentations(y_min_alpha,
                                           y_max_alpha,
                                           response_variable)

for (i in 1:length(metaecosystem_type_all)) {
  
  plots[[i+1]] = plot.metaecos.points.presentations(ds_metaecosystems,
                                                    metaecosystem_type_all[1:i],
                                                    response_variable,
                                                    legend_row_n_input) +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left),
                             "cm"),
          legend.position = "none") +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01)) + 
    xlim(x_min, x_max) +
    ylim(y_min_alpha, y_max_alpha) +
    theme(axis.text = element_text(size = presentation_axes_size)) + 
    font("legend.text", size = size_legend) +
    font("xlab", size = size_y_axis) +
    font("ylab", size = size_y_axis)
  
  }
```

```{r results=FALSE}

# Save combined plots

for(i in 1:length(metaecosystem_type_all)+1){
  
  png(file = here("results", 
                  "figures", 
                  disturbance_global_input, 
                  "presentations", 
                  paste0("metaecos_productivity_", i, ".png")),
      width = presentation_figure_width,
      height = presentation_figure_height,
      units = presentation_figure_units,
      res = presentation_figure_res)
  
  print(plots[[i]])
  
  dev.off()
  
  }
```