---
title: "SL - Shannon"
output: html_document
date: "2022-12-13"
editor_options: 
  chunk_output_type: console
---

#### Alpha Diversity {.tabset .tabset-pills}

```{r}
p_connected_alpha_effect_size = ds_patches_effect_size %>%
  filter(
    !time_point == 0,
    disturbance == disturbance_input,
    eco_metaeco_type %in% c("S (S_L)", "L (S_L)")
  ) %>%
  ggplot(aes(x = day,
             y = shannon_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(dodging)) +
  geom_line(position = position_dodge(dodging)) +
  geom_errorbar(
    aes(ymin = shannon_d_lower,
        ymax = shannon_d_upper),
    width = .2,
    position = position_dodge(dodging)
  ) +
  labs(
    x = "Day",
    y = y_axis_alpha_diversity_effect_size,
    color = "",
    caption = caption_resource_flow
  ) +
  scale_color_manual(values = c(colour_L,
                                colour_S),
                     labels = c(name_L_connected_to_S,
                                name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_connected_alpha_effect_size
```

```{r}
filtered_data = ds_patches_effect_size %>%
                         filter(time_point >= first_time_point_model,
                                time_point <= last_time_point_model,
                                disturbance == disturbance_input,
                                eco_metaeco_type %in% c("S (S_L)","L (S_L)"))
```

```{r}
full_model = lm(shannon_d ~
                  eco_metaeco_type + 
                  eco_metaeco_type : day,
                data = filtered_data)

summary(full_model)
par(mfrow = c(2, 3))
plot(full_model, which = 1:5)
```

```{r}
null_model = lm(shannon_d ~
                  1,
                data = filtered_data)

AIC = AIC(full_model, null_model)
AIC
AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC = AIC_full - AIC_null
deltaAIC_connected_alpha = round(deltaAIC, digits = 2)

anova = anova(full_model, null_model)
anova
p_value = anova$`Pr(>F)`[2]
if(p_value == 0){
  p_value_connected_alpha = "< 0.001"
} else {
  p_value_connected_alpha = round(p_value, digits = 3)
}
```