---
title: "SL - Shannon"
output: html_document
date: "2022-12-13"
editor_options: 
  chunk_output_type: console
---

```{r}
response_variable = "shannon"
```

```{r}
p_SL_shannon = plot.patches.points(ds_patches, 
                                   patch_type_input,
                                   response_variable) %>%
  print()

p_SL_shannon_2 = plot.patches.points(ds_patches, 
                                     patch_type_input = c("Small connected to large",
                                                        "Small isolated",
                                                        "Large connected to small",
                                                        "Large isolated"),
                                     response_variable) %>%
  print()

p_SL_shannon_3 = plot.patches.points(ds_patches, 
                                     patch_type_input = c("Small connected to large",
                                                          "Small connected to small",
                                                          "Small isolated",
                                                          "Large connected to large",
                                                          "Large connected to small",
                                                          "Large isolated"),
                                     response_variable,
                                     legend_row_n_input = 3) %>%
  print()

p_SL_shannon_presentations = plot.patches.points.presentations(ds_patches,
                                                               patch_type_input,
                                                               response_variable)
```