---
title: "SL patches - Species Composition"
output: html_document
date: "2023-01-26"
editor_options: 
  chunk_output_type: console
---

#### Species Composition {.tabset .tabset-pills}

```{r}
species_composition = ds_patches %>%
  filter(disturbance == disturbance_input) %>%
  select(time_point,
         eco_metaeco_type,
         Ble_dominance:Tet_dominance) %>%
  rename(Ble = Ble_dominance,
         Cep = Cep_dominance,
         Col = Col_dominance,
         Eug = Eug_dominance,
         Eup = Eup_dominance,
         Lox = Lox_dominance,
         Pau = Pau_dominance,
         Pca = Pca_dominance,
         Spi = Spi_dominance,
         Spi_te = Spi_te_dominance,
         Tet = Tet_dominance) %>%
  pivot_longer(Ble:Tet, 
               names_to = "species", 
               values_to = "dominance")

species_composition[is.na(species_composition)] = 0

species_composition = species_composition %>%
  group_by(time_point,
           eco_metaeco_type, 
           species) %>%
  summarise(dominance = mean(dominance),
            dominance = round(dominance, digits = 1))
```

##### Day 0

```{r}
species_composition %>%
  filter(time_point == 0,
         eco_metaeco_type %in% c("S", "S (S_L)", "L", "L (S_L)"),
         !dominance == 0) %>%
  mutate(eco_metaeco_type = factor(eco_metaeco_type, 
                                   levels = c("S", 
                                              "S (S_L)", 
                                              "L", "L (S_L)"))) %>% 
  ggplot(aes(x = eco_metaeco_type,
             y = dominance,
             fill = species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = dominance), 
            position = position_stack(vjust = 0.5))
```

##### Day 4

```{r}
species_composition %>%
  filter(time_point == 1,
         eco_metaeco_type %in% c("S", "S (S_L)", "L", "L (S_L)"),
         !dominance == 0) %>%
  mutate(eco_metaeco_type = factor(eco_metaeco_type, 
                                   levels = c("S", 
                                              "S (S_L)", 
                                              "L", "L (S_L)"))) %>% 
  ggplot(aes(x = eco_metaeco_type,
             y = dominance,
             fill = species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = dominance), 
            position = position_stack(vjust = 0.5))
```

##### Day 8

```{r}
species_composition %>%
  filter(time_point == 2,
         eco_metaeco_type %in% c("S", "S (S_L)", "L", "L (S_L)"),
         !dominance == 0) %>%
  mutate(eco_metaeco_type = factor(eco_metaeco_type, 
                                   levels = c("S", 
                                              "S (S_L)", 
                                              "L", "L (S_L)"))) %>% 
  ggplot(aes(x = eco_metaeco_type,
             y = dominance,
             fill = species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = dominance), 
            position = position_stack(vjust = 0.5))
```

##### Day 12

```{r}
species_composition %>%
  filter(time_point == 3,
         eco_metaeco_type %in% c("S", "S (S_L)", "L", "L (S_L)"),
         !dominance == 0) %>%
  mutate(eco_metaeco_type = factor(eco_metaeco_type, 
                                   levels = c("S", 
                                              "S (S_L)", 
                                              "L", "L (S_L)"))) %>% 
  ggplot(aes(x = eco_metaeco_type,
             y = dominance,
             fill = species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = dominance), 
            position = position_stack(vjust = 0.5))
```

##### Day 16

```{r}
species_composition %>%
  filter(time_point == 4,
         eco_metaeco_type %in% c("S", "S (S_L)", "L", "L (S_L)"),
         !dominance == 0) %>%
  mutate(eco_metaeco_type = factor(eco_metaeco_type, 
                                   levels = c("S", 
                                              "S (S_L)", 
                                              "L", "L (S_L)"))) %>% 
  ggplot(aes(x = eco_metaeco_type,
             y = dominance,
             fill = species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = dominance), 
            position = position_stack(vjust = 0.5))
```

##### Day 20

```{r}
species_composition %>%
  filter(time_point == 5,
         eco_metaeco_type %in% c("S", "S (S_L)", "L", "L (S_L)"),
         !dominance == 0) %>%
  mutate(eco_metaeco_type = factor(eco_metaeco_type, 
                                   levels = c("S", 
                                              "S (S_L)", 
                                              "L", "L (S_L)"))) %>% 
  ggplot(aes(x = eco_metaeco_type,
             y = dominance,
             fill = species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = dominance), 
            position = position_stack(vjust = 0.5))
```

##### Day 24

```{r}
species_composition %>%
  filter(time_point == 6,
         eco_metaeco_type %in% c("S", "S (S_L)", "L", "L (S_L)"),
         !dominance == 0) %>%
  mutate(eco_metaeco_type = factor(eco_metaeco_type, 
                                   levels = c("S", 
                                              "S (S_L)", 
                                              "L", "L (S_L)"))) %>% 
  ggplot(aes(x = eco_metaeco_type,
             y = dominance,
             fill = species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = dominance), 
            position = position_stack(vjust = 0.5))
```

##### Day 28

```{r}
species_composition %>%
  filter(time_point == 7,
         eco_metaeco_type %in% c("S", "S (S_L)", "L", "L (S_L)"),
         !dominance == 0) %>%
  mutate(eco_metaeco_type = factor(eco_metaeco_type, 
                                   levels = c("S", 
                                              "S (S_L)", 
                                              "L", "L (S_L)"))) %>% 
  ggplot(aes(x = eco_metaeco_type,
             y = dominance,
             fill = species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = dominance), 
            position = position_stack(vjust = 0.5))
```