---
title: '.'
output: html_document
date: "2022-12-13"
---

#### Species Densities {.tabset .tabset-pills}

##### Ble

```{r}
p_local_Ble_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Ble_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Ble_d_lower,
        ymax = Ble_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Ble Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Ble_SL
```

##### Cep

```{r}
p_local_Cep_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Cep_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Cep_d_lower,
        ymax = Cep_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Cep Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Cep_SL
```

##### Col

```{r}
p_local_Col_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Col_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Col_d_lower,
        ymax = Col_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Col Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Col_SL
```

##### Eug

```{r}
p_local_Eug_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Eug_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Eug_d_lower,
        ymax = Eug_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Eug Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Eug_SL
```

##### Eup

```{r}
p_local_Eup_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Eup_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Eup_d_lower,
        ymax = Eup_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Eup Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Eup_SL
```

##### Lox

```{r}
p_local_Lox_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Lox_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Lox_d_lower,
        ymax = Lox_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Lox Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Lox_SL
```

##### Pau

```{r}
p_local_Pau_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Pau_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Pau_d_lower,
        ymax = Pau_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Pau Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Pau_SL
```

##### Pca

```{r}
p_local_Pca_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Pca_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Pca_d_lower,
        ymax = Pca_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Pca Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Pca_SL
```

##### Spi

```{r}
p_local_Spi_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Spi_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Spi_d_lower,
        ymax = Spi_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Spi Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Spi_SL
```

##### Spi_te

```{r}
p_local_Spi_te_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Spi_te_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Spi_te_d_lower,
        ymax = Spi_te_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Spi_te Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Spi_te_SL
```

##### Tet

```{r}
p_local_Tet_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Tet_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Tet_d_lower,
        ymax = Tet_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Tet Density Effect Size (Hedge's d)",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6] + 0.7,
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Tet_SL
```

