---
title: "SL - Species dominance"
output: html_document
date: "2023-01-26"
editor_options: 
  chunk_output_type: console
---

#### Species Dominance {.tabset .tabset-pills}

##### Ble

```{r}
p_local_Ble_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Ble_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Ble_dominance_d_lower,
        ymax = Ble_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Ble Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Ble_dominance_SL
```

##### Cep

```{r}
p_local_Cep_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Cep_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Cep_dominance_d_lower,
        ymax = Cep_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Cep Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Cep_dominance_SL
```

##### Col

```{r}
p_local_Col_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Col_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Col_dominance_d_lower,
        ymax = Col_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Col Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Col_dominance_SL
```

##### Eug

```{r}
p_local_Eug_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Eug_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Eug_dominance_d_lower,
        ymax = Eug_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Eug Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Eug_dominance_SL
```

##### Eup

```{r}
p_local_Eup_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Eup_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Eup_dominance_d_lower,
        ymax = Eup_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Eup Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Eup_dominance_SL
```

##### Lox

```{r}
p_local_Lox_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Lox_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Lox_dominance_d_lower,
        ymax = Lox_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Lox Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Lox_dominance_SL
```

##### Pau

```{r}
p_local_Pau_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Pau_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Pau_dominance_d_lower,
        ymax = Pau_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Pau Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Pau_dominance_SL
```

##### Pca

```{r}
p_local_Pca_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Pca_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Pca_dominance_d_lower,
        ymax = Pca_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Pca Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Pca_dominance_SL
```

##### Spi

```{r}
p_local_Spi_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Spi_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Spi_dominance_d_lower,
        ymax = Spi_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Spi Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Spi_dominance_SL
```

##### Spi_te

```{r}
p_local_Spi_te_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Spi_te_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Spi_te_dominance_d_lower,
        ymax = Spi_te_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Spi_te Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Spi_te_dominance_SL
```

##### Tet

```{r}
p_local_Tet_dominance_SL = ds_patches_effect_size %>%
  filter(disturbance == disturbance_input,
         eco_metaeco_type %in% c("S (S_L)", "L (S_L)"),
         day > 0) %>%
  ggplot(aes(x = day,
             y = Tet_dominance_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = Tet_dominance_d_lower,
        ymax = Tet_dominance_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(x = "Day",
       y = "Tet Dominance ES",
       color = "") +
  scale_color_discrete(labels = c(name_L_connected_to_S,
                                  name_S_connected_to_L)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "top"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_local_Tet_dominance_SL
```