---
title: "small_patches"
author: "Emanuele Giacomuzzo"
date: "2022-09-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

#### Median body size {.tabset .tabset-pills}

```{r}
ds_median_body_size %>%
      filter(disturbance == disturbance_input,
             patch_size == "S") %>%
      ggplot(
        aes(
          x = day,
          y = median_body_size,
          group = interaction(day, eco_metaeco_type),
          fill = eco_metaeco_type
        )
      ) +
      geom_boxplot(width = boxplot_width) +
      labs(
        x = x_axis_day,
        y = y_axis_median_body_size,
        fill = ""
      ) +
      scale_fill_manual(
        values = c(colour_isolated, 
                   colour_different_size, 
                   colour_same_size),
        labels = c(
          name_S,
          name_S_connected_to_L,
          name_S_connected_to_S
        )
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"
      ) +
      geom_vline(
        xintercept = first_resource_flow,
        linetype = "dotdash",
        color = "grey",
        size = 0.7
      ) +
      labs(caption = "Vertical grey line: first perturbation")
```

```{r}
p_effect_size = ds_median_body_size_effect_size %>%
  filter(
    !time_point == 0,
    disturbance == disturbance_input,
    eco_metaeco_type %in% c("S (S_S)", "S (S_L)")
  ) %>%
  ggplot(aes(x = day,
             y = median_body_size_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = median_body_size_d_lower,
        ymax = median_body_size_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  labs(
    x = x_axis_day,
    y = y_axis_median_body_size_effect_size,
    color = ""
  ) +
  scale_color_discrete(labels = c(name_S_connected_to_L,
                                  name_S_connected_to_S)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  )

p_effect_size
```