---
title: "small_patches"
author: "Emanuele Giacomuzzo"
date: "2022-10-17"
output: html_document
editor_options: 
  chunk_output_type: console
---

#### Alpha Diversity {.tabset .tabset-pills}

```{r plot-alpha-diversity-of-small-patches-with-single-replicates}
ds_patches %>%
  filter(disturbance == disturbance_input,
         patch_size == "S") %>%
  ggplot(
    aes(
      x = day,
      y = shannon,
      group = culture_ID,
      fill = culture_ID,
      color = culture_ID,
      linetype = eco_metaeco_type
    )
  ) +
  geom_line(stat = "summary", fun = "mean") +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Shannon Index",
    linetype = "",
    caption = caption_resource_flow
  ) +
  scale_linetype_discrete(labels = c(
    name_S_isolated,
    name_S_connected_to_L,
    name_S_connected_to_S
  ))  +
  scale_x_continuous(breaks = unique(ds_patches$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  )
```

```{r}
ds_patches %>%
  filter(disturbance == disturbance_input,
         patch_size == "S") %>%
  ggplot(aes(
    x = day,
    y = shannon,
    group = interaction(day, eco_metaeco_type),
    fill = eco_metaeco_type
  )) +
  geom_boxplot(width = boxplot_width) +
  labs(
    x = "Day",
    y = "Alpha Diversity (Shannon Index)",
    fill = "",
    caption = caption_resource_flow
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  scale_fill_manual(
    values = c(colour_isolated, colour_different_size, colour_same_size),
    labels = c(
      name_S_isolated,
      name_S_connected_to_L,
      name_S_connected_to_S
    )
  ) +
  scale_x_continuous(breaks = unique(ds_patches$day)) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  )
```

```{r}
p_effect_size = ds_patches_effect_size %>%
  filter(
    !time_point == 0,
    disturbance == disturbance_input,
    eco_metaeco_type %in% c("S (S_S)", "S (S_L)")
  ) %>%
  ggplot(aes(x = day,
             y = shannon_d,
             color = eco_metaeco_type)) +
  geom_point(position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_errorbar(
    aes(ymin = shannon_d_lower,
        ymax = shannon_d_upper),
    width = .2,
    position = position_dodge(0.5)
  ) +
  geom_vline(
    xintercept = resource_flow_days[1],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[2],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[3],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[4],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[5],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_vline(
    xintercept = resource_flow_days[6],
    linetype = "dotdash",
    color = "grey",
    size = 0.7
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dotted",
    color = "black",
    size = 0.7
  ) +
  labs(
    x = "Day",
    y = "Shannon Index Effect Size (Hedge's d)",
    color = ""
  ) +
  scale_color_discrete(labels = c(name_S_connected_to_L,
                                  name_S_connected_to_S)) +
  scale_x_continuous(breaks = unique(ds_patches_effect_size$day)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) 

p_effect_size
```

```{r choose-time-points-small-alpha}
filtered_data = ds_patches_effect_size %>%
                         filter(time_point >= first_time_point_model,
                                time_point <= last_time_point_model,
                                disturbance == disturbance_input,
                                eco_metaeco_type %in% c("S (S_S)", "S (S_L)"))
```

```{r small-patches-full-model-small-alpha}
full_model = lm(shannon_d ~                  
                  eco_metaeco_type + 
                  eco_metaeco_type : day,
                  data = filtered_data)

par(mfrow = c(2,3))
plot(full_model, which = 1:5)

null_model = lm(shannon_d ~                  
                  1,
                  data = filtered_data)

anova = anova(full_model, null_model)
AIC = AIC(full_model, null_model)

anova
AIC

p_value = anova$`Pr(>F)`[2]

AIC_full = AIC$AIC[1]
AIC_null = AIC$AIC[2]
deltaAIC =  AIC_full - AIC_null

R2_full = glance(full_model)$r.squared
R2_null = glance(null_model)$r.squared
R2_P = R2_full - R2_null

p_value = round(p_value, digits = 2)
R2_full = round(R2_full, digits = 2)
R2_P = round(R2_P, digits = 2)
deltaAIC = round(deltaAIC, digits = 2)
```

```{r}
final_figure = p_effect_size +
  labs(title = paste0("ΔAIC = ", deltaAIC, ", p = ", p_value, ", R2 (pach type) = ", R2_P))

final_figure
```

```{r}
final_figure +
  theme_bw(base_size = presentation_size) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none"
  ) +
  labs(caption = "")

ggsave(here("results", "presentations", "small_alpha.png"))
```