---
title: "Patch biomass: small patches"
author: "Emanuele Giacomuzzo"
date: "2022-08-02"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r}
response_variable = "bioarea_µm2_per_ml"
```

```{r}
plot.patches.boxplots(patch_type_input,
                       response_variable)

plot.patches.points(patch_type_input,
                       response_variable)

plot.patches.points.ES(patch_type_input,
                       paste0(response_variable, "_d"))
```

*Analysis*

-   Filter data

```{r choose-time-points}

patch_type_input_model = c("Small connected to small",
                                 "Small connected to large")

filtered_data = ds_patches_effect_size %>%
                         filter(time_point >= first_time_point_model,
                                time_point <= last_time_point_model,
                                patch_type %in% patch_type_input_model)
```

-   Full model

```{r}
full_model = lm(bioarea_per_ml_d ~                  
                  patch_type +
                  patch_type : day,
                  data = filtered_data)

summary(full_model)
par(mfrow = c(2,3))
plot(full_model, which = 1:5)
```

-   Effects of `patch_type`

```{r small-patches-full-model}
null_model = lm(bioarea_per_ml_d ~                  
                  patch_type : day,
                  data = filtered_data)

summary(null_model)
par(mfrow = c(2,3))
plot(null_model, which = 1:5)
model_stats = compute.model.stats(full_model,
                    null_model,
                    "linear_model")

model_stats
```

-   Effects of `patch_type : day`

```{r}
null_model = lm(bioarea_per_ml_d ~                  
                  patch_type,
                  data = filtered_data)

summary(null_model)
par(mfrow = c(2,3))
plot(null_model, which = 1:5)
model_stats = compute.model.stats(full_model,
                    null_model,
                    "linear_model")

model_stats

results_small_patches_biomass_patch_type_day = paste0(
  "Interaction between size of the connected patch and day on the biomass effect size in small patches: ",
  "P value = ", 
  model_stats$p_value, 
  ", ΔAIC = ", 
  model_stats$deltaAIC, 
  ", R2 = ", 
  model_stats$R2)
results_small_patches_biomass_patch_type_day
```
