---
title: "Untitled"
output: html_document
date: "2023-04-26"
editor_options: 
  chunk_output_type: console
---

```{r}
#Save results table
results_table %>%
  write.csv(file = here("results", "results_table.csv"), 
            row.names = F)
```

```{r}
#Read results table
results_table = read.csv(here("results", "results_table.csv"))
```

```{r}
#Define level names
level_names = data.frame(
  old = NA,
  new = NA) %>%
  add_row(old = "Small-Large meta-ecosystem , Small-Large isolated", 
          new = "Small-Large (connect vs isolated)") %>%
  add_row(old = "Medium-Medium meta-ecosystem , Medium-Medium isolated", 
          new = "Medium-Medium (connect vs isolated)") %>%
  add_row(old = "Small-Large meta-ecosystem , Medium-Medium meta-ecosystem", 
          new = "Metaecos (Small-Large vs Medium-Medium)") %>%
  add_row(old = "Medium-Medium isolated , Small-Large isolated", 
          new = "Isolated (Small-Large vs Medium-Medium)") %>%
  add_row(old = "Medium-Medium meta-ecosystem , Small-Large meta-ecosystem", 
          new = "Metaecos (Small-Large vs Medium-Medium)") %>%
  add_row(old = "Small-Large isolated , Medium-Medium isolated", 
          new = "Isolated (Small-Large vs Medium-Medium)") %>%
  
  add_row(old = "Small isolated , Medium isolated , Large isolated", 
          new = "Isolated patches") %>%
  
  add_row(old = "Small connected to large , Small isolated", 
          new = "Small (isolated or connected to large)") %>%
  add_row(old = "Small isolated , Small connected to large", 
          new = "Small (isolated or connected to large)") %>%
  add_row(old = "Small connected to small , Small connected to large", 
          new = "Small (connected to small or large)") %>%
  add_row(old = "Small connected to large , Small connected to small", 
          new = "Small (connected to small or large)") %>%
  
  add_row(old = "Large connected to small , Large isolated", 
          new = "Large (isolated or connected to small)") %>%
  add_row(old = "Large isolated , Large connected to small", 
          new = "Large (isolated or connected to small)") %>%
  add_row(old = "Large connected to small , Large connected to large", 
          new = "Large (connected to small or large)") %>%
  add_row(old = "Large connected to large , Large connected to small", 
          new = "Large (connected to small or large)") %>%
  add_row(old = "Large connected to small , Large connected to large , without t4", 
          new = "Large (connected to small or large) without t4") %>%
  add_row(old = "Small connected to small , Large connected to large , without t4", 
          new = "Small (connected to small or large) without t4") %>%
  slice(-1)
```

```{r}
#Change level names
for(name_input in 1:nrow(level_names)){
  results_table$Levels <- gsub(level_names$old[name_input], 
                               level_names$new[name_input], 
                               results_table$Levels)
}
```

```{r}
#Reorder level names
results_table$Levels <- factor(results_table$Levels, levels = c("Metaecos (Small-Large vs Medium-Medium)",
                                                                "Small-Large (connect vs isolated)",
                                                                "Medium-Medium (connect vs isolated)", 
                                                                "Isolated patches",
                                                                "Small (connected to small or large)",
                                                                "Large (connected to small or large)",
                                                                "Small (isolated or connected to large)",
                                                                "Large (isolated or connected to small)",
                                                                "Small (connected to small or large) without t4",
                                                                "Large (connected to small or large) without t4"))
```

```{r}
#Define response names
response_names = data.frame(
  old = NA,
  new = NA) %>%
  add_row(old = "mean_shannon", 
          new = "Alpha Diversity") %>%
  add_row(old = "bioarea_mm2_per_ml_d", 
          new = "Bioarea Density ES") %>%
  add_row(old = "shannon_d", 
          new = "Shannon Index ES") %>%
  add_row(old = "bioarea_mm2_per_ml", 
          new = "Bioarea Density") %>%
  add_row(old = "shannon", 
          new = "Shannon Index") %>%
  add_row(old = "total_metaecosystem_bioarea_mm2", 
          new = "Tot Bioarea") %>%
  add_row(old = "bray_curtis", 
          new = "Beta Diversity") %>%
  add_row(old = "metaecosystem_richness", 
          new = "Gamma Diversity") %>%
  slice(-1)
```

```{r}
#Change response names
for(name_input in 1:nrow(response_names)) {
  results_table$Response <- gsub(response_names$old[name_input],
                                 response_names$new[name_input],
                                 results_table$Response)
}
```

```{r}
#Reorder response names
results_table$Response <- factor(results_table$Response, levels = c("Shannon Index",
                                                                    "Bioarea Density",
                                                                    "Tot Bioarea",
                                                                    "Alpha Diversity",
                                                                    "Beta Diversity",
                                                                    "Gamma Diversity",
                                                                    "Bioarea Density ES",
                                                                    "Log Bioarea Density ES",
                                                                    "Shannon Index ES",
                                                                    "Log Shannon ES",
                                                                    ""))
```

```{r}
#Round up AIC, p-value, and R digits
AIC_digits = 1
p_digits = 3
R_digits = 2

results_table = results_table %>%
  mutate(ΔAIC_full = round(ΔAIC_full, digits = AIC_digits),
         p_full = round(p_full, digits = p_digits),
         ΔR2_full = round(ΔR2_full, digits = R_digits),
         ΔAIC_fix = round(ΔAIC_fix, digits = AIC_digits),
         p_fix = round(p_fix, digits = p_digits),
         ΔR2_fix = round(ΔR2_fix, digits = R_digits))
```

```{r}
#Add evidence column
results_table = results_table %>%
  mutate(min_p = pmin(p_full, p_fix),
         evidence = "",
         evidence = ifelse(min_p > 0.1, 
                           "none",
                           evidence),
         evidence = ifelse(min_p < 0.1, 
                           "\\* weak",
                           evidence),
         evidence = ifelse(min_p < 0.05, 
                           "** moderate",
                           evidence),
         evidence = ifelse(min_p < 0.01, 
                           "*** strong",
                           evidence),
         evidence = ifelse(min_p < 0.001, 
                           "**** very strong",
                           evidence)) %>%
  select(-min_p)
```

```{r}
#Modify p value column
results_table = results_table %>%
  mutate(
    p_full = as.character(p_full),
    p_full = ifelse(p_full < 0.001,
                    "< 0.001",
                    p_full),
    p_fix = as.character(p_fix),
    p_fix = ifelse(p_fix < 0.001,
                   "< 0.001",
                   p_fix)
  )
```

```{r}
#Take off the NAs
results_table = results_table %>%
  select(-ΔR2_fix) %>%
  select(-ΔR2_full)
```