---
title: "Untitled"
output: html_document
date: "2023-10-09"
editor_options: 
  chunk_output_type: console
---

```{r}
### --- Productivity - PRESENTATIONS --- ###

png(file = here("results", "figures", disturbance_global_input, "presentation_productivity.png"),
    width = presentation_figure_width, 
         height = presentation_figure_height, 
         units = presentation_figure_units, 
         res = presentation_figure_res)

p=ggarrange(
   p_small_biomass_presentations +
    rremove("xlab") +
    rremove("ylab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = presentation_legend_size),
  p_large_biomass_presentations +
    rremove("xlab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = presentation_legend_size) +
    font("ylab", size = presentation_y_axis_size), 
  p_isolated_biomass_presentations +
    rremove("ylab") +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = presentation_x_axis_size) + 
  scale_x_continuous(breaks = unique(ds_patches$day)),
  nrow = 3,
  heights = c(0.9,0.9,1),
  common.legend = TRUE,
  #common.y = TRUE,
  align = "v",
  #labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8
) %>%
  print()
```

```{r results=FALSE}
dev.off()
```

```{r}
### --- Productivity - PRESENTATIONS --- ###

png(file = here("results", "figures", disturbance_global_input, "presentation_shannon.png"),
    width = presentation_figure_width, 
         height = presentation_figure_height, 
         units = presentation_figure_units, 
         res = presentation_figure_res)

p=ggarrange(
   p_small_shannon_presentations +
    rremove("xlab") +
    rremove("ylab") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          plot.margin = unit(c(ggarrange_margin_top,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) +
    font("legend.text", size = presentation_legend_size),
  p_large_shannon_presentations +
    rremove("ylab") +
    theme(plot.margin = unit(c(ggarrange_margin_left,
                               ggarrange_margin_right,
                               ggarrange_margin_bottom,
                               ggarrange_margin_left), 
                             "cm")) + 
    font("xlab", size = presentation_x_axis_size) + 
  scale_x_continuous(breaks = unique(ds_patches$day)),
  nrow = 2,
  heights = c(0.9,1),
  common.legend = TRUE,
  #common.y = TRUE,
  align = "v",
  #labels = c("(a)", "(b)"),
  label.x = 0.1,
  label.y = 0.8
) %>%
  print()
```

```{r results=FALSE}
dev.off()
```

